In [2]:
import pandas as pd

df = pd.read_json("/Users/suyashmali/Thesis/LLM/icecat_data_train.json")

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 489902 entries, 1072689 to 1008771
Data columns (total 45 columns):
 #   Column                                      Non-Null Count   Dtype
---  ------                                      --------------   -----
 0   Brand                                       489902 non-null  object
 1   BrandInfo.BrandLocalName                    489902 non-null  object
 2   BrandInfo.BrandLogo                         488765 non-null  object
 3   BrandInfo.BrandName                         489902 non-null  object
 4   BrandLogo                                   488765 non-null  object
 5   BrandPartCode                               489902 non-null  object
 6   BulletPoints                                455119 non-null  object
 7   Category.CategoryID                         489902 non-null  int64
 8   Category.Name.Language                      489902 non-null  object
 9   Category.Name.Value                         489902 non-null  object
 10  Description.Disclaimer                      436174 non-null  object
 11  Description.ID                              436174 non-null  float64
 12  Description.LeafletPDFURL                   436174 non-null  object
 13  Description.LongDesc                        436174 non-null  object
 14  Description.LongProductName                 436174 non-null  object
 15  Description.ManualPDFSize                   428798 non-null  float64
 16  Description.ManualPDFURL                    436174 non-null  object
 17  Description.MiddleDesc                      436174 non-null  object
 18  Description.PDFSize                         432872 non-null  float64
 19  Description.URL                             429271 non-null  object
 20  Description.Updated                         436174 non-null  object
 21  EndOfLifeDate                               489902 non-null  object
 22  GTIN                                        489902 non-null  object
 23  IcecatId                                    489902 non-null  int64
 24  ProductFamily.ProductFamilyID               489902 non-null  int64
 25  ProductName                                 489902 non-null  object
 26  ProductSeries.SeriesID                      489902 non-null  int64
 27  ReleaseDate                                 489902 non-null  object
 28  SummaryDescription.LongSummaryDescription   489902 non-null  object
 29  SummaryDescription.ShortSummaryDescription  489902 non-null  object
 30  Title                                       489902 non-null  object
 31  Description.WarrantyInfo                    258658 non-null  object
 32  Description                                 53728 non-null   object
 33  ProductFamily.Language                      117738 non-null  object
 34  ProductFamily.Value                         117738 non-null  object
 35  ProductSeries.Language                      77673 non-null   object
 36  ProductSeries.Value                         77673 non-null   object
 37  BulletPoints.BulletPointsId                 34783 non-null   float64
 38  BulletPoints.Language                       34783 non-null   object
 39  BulletPoints.Updated                        34783 non-null   object
 40  BulletPoints.Values                         34783 non-null   object
 41  VirtualCategory                             43137 non-null   object
 42  SummaryDescription                          0 non-null       float64
 43  pathlist_ids                                489902 non-null  object
 44  pathlist_names                              489902 non-null  object
dtypes: float64(5), int64(4), object(36)
memory usage: 171.9+ MB

In [38]:
df.head()

,Brand,BrandInfo.BrandLocalName,BrandInfo.BrandLogo,BrandInfo.BrandName,BrandLogo,BrandPartCode,BulletPoints,Category.CategoryID,Category.Name.Language,Category.Name.Value,Description.Disclaimer,Description.ID,Description.LeafletPDFURL,Description.LongDesc,Description.LongProductName,Description.ManualPDFSize,Description.ManualPDFURL,Description.MiddleDesc,Description.PDFSize,Description.URL,Description.Updated,EndOfLifeDate,GTIN,IcecatId,ProductFamily.ProductFamilyID,ProductName,ProductSeries.SeriesID,ReleaseDate,SummaryDescription.LongSummaryDescription,SummaryDescription.ShortSummaryDescription,Title,Description.WarrantyInfo,Description,ProductFamily.Language,ProductFamily.Value,ProductSeries.Language,ProductSeries.Value,BulletPoints.BulletPointsId,BulletPoints.Language,BulletPoints.Updated,BulletPoints.Values,VirtualCategory,SummaryDescription,pathlist_ids,pathlist_names
1072689,ASUS,,https://images.icecat.biz/img/brand/thumb/161_352df2a0298f4fc6b9b82e2d4f8aa4fa.jpg,ASUS,https://images.icecat.biz/img/brand/thumb/161_352df2a0298f4fc6b9b82e2d4f8aa4fa.jpg,K31CD-IT049T,[],153,EN,PCs/Workstations,,57169981.0,,"<b>Smart Multimedia Performance</b><br>\nVivoPC K31CD is powered by the 6th generation Intel® processors to give you significantly faster and more efficient multitasking performance over previous iterations. VivoPC K31CD enhances your daily computing experience, making online shopping, writing blogs, conducting presentations, or watching movies all the more enjoyable. <br>\n<br>\n<b>Ultra-Realistic 4K/UHD Visuals</b><br>\nVivoPC K31CD is with discrete NVIDIA or AMD graphics to bring home entertainment to the next level. It supports 4K/UHD (3840 x2160) displays so you can enjoy the latest movies, browse the web, or view photos in all their glory.<br>\n<br>\n<b>Expansive Audio, tuned by experts</b><br>\nA mixture of hardware, software, and tuning, ASUS SonicMaster was developed with the clear goal of giving you the best PC audio. A professional codec ensures precise sound performance; while an optimized amplifier, larger speakers and resonance chambers deliver powerful audio output and deeper bass. Additional signal processing helps fine tune the hardware, filtering noise and improving clarity so you can enjoy unrivalled audio on K31CD.<br>\n<br>\n<b>Windows 10 Home</b><br>\nWindows 10 Home brings the desktop back to the forefront, complete with the familiar convenience of the Start Menu. It also adds an Edge browser that lets you access the web with blistering speed and useful new functions. <br>\n<br>\n<b>SuperSpeed USB 3.1 transmission</b><br>\nVivoPC K31CD features SuperSpeed USB 3.1 transfering data up to 20 times faster than USB 2.0, and 2 times faster than USB 3.0. Besides, it also comes with all the connectivity options you need. HDMI output ports lets you hook your VivoPC K31CD up to an HDTV to supersize your entertainment. SATA 6Gbit/s ports offer blisteringly fast data transfer speeds, letting you save large files or quickly load games. <br>\n<br>\n<b>Ultra-fast connectivity</b><br>\nWith wireless transfer rates up to 433Mbit/s with compatible routers, 802.11ac Wi-Fi is around 8 times faster than 802.11g and around 3 times faster than 802.11n, making the VivoPC K31CD Series capable of streaming 4K/UHD video without the inconvenience of network cables.<br>\n<br>\n<b>ASUS desktops – Most recommended<br>\nWindows desktop brand</b><br>\nInnovation, design and reliability are at the heart of all ASUS computers. ASUS has won a PCMag.com Readers' Choice Award for its desktops four years running, leading the competition in both overall satisfaction and likelihood to be recommended. This proves that ASUS is better at delivering what customers want than rival Windows desktop PC companies. ASUS also had the lowest percentage of units needing repairs within the last 12 months, further proof of its trusted quality and reliability.<br>\n<br>\n<b>Trust worthy quality and reliability</b><br>\nASUS desktop PCs are subjected to a series of rigorous noise, vibration, drop, and thermal shock tests to ensure they meet our exacting standards and exceed those used by other manufacturers. So you can rest assured that your new computer can cope with extremes of dry, icy -40℃ to hot and humid 60℃ environments, as well as the bumps and knocks during shipping.","Intel Core i7-6700 (8M Cache, 3.4GHz), 16GB RAM, 1000GB HDD, Intel HD Graphics 530, Ethernet, Windows 10",0.0,,,0.0,https://www.asus.com/Tower-PCs/VivoPC-K31CD/,2017-06-20 09:29:04,,[4712900548402],35540060,0,K31CD-IT049T,1,,"ASUS K31CD-IT049T. Processor frequency: 3.4 GHz, Processor family: 6th gen Intel® Core™ i7, Processor model: i7-6700. Internal memory: 16 GB, Internal memory type: DDR4-SDRAM. Total storage capacity: 1000 GB, Storage media: HDD, Card reader integrated. Optical drive type: DVD-RW. On-board graphics adapter model: Intel® HD Graphics 530, Discrete graphics adapter model: NVIDIA® GeForce® GTX 950. Operating system installed: Windows 10 Home. Chassis type: Tower. Product type: PC. Product colour: Black","ASUS K31CD-IT049T, 3.4 GHz, 6th gen Intel® Core™ i7, 16 GB, 1000 GB, DVD-RW, Windows 10 Home",ASUS K31CD-IT049T PC 6th gen Intel® Core™ i7 i7-6700 16 GB DDR4-SDRAM 1000 GB HDD Black Tower,None,None,None,None,None,None,NaN,None,None,None,"[{'VirtualCategoryID': 195, 'UNCATID': '43171895', 'Value': 'PCs', 'Language': 'EN'}]",NaN,2833>150>153,Computers & Electronics>Computers>PCs/Workstations
906402,HP,,https://images.icecat.biz/img/brand/thumb/1_91e0e5b25690437cb026012c624a00ad.jpg,HP,https://images.icecat.biz/img/brand/thumb/1_91e0e5b25690437cb026012c624a00ad.jpg,686915-A41,[],2509,EN,Notebook Spare Parts,,40435749.0,,,Keyboard in midnight black finish with backlight for use on all computer models in Belgium (includes keyboard cable and keyboard backlight cable),0.0,,,0.0,https://www.hp.com/,2015-04-19 14:18:49,,[],20932444,1,686915-A41,0,,"HP 686915-A41. Type: Keyboard. Keyboard language: Belgian, Keyboard backlit. Brand compatibility: HP, Compatibility: Pavilion m6","HP 686915-A41, Keyboard, Belgian, Keyboard backlit, HP, Pavilion m6",HP 686915-A41 notebook spare part Keyboard,,None,None,None,None,None,NaN,None,None,None,None,NaN,2833>150>8355>2509,Computers & Electronics>Computers>Notebook Parts & Accessories>Notebook Spare Parts
411281,C2G,,https://images.icecat.biz/img/brand/thumb/2834_0fe501c2c3204f37b195bb21483fcd4a.jpg,C2G,https://images.icecat.biz/img/brand/thumb/2834_0fe501c2c3204f37b195bb21483fcd4a.jpg,37745,[],953,EN,Fibre Optic Cables,,23898946.0,,"Get the performance you demand at a price that makes sense with Plenum-Rated 9/125 Singlemode Fiber Patch Cords from Cables To Go. They provide high bandwidth and transmission rates and support longer distances, but are still cost effective. They also provide the fire protection required to run these cables within walls and air plenums without the need for conduit. Perfect for use with today’s high speed networks while providing headroom for tomorrow’s higher bandwidth requirements.<br>\r\n<br>\r\nThese multicolored fiber optic patch cables enable you to quickly identify various applications present in your fiber distribution system. The connectors on each end are color-coded for easy identification in a congested patch field.<br>\r\n<br>\r\n<b>Features:</b><br>\r\n<br>\r\n - A cost effective solution that provides higher bandwidth and support for longer distances<br>\r\n - Perfect for use in Gigabit Ethernet applications<br>\r\n - Headroom for tomorrow’s higher bandwidth needs<br>\r\n - CMP rated cable jacket provides the fire protection required to run these cables within walls and air plenums without the need for conduit<br>\r\n - Color-coded connector keys available in red, blue, green and black<br>\r\n - Connectors: (2) ST to (2) SC<br>\r\n - Buffer OD: 900 µm<br>\r\n - Jacket OD: 3.0 mm<br>\r\n - Jacket color: Blue<br>\r\n - Attenuation @1310 nm: 1.0 dB/km<br>\r\n - Attenuation @1550 nm: 0.75 dB/km<br>\r\n - Maximum tensile load: 100 N/cm<br>\r\n - Loaded min. bend radius: 5 cm<br>\r\n - Unloaded min. bend radius: 3 cm<br>\r\n - Crush resistance: 750 N/cm<br>\r\n - Impact resistance: 1000 cycles<br>\r\n - Flex resistance: 5000 cycles",1m ST/SC Plenum-Rated 9/125 Duplex Single-Mode Fiber Patch Cable - Blue,0.0,,,0.0,https://www.cablestogo.com/product.asp?cat_id=2333&sku=37745&st=37745,2009-06-26 14:00:19,,[],3090266,1,1m ST/SC Plenum-Rated 9/125 Duplex Single-Mode Fiber Patch Cable - Blue,1,,"C2G 1m ST/SC Plenum-Rated 9/125 Duplex Single-Mode Fiber Patch Cable - Blue. Cable length: 1 m, Connector 1: ST, Connector 2: SC, Connector gender: Male connector / Male connector, Cable colour: Blue","C2G 1m ST/SC Plenum-Rated 9/125 Duplex Single-Mode Fiber Patch Cable - Blue, 1 m, ST, SC, Male connector / Male connector, Blue","C2G 1m ST/SC Plenum-Rated 9/125 Duplex Single-Mode Fiber Patch Cable - Blue fiber optic cable 39.4"" (1 m)",Lifetime warranty against defects of materials and workmanship,None,None,None,None,None,NaN,None,None,None,None,NaN,2833>830>953,Computers & Electronics>Computer Cables>Fibre Optic Cables
425903,HP,,https://images.icecat.biz/img/brand/thumb/1_91e0e5b25690437cb026012c624a00ad.jpg,HP,https://images.icecat.biz/img/brand/thumb/1_91e0e5b25690437cb026012c624a00ad.jpg,FA889AA#AC3,[],8194,EN,Handheld Mobile Computer Spare Parts,,2230345.0,,Keeping an extra source of power nearby means your iPAQ Voice Messenger can run for longer periods away from your home or office.,"1100 mAh, Lithium Ion, Standard Battery",0.0,,,0.0,https://h18004.www1.hp.com/products/quickspecs/12657_div/12657_div.html,2013-03-11 10:31:57,,[],861193,1,FA889AA,1,,"HP FA889AA. Product type: Battery, Product colour: White, Battery technology: Lithium-Ion (Li-Ion). Width: 54 mm, Depth: 36 mm, Height: 6 mm. Number of batteries included: 1 pc(s)","HP FA889AA, Battery, White, Lithium-Ion (Li-Ion), 1100 mAh, 54 mm, 36 mm",HP FA889AA Battery,,None,None,None,None,None,NaN,None,None,None,None,NaN,2833>150>8194,Computers & Electronics>Computers>Handheld Mobile Computer Spare Parts
1047582,Lenovo,,https://images.icecat.biz/img/brand/thumb/728_2299a3e013664f2d827c919bc743fff0.jpg,Lenovo,https://images.icecat.biz/img/brand/thumb/728_2299a3e013664f2d827c919bc743fff0.jpg,109559U,[],153,EN,PCs/Workstations,,38547582.0,https://pdfs.icecat.biz/pdf/38547582-4292.pdf,"The C30 builds on its award-winning design as the world's smallest dual-CPU workstation, supporting two of the latest-generation Intel® Xeon® processors and faster memory performance, and comes with the Windows® 7 Professional OS. The ISV-certified ThinkStation C30 workstations are engineered from the ground up for the Financial Services sector, Computer-Aided Design (CAD) and Digital Content Creation (DCC) centers.<br>\n<br>\nThe C30 comes preloaded with Windows® 7 Professional and supports up to two Intel® Xeon® E5 2600 series processors, with Turbo Boost Technologyy, up to 128GB of Error Correcting Code (ECC) memory @ 1600MHz, and up to an 800W (90%efficient) power supply for high-performance in a compact form factor. Enhanced Experience 3.0<br>\n<br>\nWe've partnered with NVIDIA® to deliver professional-grade workstation graphic solutions, yielding superior application performance and stability.<br>\n<br>\nThe ThinkStation C30 workstation is certified by multiple leading ISVs, ensuring maximum performance and reliability. The certification also includes support from ISVs if software operational issues occur. Additionally, Error Correcting Code (ECC) memory provides greater data accuracy, improves system up-time, and protects against loss of data due to memory error. And the unique thermal design of the ThinkStation workstation is engineered for maximum cool air delivery to key components, reducing the risk of hardware failure.<br>\n<br>\n- Intel® vPro™ with Active Management Technology (AMT) allows IT personnel to access, diagnose, repair, manage, and secure workstations from remote locations, saving time and reducing maintenance costs.<br>\n- Tool-less interior enables quick and easy maintenance and upgrades of key components.<br>\n- User-friendly design features like a recessed power button prevents potential loss due to accidental shutdown.<br>\n- Front-access media ports with illuminated I/O icons allow you to easily connect devices to the right I/O ports, even in dark environments.<br>\n<br>\nBuilt with 50% post-consumer content, along with an 80 PLUS® Gold-certified 90% efficient power supply, the ThinkStation C30 workstation is friendly to the planet and your bottom line. Additionally, the C30 features several environmental certifications.","Intel Xeon E5-2620 (15M Cache, 2.00 GHz, 7.20 GT/s Intel QPI), 4GB ECC DDR3, 300GB SAS HDD, NVIDIA Quadro 2000D (1GB), DVD-RW, Gigabit Ethernet, Windows 7 Professional 64-bit",0.0,,,1261059.0,https://shop.lenovo.com/us/en/workstations/thinkstation/thinkstation-c-series.html,2013-06-24 11:41:08,,[],13902717,1400,C30,1,,"Lenovo ThinkStation C30. Processor frequency: 2 GHz, Processor family: Intel® Xeon® E5 Family, Processor model: E5-2620. Internal memory: 4 GB, Internal memory type: DDR3-SDRAM. Total storage capacity: 300 GB, Storage media: HDD. Optical drive type: DVD-RW. Discrete graphics adapter model: NVIDIA® Quadro® 2000. Operating system installed: Windows 7 Professional, Operating system architecture: 64-bit. Chassis type: Tower. Product type: Workstation. Weight: 18.5 kg. Product colour: Black","Lenovo ThinkStation C30, 2 GHz, Intel® Xeon® E5 Family, 4 GB, 300 GB, DVD-RW, Windows 7 Professional",Lenovo ThinkStation C30 Intel® Xeon® E5 Family E5-2620 4 GB DDR3-SDRAM 300 GB HDD Black Tower Workstation,3 Yr Onsite,None,EN,ThinkStation,None,None,NaN,None,None,None,"[{'VirtualCategoryID': 194, 'UNCATID': '43171896', 'Value': 'Workstations', 'Language': 'EN'}]",NaN,2833>150>153,Computers & Electronics>Computers>PCs/Workstations

In [39]:
df.isna()

,Brand,BrandInfo.BrandLocalName,BrandInfo.BrandLogo,BrandInfo.BrandName,BrandLogo,BrandPartCode,BulletPoints,Category.CategoryID,Category.Name.Language,Category.Name.Value,Description.Disclaimer,Description.ID,Description.LeafletPDFURL,Description.LongDesc,Description.LongProductName,Description.ManualPDFSize,Description.ManualPDFURL,Description.MiddleDesc,Description.PDFSize,Description.URL,Description.Updated,EndOfLifeDate,GTIN,IcecatId,ProductFamily.ProductFamilyID,ProductName,ProductSeries.SeriesID,ReleaseDate,SummaryDescription.LongSummaryDescription,SummaryDescription.ShortSummaryDescription,Title,Description.WarrantyInfo,Description,ProductFamily.Language,ProductFamily.Value,ProductSeries.Language,ProductSeries.Value,BulletPoints.BulletPointsId,BulletPoints.Language,BulletPoints.Updated,BulletPoints.Values,VirtualCategory,SummaryDescription,pathlist_ids,pathlist_names
1072689,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,True,True,True,True,True,True,True,True,False,True,False,False
906402,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,True,True,True,True,True,True,True,True,True,False,False
411281,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,True,True,True,True,True,True,True,True,True,False,False
425903,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,True,True,True,True,True,True,True,True,True,False,False
1047582,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,True,True,True,True,True,True,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1093316,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,True,True,True,False,True,False,False
886679,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,True,True,True,True,True,True,True,True,True,False,False
35003,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,True,True,True,True,True,True,True,True,True,False,False
779133,False,False,False,False,False,False,False,False,False,False,True,True,True,True,True,True,True,True,True,True,True,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,True,True,True,True,False,True,False,False
1008771,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,True,True,True,True,True,True,True,True,True,True,False,False

In [40]:
print(df['pathlist_names'].iloc[12])

Computers & Electronics>TVs & Monitors>Computer Monitors

In [41]:
df[df["ProductName"] == "K360"][["pathlist_names", "Brand", "ProductName", "Category.Name.Value"]]

,pathlist_names,Brand,ProductName,Category.Name.Value
568885,Computers & Electronics>Data Input Devices>Keyboards,Logitech,K360,Keyboards
568887,Computers & Electronics>Data Input Devices>Keyboards,Logitech,K360,Keyboards
572867,Computers & Electronics>Data Input Devices>Keyboards,Logitech,K360,Keyboards
571706,Computers & Electronics>Data Input Devices>Keyboards,Logitech,K360,Keyboards
572864,Computers & Electronics>Data Input Devices>Keyboards,Logitech,K360,Keyboards
569791,Computers & Electronics>Data Input Devices>Keyboards,Logitech,K360,Keyboards
568972,Computers & Electronics>Data Input Devices>Keyboards,Logitech,K360,Keyboards
567570,Computers & Electronics>Data Input Devices>Keyboards,Logitech,K360,Keyboards
567384,Computers & Electronics>Data Input Devices>Keyboards,Logitech,K360,Keyboards
572862,Computers & Electronics>Data Input Devices>Keyboards,Logitech,K360,Keyboards
567451,Computers & Electronics>Data Input Devices>Keyboards,Logitech,K360,Keyboards
569790,Computers & Electronics>Data Input Devices>Keyboards,Logitech,K360,Keyboards
572857,Computers & Electronics>Data Input Devices>Keyboards,Logitech,K360,Keyboards
567940,Computers & Electronics>Data Input Devices>Keyboards,Logitech,K360,Keyboards
567482,Computers & Electronics>Data Input Devices>Keyboards,Logitech,K360,Keyboards
568862,Computers & Electronics>Data Input Devices>Keyboards,Logitech,K360,Keyboards
567379,Computers & Electronics>Data Input Devices>Keyboards,Logitech,K360,Keyboards
567274,Computers & Electronics>Data Input Devices>Keyboards,Logitech,K360,Keyboards
567807,Computers & Electronics>Data Input Devices>Keyboards,Logitech,K360,Keyboards
568847,Computers & Electronics>Data Input Devices>Keyboards,Logitech,K360,Keyboards
570012,Computers & Electronics>Data Input Devices>Keyboards,Logitech,K360,Keyboards
572865,Computers & Electronics>Data Input Devices>Keyboards,Logitech,K360,Keyboards

In [42]:
# df[df["BrandPartCode"] == "DRACUSB6-EU"][["pathlist_names", "Brand", "ProductName", "Category.Name.Value"]]

In [43]:
    # "Title",
    # "BrandInfo.BrandName",
    # "ProductName",
    # "Category.Name.Value",

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 489902 entries, 1072689 to 1008771
Data columns (total 45 columns):
 #   Column                                      Non-Null Count   Dtype
---  ------                                      --------------   -----
 0   Brand                                       489902 non-null  object
 1   BrandInfo.BrandLocalName                    489902 non-null  object
 2   BrandInfo.BrandLogo                         488765 non-null  object
 3   BrandInfo.BrandName                         489902 non-null  object
 4   BrandLogo                                   488765 non-null  object
 5   BrandPartCode                               489902 non-null  object
 6   BulletPoints                                455119 non-null  object
 7   Category.CategoryID                         489902 non-null  int64
 8   Category.Name.Language                      489902 non-null  object
 9   Category.Name.Value                         489902 non-null  object
 10  Description.Disclaimer                      436174 non-null  object
 11  Description.ID                              436174 non-null  float64
 12  Description.LeafletPDFURL                   436174 non-null  object
 13  Description.LongDesc                        436174 non-null  object
 14  Description.LongProductName                 436174 non-null  object
 15  Description.ManualPDFSize                   428798 non-null  float64
 16  Description.ManualPDFURL                    436174 non-null  object
 17  Description.MiddleDesc                      436174 non-null  object
 18  Description.PDFSize                         432872 non-null  float64
 19  Description.URL                             429271 non-null  object
 20  Description.Updated                         436174 non-null  object
 21  EndOfLifeDate                               489902 non-null  object
 22  GTIN                                        489902 non-null  object
 23  IcecatId                                    489902 non-null  int64
 24  ProductFamily.ProductFamilyID               489902 non-null  int64
 25  ProductName                                 489902 non-null  object
 26  ProductSeries.SeriesID                      489902 non-null  int64
 27  ReleaseDate                                 489902 non-null  object
 28  SummaryDescription.LongSummaryDescription   489902 non-null  object
 29  SummaryDescription.ShortSummaryDescription  489902 non-null  object
 30  Title                                       489902 non-null  object
 31  Description.WarrantyInfo                    258658 non-null  object
 32  Description                                 53728 non-null   object
 33  ProductFamily.Language                      117738 non-null  object
 34  ProductFamily.Value                         117738 non-null  object
 35  ProductSeries.Language                      77673 non-null   object
 36  ProductSeries.Value                         77673 non-null   object
 37  BulletPoints.BulletPointsId                 34783 non-null   float64
 38  BulletPoints.Language                       34783 non-null   object
 39  BulletPoints.Updated                        34783 non-null   object
 40  BulletPoints.Values                         34783 non-null   object
 41  VirtualCategory                             43137 non-null   object
 42  SummaryDescription                          0 non-null       float64
 43  pathlist_ids                                489902 non-null  object
 44  pathlist_names                              489902 non-null  object
dtypes: float64(5), int64(4), object(36)
memory usage: 171.9+ MB

In [10]:
df.isna().sum()

Brand                                              0
BrandInfo.BrandLocalName                           0
BrandInfo.BrandLogo                             1137
BrandInfo.BrandName                                0
BrandLogo                                       1137
BrandPartCode                                      0
BulletPoints                                   34783
Category.CategoryID                                0
Category.Name.Language                             0
Category.Name.Value                                0
Description.Disclaimer                         53728
Description.ID                                 53728
Description.LeafletPDFURL                      53728
Description.LongDesc                           53728
Description.LongProductName                    53728
Description.ManualPDFSize                      61104
Description.ManualPDFURL                       53728
Description.MiddleDesc                         53728
Description.PDFSize                            57030
Description.URL                                60631
Description.Updated                            53728
EndOfLifeDate                                      0
GTIN                                               0
IcecatId                                           0
ProductFamily.ProductFamilyID                      0
ProductName                                        0
ProductSeries.SeriesID                             0
ReleaseDate                                        0
SummaryDescription.LongSummaryDescription          0
SummaryDescription.ShortSummaryDescription         0
Title                                              0
Description.WarrantyInfo                      231244
Description                                   436174
ProductFamily.Language                        372164
ProductFamily.Value                           372164
ProductSeries.Language                        412229
ProductSeries.Value                           412229
BulletPoints.BulletPointsId                   455119
BulletPoints.Language                         455119
BulletPoints.Updated                          455119
BulletPoints.Values                           455119
VirtualCategory                               446765
SummaryDescription                            489902
pathlist_ids                                       0
pathlist_names                                     0
dtype: int64

In [11]:
df.columns

Index(['Brand', 'BrandInfo.BrandLocalName', 'BrandInfo.BrandLogo',
       'BrandInfo.BrandName', 'BrandLogo', 'BrandPartCode', 'BulletPoints',
       'Category.CategoryID', 'Category.Name.Language', 'Category.Name.Value',
       'Description.Disclaimer', 'Description.ID', 'Description.LeafletPDFURL',
       'Description.LongDesc', 'Description.LongProductName',
       'Description.ManualPDFSize', 'Description.ManualPDFURL',
       'Description.MiddleDesc', 'Description.PDFSize', 'Description.URL',
       'Description.Updated', 'EndOfLifeDate', 'GTIN', 'IcecatId',
       'ProductFamily.ProductFamilyID', 'ProductName',
       'ProductSeries.SeriesID', 'ReleaseDate',
       'SummaryDescription.LongSummaryDescription',
       'SummaryDescription.ShortSummaryDescription', 'Title',
       'Description.WarrantyInfo', 'Description', 'ProductFamily.Language',
       'ProductFamily.Value', 'ProductSeries.Language', 'ProductSeries.Value',
       'BulletPoints.BulletPointsId', 'BulletPoints.Language',
       'BulletPoints.Updated', 'BulletPoints.Values', 'VirtualCategory',
       'SummaryDescription', 'pathlist_ids', 'pathlist_names'],
      dtype='object')

In [12]:
df["pathlist_names"].unique()

array(['Computers & Electronics>Computers>PCs/Workstations',
       'Computers & Electronics>Computers>Notebook Parts & Accessories>Notebook Spare Parts',
       'Computers & Electronics>Computer Cables>Fibre Optic Cables',
       'Computers & Electronics>Computers>Handheld Mobile Computer Spare Parts',
       'Computers & Electronics>Software>Software Licenses/Upgrades',
       'Computers & Electronics>Telecom & Navigation>Mobile Phone Spare Parts',
       'Computers & Electronics>Printers & Scanners>Printing Supplies>Toner Cartridges',
       'Computers & Electronics>Batteries & Power Supplies>UPS Batteries',
       'Computers & Electronics>TVs & Monitors>Computer Monitors',
       'Computers & Electronics>Data Storage>Data Storage Devices>USB Flash Drives',
       'Computers & Electronics>Warranty & Support>Warranty & Support Extensions',
       'Computers & Electronics>Computers>Notebooks',
       'Computers & Electronics>Data Storage>Data Storage Mediums>Optical Disc Cases',
       'Computers & Electronics>Data Input Devices>Keyboards',
       'Computers & Electronics>Consumer Audio & Video Equipment>Audio Equipment Parts & Accessories>Headphones',
       'Computers & Electronics>Computers>Servers',
       'Computers & Electronics>Consumer Audio & Video Equipment>AV Extenders',
       'Computers & Electronics>Batteries & Power Supplies>Power Supply Units',
       'Computers & Electronics>Computers>Tablets',
       'Computers & Electronics>Data Storage>Data Storage Devices>Internal Hard Drives',
       'Computers & Electronics>TVs & Monitors>TVs',
       'Computers & Electronics>Software>Antivirus Security Software',
       'Computers & Electronics>Computer Cables>Networking Cables',
       'Computers & Electronics>Computer Cables>DisplayPort Cables',
       'Computers & Electronics>Data Storage>Data Storage Devices>Internal Solid State Drives',
       'Computers & Electronics>Computer Components>System Components>Graphics Cards',
       'Computers & Electronics>Computer Components>System Components>Server/Workstation Motherboards',
       'Computers & Electronics>Photo & Video Equipment>Cameras & Camcorders>Camcorders',
       'Computers & Electronics>Computer Components>System Components>Processors',
       'Computers & Electronics>Printers & Scanners>Print & Scan Accessories>Printer/Scanner Spare Parts',
       'Computers & Electronics>Computers>All-in-One PCs/Workstations',
       'Computers & Electronics>TVs & Monitors>Flat Panel Mount Accessories',
       'Computers & Electronics>Projectors>Projection Lenses',
       'Computers & Electronics>Computer Components>System Components>Memory Modules',
       'Computers & Electronics>Computer Components>System Components>Motherboards',
       'Computers & Electronics>Batteries & Power Supplies>Power Adapters & Inverters',
       'Computers & Electronics>Data Input Devices>Mice',
       'Computers & Electronics>Telecom & Navigation>Mobile Device Keyboards',
       'Computers & Electronics>Printers & Scanners>Printing Equipment>Laser Printers',
       'Computers & Electronics>Computers>Tablet Cases',
       'Computers & Electronics>Photo & Video Equipment>Cameras & Camcorders>Action Sports Cameras',
       'Computers & Electronics>Data Storage>Data Storage Devices>External Hard Drives',
       'Computers & Electronics>Computer Components>Chassis Components>Rack Accessories',
       'Computers & Electronics>Computers>Notebook Parts & Accessories>Notebook Docks & Port Replicators',
       'Computers & Electronics>Computer Cables>Power Cables',
       'Computers & Electronics>Data Storage>Data Storage Mediums>Blank CDs',
       'Computers & Electronics>Networking>Network Switches',
       'Computers & Electronics>Telecom & Navigation>Smartphones',
       'Computers & Electronics>TVs & Monitors>Display Privacy Filters',
       'Computers & Electronics>Projectors>Projector Mount Accessories',
       'Computers & Electronics>Software>Computer Utilities>Printer Software',
       'Computers & Electronics>Computer Components>Chassis Components>Computer Case Parts',
       'Computers & Electronics>Projectors>Projector Lamps',
       'Computers & Electronics>Telecom & Navigation>Mobile Phone Cases',
       'Computers & Electronics>Data Input Devices>KVM Switches',
       'Computers & Electronics>Computer Cables>USB Cables',
       'Computers & Electronics>Photo & Video Equipment>Photographic Filmmaking Supplies>Photo Paper',
       'Computers & Electronics>Computers>Notebook Parts & Accessories>Notebook Accessories',
       'Computers & Electronics>Printers & Scanners>Printing Supplies>Ink Cartridges',
       'Computers & Electronics>Computer Components>Interface Components>Console Servers',
       'Computers & Electronics>Telecom & Navigation>Holders',
       'Computers & Electronics>Computers>Notebook Parts & Accessories>Notebook Cases',
       'Computers & Electronics>Software>Multimedia Software>Graphics Software',
       'Computers & Electronics>TVs & Monitors>Flat Panel Spare Parts',
       'Computers & Electronics>Printers & Scanners>Print & Scan Accessories>Fusers',
       'Computers & Electronics>Consumer Audio & Video Equipment>Radios',
       'Computers & Electronics>Consumer Audio & Video Equipment>MP3/MP4 Players',
       'Computers & Electronics>Computer Cables>Cable Interface/Gender Adapters',
       'Computers & Electronics>Projectors>Data Projectors',
       'Computers & Electronics>Computer Components>Chassis Components>Mounting Kits',
       'Computers & Electronics>Projectors>Projection Screens',
       'Computers & Electronics>Networking>Remote Management Adapters',
       'Computers & Electronics>Photo & Video Equipment>Camera Accessories>Camera Cases',
       'Computers & Electronics>Data Storage>Data Storage Devices>NAS & Storage Servers',
       'Computers & Electronics>Telecom & Navigation>Telephony Equipment>Telephones',
       'Computers & Electronics>Telecom & Navigation>Screen Protectors',
       'Computers & Electronics>Software>Networking Software>Virtualization Software',
       'Computers & Electronics>Printers & Scanners>Printing Supplies>Printer Kits',
       'Computers & Electronics>Printers & Scanners>Printing Equipment>Multifunctionals',
       'Computers & Electronics>Printers & Scanners>Printing Media>Printing Paper',
       'Computers & Electronics>Printers & Scanners>Printing Media>Printer Labels',
       'Computers & Electronics>Computer Components>Chassis Components>Rack Cabinets',
       'Computers & Electronics>Computers>Server Barebones',
       'Computers & Electronics>Printers & Scanners>Print & Scan Accessories>Trays & Feeders',
       'Computers & Electronics>Batteries & Power Supplies>Uninterruptible Power Supplies (UPSs)',
       'Computers & Electronics>Batteries & Power Supplies>Household Batteries',
       'Computers & Electronics>Photo & Video Equipment>Cameras & Camcorders>Webcams',
       'Computers & Electronics>Consumer Audio & Video Equipment>Soundbar Speakers',
       'Computers & Electronics>TVs & Monitors>Flat Panel Wall Mounts',
       'Computers & Electronics>TVs & Monitors>Signage Displays',
       'Computers & Electronics>Projectors>Projector Accessories',
       'Computers & Electronics>Batteries & Power Supplies>Power Distribution Units (PDUs)',
       'Computers & Electronics>Consumer Audio & Video Equipment>Home Cinema Systems',
       'Computers & Electronics>Consumer Audio & Video Equipment>MP3/MP4 Player Cases',
       'Computers & Electronics>Networking>Network Transceiver Modules',
       'Computers & Electronics>Consumer Audio & Video Equipment>Portable Speakers',
       'Computers & Electronics>Printers & Scanners>Printing Media>Large Format Media',
       'Computers & Electronics>Data Storage>Data Storage Devices>Optical Disc Drives',
       'Computers & Electronics>Software>Multimedia Software>Video Software',
       'Computers & Electronics>Printers & Scanners>Printing Equipment>Dot Matrix Printers',
       'Computers & Electronics>Photo & Video Equipment>Cameras & Camcorders>Camera/Camcorder Batteries',
       'Computers & Electronics>Telecom & Navigation>Mobile Phones',
       'Computers & Electronics>Computer Components>System Components>Networking Cards',
       'Computers & Electronics>Computers>Stylus Pens',
       'Computers & Electronics>Warranty & Support>IT Support Services',
       'Computers & Electronics>Consumer Audio & Video Equipment>Remote Controls',
       'Computers & Electronics>Telecom & Navigation>Mobile Headsets',
       'Computers & Electronics>TVs & Monitors>Touch Screen Overlays',
       'Computers & Electronics>Computer Cables>Video Cable Adapters',
       'Computers & Electronics>Consumer Audio & Video Equipment>Cassette Players',
       'Computers & Electronics>TVs & Monitors>Video Splitters',
       'Computers & Electronics>Data Storage>Data Storage Devices>Card Readers',
       'Computers & Electronics>Networking>PowerLine Network Adapters',
       'Computers & Electronics>Projectors>Projector Mounts',
       'Computers & Electronics>Consumer Audio & Video Equipment>Public Address (PA) Systems',
       'Computers & Electronics>Computer Components>System Components>Interface Cards/Adapters',
       'Computers & Electronics>Printers & Scanners>Printing Supplies>Printer Ribbons',
       'Computers & Electronics>Computer Cables>Cable Protectors',
       'Computers & Electronics>Computer Cables>HDMI Cables',
       'Computers & Electronics>Data Storage>Data Storage Devices>Memory Cards',
       'Computers & Electronics>Computer Components>Chassis Components>Computer Cases',
       'Computers & Electronics>Computers>Handheld Device Accessories',
       'Computers & Electronics>Photo & Video Equipment>Cameras & Camcorders>Digital Cameras',
       'Computers & Electronics>Computer Cables>Wire Connectors',
       'Computers & Electronics>Consumer Audio & Video Equipment>Digital Media Players',
       'Computers & Electronics>Computers>Backpack PCs',
       'Computers & Electronics>TVs & Monitors>Touch Screen Monitors',
       'Computers & Electronics>Consumer Audio & Video Equipment>Loudspeakers',
       'Computers & Electronics>Networking>WLAN Access Points',
       'Computers & Electronics>Photo & Video Equipment>Camera Accessories>Lens Hoods',
       'Computers & Electronics>Printers & Scanners>Scanning Equipment>Scanners',
       'Computers & Electronics>Software>Computer Utilities>Storage Software',
       'Computers & Electronics>Computer Cables>SCSI Cables',
       'Computers & Electronics>TVs & Monitors>Flat Panel Floor Stands',
       'Computers & Electronics>Printers & Scanners>Printing Equipment>POS Printers',
       'Computers & Electronics>Printers & Scanners>Printing Supplies>Printer Rollers',
       'Computers & Electronics>Batteries & Power Supplies>Power Banks',
       'Computers & Electronics>Software>Computer Utilities>General Utility Software',
       'Computers & Electronics>Data Storage>Data Storage Devices>Tape Drives',
       'Computers & Electronics>Office Electronics>Calculators',
       'Computers & Electronics>Computer Components>Chassis Components>Computer Cooling Components',
       'Computers & Electronics>Networking>Wireless Routers',
       'Computers & Electronics>Networking>Patch Panels',
       'Computers & Electronics>Data Storage>Data Storage Devices>Disk Arrays',
       'Computers & Electronics>Software>Computer Utilities>Backup Recovery Software',
       'Computers & Electronics>Networking>Network Extenders',
       'Computers & Electronics>Consumer Audio & Video Equipment>Home Audio Sets',
       'Computers & Electronics>Consumer Audio & Video Equipment>Audio Equipment Parts & Accessories>Headsets',
       'Computers & Electronics>Computers>PC/Workstation Barebones',
       'Computers & Electronics>Computer Components>Chassis Components>Storage Drive Enclosures',
       'Computers & Electronics>Computers>POS Systems',
       'Computers & Electronics>Data Storage>Data Storage Mediums>Blank Blu-Ray Discs',
       'Computers & Electronics>Consumer Audio & Video Equipment>Video Switches',
       'Computers & Electronics>Printers & Scanners>Print & Scan Accessories>Duplex Units',
       'Computers & Electronics>Printers & Scanners>Printing Supplies>Printer Drums',
       'Computers & Electronics>Computer Cables>SATA Cables',
       'Computers & Electronics>Consumer Audio & Video Equipment>Portable DVD/Blu-Ray Players',
       'Computers & Electronics>Consumer Audio & Video Equipment>DVD/Blu-Ray Players',
       'Computers & Electronics>Computer Cables>SCART Cables',
       'Computers & Electronics>Printers & Scanners>Print & Scan Accessories>Printer Memory',
       'Computers & Electronics>Smart Wearables>Sport Watch Accessories',
       'Computers & Electronics>Computer Cables>Lightning Cables',
       'Computers & Electronics>Printers & Scanners>Printing Equipment>Inkjet Printers',
       'Computers & Electronics>Consumer Audio & Video Equipment>CD Players',
       'Computers & Electronics>Consumer Audio & Video Equipment>Dictaphones',
       'Computers & Electronics>TVs & Monitors>Digital Photo Frames',
       'Computers & Electronics>Software>Computer Utilities>System Management Software',
       'Computers & Electronics>Printers & Scanners>Printing Supplies>Printer Cleaning',
       'Computers & Electronics>Computer Components>Chassis Components>Heat Sink Compounds',
       'Computers & Electronics>Data Storage>Data Storage Devices>Floppy Drives',
       'Computers & Electronics>Networking>Network Switch Components',
       'Computers & Electronics>Batteries & Power Supplies>Uninterruptible Power Supplies (UPSs) Accessories',
       'Computers & Electronics>Data Storage>Data Storage Mediums>High Density Removable Media Blank Disks',
       'Computers & Electronics>Computer Cables>Coaxial Cables',
       'Computers & Electronics>Consumer Audio & Video Equipment>Speaker Sets',
       'Computers & Electronics>Computer Cables>VGA Cables',
       'Computers & Electronics>Computer Components>Chassis Components>Hardware Cooling Accessories',
       'Computers & Electronics>Computer Components>Interface Components>Interface Hubs',
       'Computers & Electronics>Photo & Video Equipment>Camera Accessories>Camera Mounting Accessories',
       'Computers & Electronics>Photo & Video Equipment>Camera Accessories>Action Sports Camera Accessories',
       'Computers & Electronics>Consumer Audio & Video Equipment>USB Graphics Adapters',
       'Computers & Electronics>Computers>Thin Clients',
       'Computers & Electronics>Networking>Network Media Converters',
       'Computers & Electronics>Printers & Scanners>Printing Equipment>Large Format Printers',
       'Computers & Electronics>Printers & Scanners>Printing Equipment>3D Printing Materials',
       'Computers & Electronics>Printers & Scanners>Print & Scan Accessories>Scanner Accessories',
       'Computers & Electronics>TVs & Monitors>Hospitality TVs',
       'Computers & Electronics>Data Storage>Data Storage Mediums>Magnetic Tape Cassettes',
       'Computers & Electronics>Computer Cables>KVM Cables',
       'Computers & Electronics>Telecom & Navigation>Two-Way Radios',
       'Computers & Electronics>Printers & Scanners>Printing Media>Plotter Paper',
       'Computers & Electronics>Consumer Audio & Video Equipment>Video Capturing Devices',
       'Computers & Electronics>Telecom & Navigation>Mobile Device Chargers',
       'Computers & Electronics>Warranty & Support>Installation Services',
       'Computers & Electronics>Data Storage>Data Storage Mediums>Blank DVDs',
       'Computers & Electronics>Data Storage>Data Storage Devices>External Solid State Drives',
       'Computers & Electronics>Printers & Scanners>Printing Supplies>Developer Units',
       'Computers & Electronics>Photo & Video Equipment>Camera Accessories>Camera Lenses',
       'Computers & Electronics>Computer Cables>DVI Cables',
       'Computers & Electronics>Batteries & Power Supplies>Battery Chargers',
       'Computers & Electronics>Printers & Scanners>Printing Media>Printing Films',
       'Computers & Electronics>Batteries & Power Supplies>UPS Battery Cabinets',
       'Computers & Electronics>Printers & Scanners>Printing Equipment>Label Printers',
       'Computers & Electronics>Consumer Audio & Video Equipment>AV Receivers',
       'Computers & Electronics>Computers>Notebook Parts & Accessories>Notebook Cooling Pads',
       'Computers & Electronics>Telecom & Navigation>Navigational Equipment>Navigators',
       'Computers & Electronics>Printers & Scanners>Print & Scan Accessories>Printer Cables',
       'Computers & Electronics>Office Electronics>Fax Machines',
       'Computers & Electronics>TVs & Monitors>Flat Panel Ceiling Mounts',
       'Computers & Electronics>Batteries & Power Supplies>Notebook Power Tips',
       'Computers & Electronics>Printers & Scanners>Printing Supplies>Toner Collectors',
       'Computers & Electronics>Printers & Scanners>Printing Media>Label-Making Tapes',
       'Computers & Electronics>Smart Wearables>Activity Trackers',
       'Computers & Electronics>TVs & Monitors>Stereoscopic 3D Glasses',
       'Computers & Electronics>Computers>E-Book Reader Cases',
       'Computers & Electronics>Consumer Audio & Video Equipment>Portable Stereo Systems',
       'Computers & Electronics>Printers & Scanners>Printing Supplies>Thermal Ribbon',
       'Computers & Electronics>Telecom & Navigation>Peripheral Device Cases',
       'Computers & Electronics>TVs & Monitors>Flat Panel Accessories',
       'Computers & Electronics>Printers & Scanners>Printing Supplies>Print Heads',
       'Computers & Electronics>Photo & Video Equipment>Camera Accessories>Camera Kits',
       'Computers & Electronics>Networking>ISDN Access Devices',
       'Computers & Electronics>Telecom & Navigation>Navigational Equipment>Navigator Cases',
       'Computers & Electronics>Office Electronics>Laminator Pouches',
       'Computers & Electronics>Consumer Audio & Video Equipment>Audio Equipment Parts & Accessories>Microphones',
       'Computers & Electronics>Printers & Scanners>Print & Scan Accessories>Printer Belts',
       'Computers & Electronics>Computer Cables>Serial Attached SCSI (SAS) Cables',
       'Computers & Electronics>Data Storage>Data Storage Mediums>Blank Data Tapes',
       'Computers & Electronics>Computer Components>Chassis Components>Drive Bay Panels',
       'Computers & Electronics>Software>Operating Systems',
       'Computers & Electronics>Consumer Audio & Video Equipment>Docking Speakers',
       'Computers & Electronics>Computers>Tablet Spare Parts',
       'Computers & Electronics>Networking>Network Antennas',
       'Computers & Electronics>Computer Cables>Audio Cables',
       'Computers & Electronics>Consumer Audio & Video Equipment>Computer TV Tuners',
       'Computers & Electronics>Computer Components>Chassis Components>Rack Consoles',
       'Computers & Electronics>Consumer Audio & Video Equipment>Audio Equipment Parts & Accessories>Microphone Parts & Accessories',
       'Computers & Electronics>Networking>Network Switch Modules',
       'Computers & Electronics>Warranty & Support>Maintenance & Support Fees',
       'Computers & Electronics>Computer Components>System Components>RAID Controllers',
       'Computers & Electronics>TVs & Monitors>Flat Panel Desk Mounts',
       'Computers & Electronics>Data Storage>Data Storage Devices>Data Encryption Devices',
       'Computers & Electronics>Telecom & Navigation>Telephony Equipment>Telephone Spare Parts',
       'Computers & Electronics>Batteries & Power Supplies>Portable Device Management Carts & Cabinets',
       'Computers & Electronics>Computer Cables>InfiniBand Cables',
       'Computers & Electronics>Computers>E-Book Readers',
       'Computers & Electronics>Computer Cables>FireWire Cables',
       'Computers & Electronics>Computer Cables>S-Video Cables',
       'Computers & Electronics>Computers>Handheld Mobile Computers',

In [13]:
df["pathlist_names"].nunique()

370

In [14]:
# Drop rows where pathlist_names is missing or not a string
df = df[df['pathlist_names'].notnull() & df['pathlist_names'].apply(lambda x: isinstance(x, str))]

# Keep only those rows where pathlist_names has exactly 2 '>' → which means 3 levels (A > B > C)
df_3level = df[df['pathlist_names'].apply(lambda x: x.count('>') == 2)]

print(f"✅ Found {len(df_3level)} products with exactly 3-level categories.")

✅ Found 289865 products with exactly 3-level categories.

In [15]:
pd.set_option('display.max_columns', None)
# pd.set_option('display.max_rows', None)

In [16]:
df_3level

,Brand,BrandInfo.BrandLocalName,BrandInfo.BrandLogo,BrandInfo.BrandName,BrandLogo,BrandPartCode,BulletPoints,Category.CategoryID,Category.Name.Language,Category.Name.Value,Description.Disclaimer,Description.ID,Description.LeafletPDFURL,Description.LongDesc,Description.LongProductName,Description.ManualPDFSize,Description.ManualPDFURL,Description.MiddleDesc,Description.PDFSize,Description.URL,Description.Updated,EndOfLifeDate,GTIN,IcecatId,ProductFamily.ProductFamilyID,ProductName,ProductSeries.SeriesID,ReleaseDate,SummaryDescription.LongSummaryDescription,SummaryDescription.ShortSummaryDescription,Title,Description.WarrantyInfo,Description,ProductFamily.Language,ProductFamily.Value,ProductSeries.Language,ProductSeries.Value,BulletPoints.BulletPointsId,BulletPoints.Language,BulletPoints.Updated,BulletPoints.Values,VirtualCategory,SummaryDescription,pathlist_ids,pathlist_names
1072689,ASUS,,https://images.icecat.biz/img/brand/thumb/161_...,ASUS,https://images.icecat.biz/img/brand/thumb/161_...,K31CD-IT049T,[],153,EN,PCs/Workstations,,57169981.0,,<b>Smart Multimedia Performance</b><br>\nVivoP...,"Intel Core i7-6700 (8M Cache, 3.4GHz), 16GB RA...",0.0,,,0.0,https://www.asus.com/Tower-PCs/VivoPC-K31CD/,2017-06-20 09:29:04,,[4712900548402],35540060,0,K31CD-IT049T,1,,ASUS K31CD-IT049T. Processor frequency: 3.4 GH...,"ASUS K31CD-IT049T, 3.4 GHz, 6th gen Intel® Cor...",ASUS K31CD-IT049T PC 6th gen Intel® Core™ i7 i...,None,None,None,None,None,None,NaN,None,None,None,"[{'VirtualCategoryID': 195, 'UNCATID': '431718...",NaN,2833>150>153,Computers & Electronics>Computers>PCs/Workstat...
411281,C2G,,https://images.icecat.biz/img/brand/thumb/2834...,C2G,https://images.icecat.biz/img/brand/thumb/2834...,37745,[],953,EN,Fibre Optic Cables,,23898946.0,,Get the performance you demand at a price that...,1m ST/SC Plenum-Rated 9/125 Duplex Single-Mode...,0.0,,,0.0,https://www.cablestogo.com/product.asp?cat_id=...,2009-06-26 14:00:19,,[],3090266,1,1m ST/SC Plenum-Rated 9/125 Duplex Single-Mode...,1,,C2G 1m ST/SC Plenum-Rated 9/125 Duplex Single-...,C2G 1m ST/SC Plenum-Rated 9/125 Duplex Single-...,C2G 1m ST/SC Plenum-Rated 9/125 Duplex Single-...,Lifetime warranty against defects of materials...,None,None,None,None,None,NaN,None,None,None,None,NaN,2833>830>953,Computers & Electronics>Computer Cables>Fibre ...
425903,HP,,https://images.icecat.biz/img/brand/thumb/1_91...,HP,https://images.icecat.biz/img/brand/thumb/1_91...,FA889AA#AC3,[],8194,EN,Handheld Mobile Computer Spare Parts,,2230345.0,,Keeping an extra source of power nearby means ...,"1100 mAh, Lithium Ion, Standard Battery",0.0,,,0.0,https://h18004.www1.hp.com/products/quickspecs...,2013-03-11 10:31:57,,[],861193,1,FA889AA,1,,"HP FA889AA. Product type: Battery, Product col...","HP FA889AA, Battery, White, Lithium-Ion (Li-Io...",HP FA889AA Battery,,None,None,None,None,None,NaN,None,None,None,None,NaN,2833>150>8194,Computers & Electronics>Computers>Handheld Mob...
1047582,Lenovo,,https://images.icecat.biz/img/brand/thumb/728_...,Lenovo,https://images.icecat.biz/img/brand/thumb/728_...,109559U,[],153,EN,PCs/Workstations,,38547582.0,https://pdfs.icecat.biz/pdf/38547582-4292.pdf,The C30 builds on its award-winning design as ...,"Intel Xeon E5-2620 (15M Cache, 2.00 GHz, 7.20 ...",0.0,,,1261059.0,https://shop.lenovo.com/us/en/workstations/thi...,2013-06-24 11:41:08,,[],13902717,1400,C30,1,,Lenovo ThinkStation C30. Processor frequency: ...,"Lenovo ThinkStation C30, 2 GHz, Intel® Xeon® E...",Lenovo ThinkStation C30 Intel® Xeon® E5 Family...,3 Yr Onsite,None,EN,ThinkStation,None,None,NaN,None,None,None,"[{'VirtualCategoryID': 194, 'UNCATID': '431718...",NaN,2833>150>153,Computers & Electronics>Computers>PCs/Workstat...
157385,Lenovo,,https://images.icecat.biz/img/brand/thumb/728_...,Lenovo,https://images.icecat.biz/img/brand/thumb/728_...,00D8199,[],803,EN,Software Licenses/Upgrades,,44877091.0,,SUSE Linux Enterprise Server (SLES)<br>\n<br>\...,SLES for SAP Applications 2 Socket 24x7 SUSE S...,0.0,,,0.0,https://www-01.ibm.com/common/ssi/cgi-bin/ssia...,2015-02-18 13:35:19,,[],20922053,1,00D8199,1,,Lenovo 00D8199. License term in years: 3 year(s),"Lenovo 00D8199, 3 year(s)",Lenovo 00D8199 software license/upgrade,,None,None,None,None,None,NaN,None,None,None,None,NaN,2833>2>803,Computers & Electronics>Software>Software Lice...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
421630,Duracell,,https://images.icecat.biz/img/brand/thumb/338_...,Duracell,https://images.icecat.biz/img/brand/thumb/338_...,5000394015845,[],946,EN,Household Batteries,,36930106.0,,,"16x AAA, LR03, 1.5V",0.0,,,0.0,https://www.duracell.com/en-US/products.jspx,2012-11-05 11:14:50,,[],15744741,1,16 LR03 AAA,1,,Duracell 16 LR03 AAA. Battery type: Single-use...,"Duracell 16 LR03 AAA, Single-use battery, AAA,...",Duracell 16 LR03 AAA Single-use battery Alkaline,,None,None,None,None,None,NaN,None,None,None,None,NaN,2833>2557>946,Computers & Electronics>Batteries & Power Supp...
61851,C2G,,https://images.icecat.biz/img/brand/thumb/2834...,C2G,https://images.icecat.biz/img/brand/thumb/2834...,80247,[],2926,EN,Video Cable Adapters,,23974985.0,,Velocity™ Camcorder Audio/Video Cables from Ca...,2m Velocity Camcorder Audio/Video Cable,0.0,,,0.0,https://www.cablestogo.co.uk/product.asp?produ...,2009-07-07 11:05:07,,[],2132442,1,2m Velocity Camcorder Audio/Video Cable,1,,C2G 2m Velocity Camcorder Audio/Video Cable. C...,"C2G 2m Velocity Camcorder Audio/Video Cable, 2...",C2G 2m Velocity Camcorder Audio/Video Cable 3 ...,,None,None,None,None,None,NaN,None,None,None,None,NaN,2833>830>2926,Computers & Electronics>Computer Cables>Video ...
1093316,Fujitsu,,https://images.icecat.biz/img/brand/thumb/15_b...,Fujitsu,https://images.icecat.biz/img/brand/thumb/15_b...,VFY:P0758PP761CH,[],153,EN,PCs/Workstations,,66803262.0,,The FUJITSU ESPRIMO P758 Desktop provides high...,"Intel Core i7-8700, 1 x 16 GB DDR4 2666 MHz, P...",0.0,,,0.0,https://www.fujitsu.com/fts/products/computing...,2019-02-20 16:35:23,,[],65447409,376,P758,511,,Fujitsu ESPRIMO P758. Processor frequency: 3.2...,"Fujitsu ESPRIMO P758, 3.2 GHz, 8th gen Intel® ...",Fujitsu ESPRIMO P758 8th gen Intel® Core™ i7 i...,1 year,None,EN,ESPRIMO,EN,P,NaN,None,None,None,"[{'VirtualCategoryID': 195, 'UNCATID': '431718...",NaN,2833>150>153,Computers & Electronics>Computers>PCs/Workstat...
35003,Gigabyte,,https://images.icecat.biz/img/brand/thumb/739_...,Gigabyte,https://images.icecat.biz/img/brand/thumb/739_...,28711-ARM01-0CBS,[],195,EN,Mice,,33939877.0,,<b>Mini Size</b><br>\nUltimate Choice for Note...,"Optical, USB, 1000dpi, 61g, Black",0.0,,,0.0,https://www.gigabyte.com/products/product-page...,2012-03-11 00:59:03,,[],12795204,1,Aire M1,1,,Gigabyte Aire M1. Movement detection technolog...,"Gigabyte Aire M1, Optical, USB, 1000 DPI, Black",Gigabyte Aire M1 mouse USB Optical 1000 DPI,2 year,None,None,None,None,None,NaN,None,None,None,None,NaN,2833>191>195,Computers & Electronics>Data Input Devices>Mice
779133,HP,,https://images.icecat.biz/img/brand/thumb/1_91...,HP,https://images.icecat.biz/img/brand/thumb/1_91...,7GN16EA,[],151,EN,Notebooks,None,NaN,None,None,None,NaN,None,None,NaN,None,None,,[0193905768042],71610404,64360,14-dh0062no,5739,17-07-2019,HP Pavilion x360 14-dh0062no. Product type: Hy...,"HP Pavilion x360 14-dh0062no, 8th gen Intel® C...",HP Pavilion x360 14-dh0062no Gold Hybrid (2-in...,None,[],EN,Pavilion x360,EN,14,NaN,None,None,None,"[{'VirtualCategoryID': 329, 'UNCATID': '432115...",NaN,2833>150>151,Computers & Electronics>Computers>Notebooks

In [82]:
df_3level["pathlist_names"].unique()

array(['Computers & Electronics>Computers>PCs/Workstations',
       'Computers & Electronics>Computer Cables>Fibre Optic Cables',
       'Computers & Electronics>Computers>Handheld Mobile Computer Spare Parts',
       'Computers & Electronics>Software>Software Licenses/Upgrades',
       'Computers & Electronics>Telecom & Navigation>Mobile Phone Spare Parts',
       'Computers & Electronics>Batteries & Power Supplies>UPS Batteries',
       'Computers & Electronics>TVs & Monitors>Computer Monitors',
       'Computers & Electronics>Warranty & Support>Warranty & Support Extensions',
       'Computers & Electronics>Computers>Notebooks',
       'Computers & Electronics>Data Input Devices>Keyboards',
       'Computers & Electronics>Computers>Servers',
       'Computers & Electronics>Consumer Audio & Video Equipment>AV Extenders',
       'Computers & Electronics>Batteries & Power Supplies>Power Supply Units',
       'Computers & Electronics>Computers>Tablets',
       'Computers & Electronics>TVs & Monitors>TVs',
       'Computers & Electronics>Software>Antivirus Security Software',
       'Computers & Electronics>Computer Cables>Networking Cables',
       'Computers & Electronics>Computer Cables>DisplayPort Cables',
       'Computers & Electronics>Computers>All-in-One PCs/Workstations',
       'Computers & Electronics>TVs & Monitors>Flat Panel Mount Accessories',
       'Computers & Electronics>Projectors>Projection Lenses',
       'Computers & Electronics>Batteries & Power Supplies>Power Adapters & Inverters',
       'Computers & Electronics>Data Input Devices>Mice',
       'Computers & Electronics>Telecom & Navigation>Mobile Device Keyboards',
       'Computers & Electronics>Computers>Tablet Cases',
       'Computers & Electronics>Computer Cables>Power Cables',
       'Computers & Electronics>Networking>Network Switches',
       'Computers & Electronics>Telecom & Navigation>Smartphones',
       'Computers & Electronics>TVs & Monitors>Display Privacy Filters',
       'Computers & Electronics>Projectors>Projector Mount Accessories',
       'Computers & Electronics>Projectors>Projector Lamps',
       'Computers & Electronics>Telecom & Navigation>Mobile Phone Cases',
       'Computers & Electronics>Data Input Devices>KVM Switches',
       'Computers & Electronics>Computer Cables>USB Cables',
       'Computers & Electronics>Telecom & Navigation>Holders',
       'Computers & Electronics>TVs & Monitors>Flat Panel Spare Parts',
       'Computers & Electronics>Consumer Audio & Video Equipment>Radios',
       'Computers & Electronics>Consumer Audio & Video Equipment>MP3/MP4 Players',
       'Computers & Electronics>Computer Cables>Cable Interface/Gender Adapters',
       'Computers & Electronics>Projectors>Data Projectors',
       'Computers & Electronics>Projectors>Projection Screens',
       'Computers & Electronics>Networking>Remote Management Adapters',
       'Computers & Electronics>Telecom & Navigation>Screen Protectors',
       'Computers & Electronics>Computers>Server Barebones',
       'Computers & Electronics>Batteries & Power Supplies>Uninterruptible Power Supplies (UPSs)',
       'Computers & Electronics>Batteries & Power Supplies>Household Batteries',
       'Computers & Electronics>Consumer Audio & Video Equipment>Soundbar Speakers',
       'Computers & Electronics>TVs & Monitors>Flat Panel Wall Mounts',
       'Computers & Electronics>TVs & Monitors>Signage Displays',
       'Computers & Electronics>Projectors>Projector Accessories',
       'Computers & Electronics>Batteries & Power Supplies>Power Distribution Units (PDUs)',
       'Computers & Electronics>Consumer Audio & Video Equipment>Home Cinema Systems',
       'Computers & Electronics>Consumer Audio & Video Equipment>MP3/MP4 Player Cases',
       'Computers & Electronics>Networking>Network Transceiver Modules',
       'Computers & Electronics>Consumer Audio & Video Equipment>Portable Speakers',
       'Computers & Electronics>Telecom & Navigation>Mobile Phones',
       'Computers & Electronics>Computers>Stylus Pens',
       'Computers & Electronics>Warranty & Support>IT Support Services',
       'Computers & Electronics>Consumer Audio & Video Equipment>Remote Controls',
       'Computers & Electronics>Telecom & Navigation>Mobile Headsets',
       'Computers & Electronics>TVs & Monitors>Touch Screen Overlays',
       'Computers & Electronics>Computer Cables>Video Cable Adapters',
       'Computers & Electronics>Consumer Audio & Video Equipment>Cassette Players',
       'Computers & Electronics>TVs & Monitors>Video Splitters',
       'Computers & Electronics>Networking>PowerLine Network Adapters',
       'Computers & Electronics>Projectors>Projector Mounts',
       'Computers & Electronics>Consumer Audio & Video Equipment>Public Address (PA) Systems',
       'Computers & Electronics>Computer Cables>Cable Protectors',
       'Computers & Electronics>Computer Cables>HDMI Cables',
       'Computers & Electronics>Computers>Handheld Device Accessories',
       'Computers & Electronics>Computer Cables>Wire Connectors',
       'Computers & Electronics>Consumer Audio & Video Equipment>Digital Media Players',
       'Computers & Electronics>Computers>Backpack PCs',
       'Computers & Electronics>TVs & Monitors>Touch Screen Monitors',
       'Computers & Electronics>Consumer Audio & Video Equipment>Loudspeakers',
       'Computers & Electronics>Networking>WLAN Access Points',
       'Computers & Electronics>Computer Cables>SCSI Cables',
       'Computers & Electronics>TVs & Monitors>Flat Panel Floor Stands',
       'Computers & Electronics>Batteries & Power Supplies>Power Banks',
       'Computers & Electronics>Office Electronics>Calculators',
       'Computers & Electronics>Networking>Wireless Routers',
       'Computers & Electronics>Networking>Patch Panels',
       'Computers & Electronics>Networking>Network Extenders',
       'Computers & Electronics>Consumer Audio & Video Equipment>Home Audio Sets',
       'Computers & Electronics>Computers>PC/Workstation Barebones',
       'Computers & Electronics>Computers>POS Systems',
       'Computers & Electronics>Consumer Audio & Video Equipment>Video Switches',
       'Computers & Electronics>Computer Cables>SATA Cables',
       'Computers & Electronics>Consumer Audio & Video Equipment>Portable DVD/Blu-Ray Players',
       'Computers & Electronics>Consumer Audio & Video Equipment>DVD/Blu-Ray Players',
       'Computers & Electronics>Computer Cables>SCART Cables',
       'Computers & Electronics>Smart Wearables>Sport Watch Accessories',
       'Computers & Electronics>Computer Cables>Lightning Cables',
       'Computers & Electronics>Consumer Audio & Video Equipment>CD Players',
       'Computers & Electronics>Consumer Audio & Video Equipment>Dictaphones',
       'Computers & Electronics>TVs & Monitors>Digital Photo Frames',
       'Computers & Electronics>Networking>Network Switch Components',
       'Computers & Electronics>Batteries & Power Supplies>Uninterruptible Power Supplies (UPSs) Accessories',
       'Computers & Electronics>Computer Cables>Coaxial Cables',
       'Computers & Electronics>Consumer Audio & Video Equipment>Speaker Sets',
       'Computers & Electronics>Computer Cables>VGA Cables',
       'Computers & Electronics>Consumer Audio & Video Equipment>USB Graphics Adapters',
       'Computers & Electronics>Computers>Thin Clients',
       'Computers & Electronics>Networking>Network Media Converters',
       'Computers & Electronics>TVs & Monitors>Hospitality TVs',
       'Computers & Electronics>Computer Cables>KVM Cables',
       'Computers & Electronics>Telecom & Navigation>Two-Way Radios',
       'Computers & Electronics>Consumer Audio & Video Equipment>Video Capturing Devices',
       'Computers & Electronics>Telecom & Navigation>Mobile Device Chargers',
       'Computers & Electronics>Warranty & Support>Installation Services',
       'Computers & Electronics>Computer Cables>DVI Cables',
       'Computers & Electronics>Batteries & Power Supplies>Battery Chargers',
       'Computers & Electronics>Batteries & Power Supplies>UPS Battery Cabinets',
       'Computers & Electronics>Consumer Audio & Video Equipment>AV Receivers',
       'Computers & Electronics>Office Electronics>Fax Machines',
       'Computers & Electronics>TVs & Monitors>Flat Panel Ceiling Mounts',
       'Computers & Electronics>Batteries & Power Supplies>Notebook Power Tips',
       'Computers & Electronics>Smart Wearables>Activity Trackers',
       'Computers & Electronics>TVs & Monitors>Stereoscopic 3D Glasses',
       'Computers & Electronics>Computers>E-Book Reader Cases',
       'Computers & Electronics>Consumer Audio & Video Equipment>Portable Stereo Systems',
       'Computers & Electronics>Telecom & Navigation>Peripheral Device Cases',
       'Computers & Electronics>TVs & Monitors>Flat Panel Accessories',
       'Computers & Electronics>Networking>ISDN Access Devices',
       'Computers & Electronics>Office Electronics>Laminator Pouches',
       'Computers & Electronics>Computer Cables>Serial Attached SCSI (SAS) Cables',
       'Computers & Electronics>Software>Operating Systems',
       'Computers & Electronics>Consumer Audio & Video Equipment>Docking Speakers',
       'Computers & Electronics>Computers>Tablet Spare Parts',
       'Computers & Electronics>Networking>Network Antennas',
       'Computers & Electronics>Computer Cables>Audio Cables',
       'Computers & Electronics>Consumer Audio & Video Equipment>Computer TV Tuners',
       'Computers & Electronics>Networking>Network Switch Modules',
       'Computers & Electronics>Warranty & Support>Maintenance & Support Fees',
       'Computers & Electronics>TVs & Monitors>Flat Panel Desk Mounts',
       'Computers & Electronics>Batteries & Power Supplies>Portable Device Management Carts & Cabinets',
       'Computers & Electronics>Computer Cables>InfiniBand Cables',
       'Computers & Electronics>Computers>E-Book Readers',
       'Computers & Electronics>Computer Cables>FireWire Cables',
       'Computers & Electronics>Computer Cables>S-Video Cables',
       'Computers & Electronics>Computers>Handheld Mobile Computers',
       'Computers & Electronics>Networking>Print Servers',
       'Computers & Electronics>Networking>PoE Adapters',
       'Computers & Electronics>Consumer Audio & Video Equipment>Video Converters',
       'Computers & Electronics>Software>Office Suites',
       'Computers & Electronics>Computer Cables>Component (YPbPr) Video Cables',
       'Computers & Electronics>Telecom & Navigation>Mobile Device Dock Stations',
       'Computers & Electronics>Networking>Fibre Optic Adapters',
       'Computers & Electronics>Computers>Embedded Computers',
       'Computers & Electronics>Data Input Devices>Mouse Pads',
       'Computers & Electronics>Networking>Wired Routers',
       'Computers & Electronics>TVs & Monitors>Monitors CRT',
       'Computers & Electronics>Computer Components>All-in-One PC/Workstation Mounts & Stands',
       'Computers & Electronics>Networking>Gateways/Controllers',
       'Computers & Electronics>Computer Cables>Composite Video Cables',
       'Computers & Electronics>Networking>Video Conferencing Systems',
       'Computers & Electronics>Office Electronics>Fax Supplies',
       'Computers & Electronics>Computer Cables>Thunderbolt Cables',
       'Computers & Electronics>Projectors>Projector Cases',
       'Computers & Electronics>Computer Cables>PS/2 Cables',
       'Computers & Electronics>Computer Cables>Serial Cables',
       'Computers & Electronics>Computers>Customer Displays',
       'Computers & Electronics>Software>Service Management Software',
       'Computers & Electronics>Computers>Stick PCs',
       "Computers & Electronics>Computers>Kids' Tablet Accessories",
       'Computers & Electronics>TVs & Monitors>CRT TVs',
       'Computers & Electronics>Computer Cables>Internal Power Cables',
       'Computers & Electronics>Smart Wearables>Smartwatches',
       'Computers & Electronics>Networking>Telephony Cables',
       'Computers & Electronics>Data Input Devices>Wrist Rests',
       'Computers & Electronics>Networking>Network Cable Testers',
       'Computers & Electronics>Computer Cables>Signal Cables',
       'Computers & Electronics>Software>Word Processors',
       'Computers & Electronics>Data Input Devices>Input Device Accessories',
       'Computers & Electronics>Networking>Modems',
       'Computers & Electronics>Office Electronics>Lamination Films',
       'Computers & Electronics>Office Electronics>Smart Card Readers',
       'Computers & Electronics>Smart Wearables>Smartwatch Accessories',
       'Computers & Electronics>Computer Cables>Cable Splitters or Combiners',
       'Computers & Electronics>TVs & Monitors>Head-Mounted Displays',
       'Computers & Electronics>TVs & Monitors>Television Antennas',
       'Computers & Electronics>Consumer Audio & Video Equipment>TV Set-Top Boxes',
       "Computers & Electronics>Computers>Kids' Tablets",
       'Computers & Electronics>Networking>Hardware Firewalls',
       'Computers & Electronics>Telecom & Navigation>Mobile Phone Cables',
       'Computers & Electronics>Computer Components>CPU Holders',
       'Computers & Electronics>Telecom & Navigation>Selfie Sticks',
       'Computers & Electronics>Networking>Network Splitters',
       'Computers & Electronics>Data Input Devices>KVM Extenders',
       'Computers & Electronics>Networking>AV Conferencing Bridges',
       'Computers & Electronics>Consumer Audio & Video Equipment>Audio Turntables',
       'Computers & Electronics>Computer Cables>Cable Boots',
       'Computers & Electronics>Data Input Devices>Touch Pads',
       'Computers & Electronics>Networking>Bridges & Repeaters',
       'Computers & Electronics>Smart Wearables>Sport Watches',
       'Computers & Electronics>Data Input Devices>Other Input Devices',
       'Computers & Electronics>Computer Cables>Parallel Cables',
       'Computers & Electronics>Computer Cables>Ribbon Cables',
       'Computers & Electronics>Telecom & Navigation>Mobile Device Skins',
       'Computers & Electronics>Warranty & Support>IT Courses',
       'Computers & Electronics>Networking>Video Conferencing Cameras',
       'Computers & Electronics>Consumer Audio & Video Equipment>MP3/MP4 Player Accessories',
       'Computers & Electronics>Office Electronics>Paper Shredders',
       'Computers & Electronics>Networking>Network Management Devices',
       'Computers & Electronics>Data Input Devices>Wireless Presenters',
       'Computers & Electronics>Networking>Remote Power Controllers',
       'Computers & Electronics>Telecom & Navigation>Car Kits',
       'Computers & Electronics>Consumer Audio & Video Equipment>Smart TV Boxes',
       'Computers & Electronics>Data Input Devices>Numeric Keypads'],
      dtype=object)

In [83]:
df_3level["pathlist_names"].nunique()

209

In [17]:
df_cleaned = df_3level.drop(columns=[ 'BulletPoints', 'Description', 'VirtualCategory','SummaryDescription', 'pathlist_ids'], errors='ignore')

In [18]:
df_cleaned

,Brand,BrandInfo.BrandLocalName,BrandInfo.BrandLogo,BrandInfo.BrandName,BrandLogo,BrandPartCode,Category.CategoryID,Category.Name.Language,Category.Name.Value,Description.Disclaimer,Description.ID,Description.LeafletPDFURL,Description.LongDesc,Description.LongProductName,Description.ManualPDFSize,Description.ManualPDFURL,Description.MiddleDesc,Description.PDFSize,Description.URL,Description.Updated,EndOfLifeDate,GTIN,IcecatId,ProductFamily.ProductFamilyID,ProductName,ProductSeries.SeriesID,ReleaseDate,SummaryDescription.LongSummaryDescription,SummaryDescription.ShortSummaryDescription,Title,Description.WarrantyInfo,ProductFamily.Language,ProductFamily.Value,ProductSeries.Language,ProductSeries.Value,BulletPoints.BulletPointsId,BulletPoints.Language,BulletPoints.Updated,BulletPoints.Values,pathlist_names
1072689,ASUS,,https://images.icecat.biz/img/brand/thumb/161_...,ASUS,https://images.icecat.biz/img/brand/thumb/161_...,K31CD-IT049T,153,EN,PCs/Workstations,,57169981.0,,<b>Smart Multimedia Performance</b><br>\nVivoP...,"Intel Core i7-6700 (8M Cache, 3.4GHz), 16GB RA...",0.0,,,0.0,https://www.asus.com/Tower-PCs/VivoPC-K31CD/,2017-06-20 09:29:04,,[4712900548402],35540060,0,K31CD-IT049T,1,,ASUS K31CD-IT049T. Processor frequency: 3.4 GH...,"ASUS K31CD-IT049T, 3.4 GHz, 6th gen Intel® Cor...",ASUS K31CD-IT049T PC 6th gen Intel® Core™ i7 i...,None,None,None,None,None,NaN,None,None,None,Computers & Electronics>Computers>PCs/Workstat...
411281,C2G,,https://images.icecat.biz/img/brand/thumb/2834...,C2G,https://images.icecat.biz/img/brand/thumb/2834...,37745,953,EN,Fibre Optic Cables,,23898946.0,,Get the performance you demand at a price that...,1m ST/SC Plenum-Rated 9/125 Duplex Single-Mode...,0.0,,,0.0,https://www.cablestogo.com/product.asp?cat_id=...,2009-06-26 14:00:19,,[],3090266,1,1m ST/SC Plenum-Rated 9/125 Duplex Single-Mode...,1,,C2G 1m ST/SC Plenum-Rated 9/125 Duplex Single-...,C2G 1m ST/SC Plenum-Rated 9/125 Duplex Single-...,C2G 1m ST/SC Plenum-Rated 9/125 Duplex Single-...,Lifetime warranty against defects of materials...,None,None,None,None,NaN,None,None,None,Computers & Electronics>Computer Cables>Fibre ...
425903,HP,,https://images.icecat.biz/img/brand/thumb/1_91...,HP,https://images.icecat.biz/img/brand/thumb/1_91...,FA889AA#AC3,8194,EN,Handheld Mobile Computer Spare Parts,,2230345.0,,Keeping an extra source of power nearby means ...,"1100 mAh, Lithium Ion, Standard Battery",0.0,,,0.0,https://h18004.www1.hp.com/products/quickspecs...,2013-03-11 10:31:57,,[],861193,1,FA889AA,1,,"HP FA889AA. Product type: Battery, Product col...","HP FA889AA, Battery, White, Lithium-Ion (Li-Io...",HP FA889AA Battery,,None,None,None,None,NaN,None,None,None,Computers & Electronics>Computers>Handheld Mob...
1047582,Lenovo,,https://images.icecat.biz/img/brand/thumb/728_...,Lenovo,https://images.icecat.biz/img/brand/thumb/728_...,109559U,153,EN,PCs/Workstations,,38547582.0,https://pdfs.icecat.biz/pdf/38547582-4292.pdf,The C30 builds on its award-winning design as ...,"Intel Xeon E5-2620 (15M Cache, 2.00 GHz, 7.20 ...",0.0,,,1261059.0,https://shop.lenovo.com/us/en/workstations/thi...,2013-06-24 11:41:08,,[],13902717,1400,C30,1,,Lenovo ThinkStation C30. Processor frequency: ...,"Lenovo ThinkStation C30, 2 GHz, Intel® Xeon® E...",Lenovo ThinkStation C30 Intel® Xeon® E5 Family...,3 Yr Onsite,EN,ThinkStation,None,None,NaN,None,None,None,Computers & Electronics>Computers>PCs/Workstat...
157385,Lenovo,,https://images.icecat.biz/img/brand/thumb/728_...,Lenovo,https://images.icecat.biz/img/brand/thumb/728_...,00D8199,803,EN,Software Licenses/Upgrades,,44877091.0,,SUSE Linux Enterprise Server (SLES)<br>\n<br>\...,SLES for SAP Applications 2 Socket 24x7 SUSE S...,0.0,,,0.0,https://www-01.ibm.com/common/ssi/cgi-bin/ssia...,2015-02-18 13:35:19,,[],20922053,1,00D8199,1,,Lenovo 00D8199. License term in years: 3 year(s),"Lenovo 00D8199, 3 year(s)",Lenovo 00D8199 software license/upgrade,,None,None,None,None,NaN,None,None,None,Computers & Electronics>Software>Software Lice...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
421630,Duracell,,https://images.icecat.biz/img/brand/thumb/338_...,Duracell,https://images.icecat.biz/img/brand/thumb/338_...,5000394015845,946,EN,Household Batteries,,36930106.0,,,"16x AAA, LR03, 1.5V",0.0,,,0.0,https://www.duracell.com/en-US/products.jspx,2012-11-05 11:14:50,,[],15744741,1,16 LR03 AAA,1,,Duracell 16 LR03 AAA. Battery type: Single-use...,"Duracell 16 LR03 AAA, Single-use battery, AAA,...",Duracell 16 LR03 AAA Single-use battery Alkaline,,None,None,None,None,NaN,None,None,None,Computers & Electronics>Batteries & Power Supp...
61851,C2G,,https://images.icecat.biz/img/brand/thumb/2834...,C2G,https://images.icecat.biz/img/brand/thumb/2834...,80247,2926,EN,Video Cable Adapters,,23974985.0,,Velocity™ Camcorder Audio/Video Cables from Ca...,2m Velocity Camcorder Audio/Video Cable,0.0,,,0.0,https://www.cablestogo.co.uk/product.asp?produ...,2009-07-07 11:05:07,,[],2132442,1,2m Velocity Camcorder Audio/Video Cable,1,,C2G 2m Velocity Camcorder Audio/Video Cable. C...,"C2G 2m Velocity Camcorder Audio/Video Cable, 2...",C2G 2m Velocity Camcorder Audio/Video Cable 3 ...,,None,None,None,None,NaN,None,None,None,Computers & Electronics>Computer Cables>Video ...
1093316,Fujitsu,,https://images.icecat.biz/img/brand/thumb/15_b...,Fujitsu,https://images.icecat.biz/img/brand/thumb/15_b...,VFY:P0758PP761CH,153,EN,PCs/Workstations,,66803262.0,,The FUJITSU ESPRIMO P758 Desktop provides high...,"Intel Core i7-8700, 1 x 16 GB DDR4 2666 MHz, P...",0.0,,,0.0,https://www.fujitsu.com/fts/products/computing...,2019-02-20 16:35:23,,[],65447409,376,P758,511,,Fujitsu ESPRIMO P758. Processor frequency: 3.2...,"Fujitsu ESPRIMO P758, 3.2 GHz, 8th gen Intel® ...",Fujitsu ESPRIMO P758 8th gen Intel® Core™ i7 i...,1 year,EN,ESPRIMO,EN,P,NaN,None,None,None,Computers & Electronics>Computers>PCs/Workstat...
35003,Gigabyte,,https://images.icecat.biz/img/brand/thumb/739_...,Gigabyte,https://images.icecat.biz/img/brand/thumb/739_...,28711-ARM01-0CBS,195,EN,Mice,,33939877.0,,<b>Mini Size</b><br>\nUltimate Choice for Note...,"Optical, USB, 1000dpi, 61g, Black",0.0,,,0.0,https://www.gigabyte.com/products/product-page...,2012-03-11 00:59:03,,[],12795204,1,Aire M1,1,,Gigabyte Aire M1. Movement detection technolog...,"Gigabyte Aire M1, Optical, USB, 1000 DPI, Black",Gigabyte Aire M1 mouse USB Optical 1000 DPI,2 year,None,None,None,None,NaN,None,None,None,Computers & Electronics>Data Input Devices>Mice
779133,HP,,https://images.icecat.biz/img/brand/thumb/1_91...,HP,https://images.icecat.biz/img/brand/thumb/1_91...,7GN16EA,151,EN,Notebooks,None,NaN,None,None,None,NaN,None,None,NaN,None,None,,[0193905768042],71610404,64360,14-dh0062no,5739,17-07-2019,HP Pavilion x360 14-dh0062no. Product type: Hy...,"HP Pavilion x360 14-dh0062no, 8th gen Intel® C...",HP Pavilion x360 14-dh0062no Gold Hybrid (2-in...,None,EN,Pavilion x360,EN,14,NaN,None,None,None,Computers & Electronics>Computers>Notebooks

In [20]:
df.describe()

,Category.CategoryID,Description.ID,Description.ManualPDFSize,Description.PDFSize,IcecatId,ProductFamily.ProductFamilyID,ProductSeries.SeriesID,BulletPoints.BulletPointsId,SummaryDescription
count,489902.000000,4.361740e+05,4.287980e+05,4.328720e+05,4.899020e+05,489902.000000,489902.000000,3.478300e+04,0.0
mean,1153.717617,4.640968e+07,5.458168e+05,2.217285e+05,2.883804e+07,10788.744181,584.586011,1.417348e+06,NaN
std,1073.865849,1.623788e+07,2.694096e+06,1.085100e+06,2.041610e+07,24040.597754,1549.634199,7.106451e+05,NaN
min,7.000000,1.401000e+03,0.000000e+00,0.000000e+00,1.399000e+03,0.000000,0.000000,3.600000e+01,NaN
25%,170.000000,3.625266e+07,0.000000e+00,0.000000e+00,1.381661e+07,0.000000,1.000000,1.019869e+06,NaN
50%,803.000000,4.752119e+07,0.000000e+00,0.000000e+00,2.558921e+07,1.000000,1.000000,1.395549e+06,NaN
75%,2282.000000,6.024942e+07,0.000000e+00,0.000000e+00,3.659320e+07,1.000000,1.000000,2.052349e+06,NaN
max,8194.000000,6.980787e+07,1.103482e+08,5.618184e+07,7.428240e+07,70543.000000,6728.000000,2.469701e+06,NaN

In [21]:
df_cleaned.info()

<class 'pandas.core.frame.DataFrame'>
Index: 289865 entries, 1072689 to 779133
Data columns (total 40 columns):
 #   Column                                      Non-Null Count   Dtype
---  ------                                      --------------   -----
 0   Brand                                       289865 non-null  object
 1   BrandInfo.BrandLocalName                    289865 non-null  object
 2   BrandInfo.BrandLogo                         288908 non-null  object
 3   BrandInfo.BrandName                         289865 non-null  object
 4   BrandLogo                                   288908 non-null  object
 5   BrandPartCode                               289865 non-null  object
 6   Category.CategoryID                         289865 non-null  int64
 7   Category.Name.Language                      289865 non-null  object
 8   Category.Name.Value                         289865 non-null  object
 9   Description.Disclaimer                      244918 non-null  object
 10  Description.ID                              244918 non-null  float64
 11  Description.LeafletPDFURL                   244918 non-null  object
 12  Description.LongDesc                        244918 non-null  object
 13  Description.LongProductName                 244918 non-null  object
 14  Description.ManualPDFSize                   238887 non-null  float64
 15  Description.ManualPDFURL                    244918 non-null  object
 16  Description.MiddleDesc                      244918 non-null  object
 17  Description.PDFSize                         242827 non-null  float64
 18  Description.URL                             240183 non-null  object
 19  Description.Updated                         244918 non-null  object
 20  EndOfLifeDate                               289865 non-null  object
 21  GTIN                                        289865 non-null  object
 22  IcecatId                                    289865 non-null  int64
 23  ProductFamily.ProductFamilyID               289865 non-null  int64
 24  ProductName                                 289865 non-null  object
 25  ProductSeries.SeriesID                      289865 non-null  int64
 26  ReleaseDate                                 289865 non-null  object
 27  SummaryDescription.LongSummaryDescription   289865 non-null  object
 28  SummaryDescription.ShortSummaryDescription  289865 non-null  object
 29  Title                                       289865 non-null  object
 30  Description.WarrantyInfo                    143067 non-null  object
 31  ProductFamily.Language                      105919 non-null  object
 32  ProductFamily.Value                         105919 non-null  object
 33  ProductSeries.Language                      75802 non-null   object
 34  ProductSeries.Value                         75802 non-null   object
 35  BulletPoints.BulletPointsId                 25263 non-null   float64
 36  BulletPoints.Language                       25263 non-null   object
 37  BulletPoints.Updated                        25263 non-null   object
 38  BulletPoints.Values                         25263 non-null   object
 39  pathlist_names                              289865 non-null  object
dtypes: float64(4), int64(4), object(32)
memory usage: 90.7+ MB

In [22]:
df_cleaned.isnull().sum()

Brand                                              0
BrandInfo.BrandLocalName                           0
BrandInfo.BrandLogo                              957
BrandInfo.BrandName                                0
BrandLogo                                        957
BrandPartCode                                      0
Category.CategoryID                                0
Category.Name.Language                             0
Category.Name.Value                                0
Description.Disclaimer                         44947
Description.ID                                 44947
Description.LeafletPDFURL                      44947
Description.LongDesc                           44947
Description.LongProductName                    44947
Description.ManualPDFSize                      50978
Description.ManualPDFURL                       44947
Description.MiddleDesc                         44947
Description.PDFSize                            47038
Description.URL                                49682
Description.Updated                            44947
EndOfLifeDate                                      0
GTIN                                               0
IcecatId                                           0
ProductFamily.ProductFamilyID                      0
ProductName                                        0
ProductSeries.SeriesID                             0
ReleaseDate                                        0
SummaryDescription.LongSummaryDescription          0
SummaryDescription.ShortSummaryDescription         0
Title                                              0
Description.WarrantyInfo                      146798
ProductFamily.Language                        183946
ProductFamily.Value                           183946
ProductSeries.Language                        214063
ProductSeries.Value                           214063
BulletPoints.BulletPointsId                   264602
BulletPoints.Language                         264602
BulletPoints.Updated                          264602
BulletPoints.Values                           264602
pathlist_names                                     0
dtype: int64

In [23]:
fields_to_keep = [
    "Title",
    "BrandInfo.BrandName",
    "ProductName",
    "Category.Name.Value",  
    "SummaryDescription.LongSummaryDescription",
    # "SummaryDescription.ShortSummaryDescription",
    "Description.LongProductName",
    "Description.LongDesc",
]


# Combine all text fields into one column for LLM or clustering
df_cleaned['metadata_text'] = df_cleaned[fields_to_keep].astype(str).apply(lambda x: ' | '.join(x), axis=1)

In [90]:
df

,Brand,BrandInfo.BrandLocalName,BrandInfo.BrandLogo,BrandInfo.BrandName,BrandLogo,BrandPartCode,BulletPoints,Category.CategoryID,Category.Name.Language,Category.Name.Value,Description.Disclaimer,Description.ID,Description.LeafletPDFURL,Description.LongDesc,Description.LongProductName,Description.ManualPDFSize,Description.ManualPDFURL,Description.MiddleDesc,Description.PDFSize,Description.URL,Description.Updated,EndOfLifeDate,GTIN,IcecatId,ProductFamily.ProductFamilyID,ProductName,ProductSeries.SeriesID,ReleaseDate,SummaryDescription.LongSummaryDescription,SummaryDescription.ShortSummaryDescription,Title,Description.WarrantyInfo,Description,ProductFamily.Language,ProductFamily.Value,ProductSeries.Language,ProductSeries.Value,BulletPoints.BulletPointsId,BulletPoints.Language,BulletPoints.Updated,BulletPoints.Values,VirtualCategory,SummaryDescription,pathlist_ids,pathlist_names
1072689,ASUS,,https://images.icecat.biz/img/brand/thumb/161_352df2a0298f4fc6b9b82e2d4f8aa4fa.jpg,ASUS,https://images.icecat.biz/img/brand/thumb/161_352df2a0298f4fc6b9b82e2d4f8aa4fa.jpg,K31CD-IT049T,[],153,EN,PCs/Workstations,,57169981.0,,"<b>Smart Multimedia Performance</b><br>\nVivoPC K31CD is powered by the 6th generation Intel® processors to give you significantly faster and more efficient multitasking performance over previous iterations. VivoPC K31CD enhances your daily computing experience, making online shopping, writing blogs, conducting presentations, or watching movies all the more enjoyable. <br>\n<br>\n<b>Ultra-Realistic 4K/UHD Visuals</b><br>\nVivoPC K31CD is with discrete NVIDIA or AMD graphics to bring home entertainment to the next level. It supports 4K/UHD (3840 x2160) displays so you can enjoy the latest movies, browse the web, or view photos in all their glory.<br>\n<br>\n<b>Expansive Audio, tuned by experts</b><br>\nA mixture of hardware, software, and tuning, ASUS SonicMaster was developed with the clear goal of giving you the best PC audio. A professional codec ensures precise sound performance; while an optimized amplifier, larger speakers and resonance chambers deliver powerful audio output and deeper bass. Additional signal processing helps fine tune the hardware, filtering noise and improving clarity so you can enjoy unrivalled audio on K31CD.<br>\n<br>\n<b>Windows 10 Home</b><br>\nWindows 10 Home brings the desktop back to the forefront, complete with the familiar convenience of the Start Menu. It also adds an Edge browser that lets you access the web with blistering speed and useful new functions. <br>\n<br>\n<b>SuperSpeed USB 3.1 transmission</b><br>\nVivoPC K31CD features SuperSpeed USB 3.1 transfering data up to 20 times faster than USB 2.0, and 2 times faster than USB 3.0. Besides, it also comes with all the connectivity options you need. HDMI output ports lets you hook your VivoPC K31CD up to an HDTV to supersize your entertainment. SATA 6Gbit/s ports offer blisteringly fast data transfer speeds, letting you save large files or quickly load games. <br>\n<br>\n<b>Ultra-fast connectivity</b><br>\nWith wireless transfer rates up to 433Mbit/s with compatible routers, 802.11ac Wi-Fi is around 8 times faster than 802.11g and around 3 times faster than 802.11n, making the VivoPC K31CD Series capable of streaming 4K/UHD video without the inconvenience of network cables.<br>\n<br>\n<b>ASUS desktops – Most recommended<br>\nWindows desktop brand</b><br>\nInnovation, design and reliability are at the heart of all ASUS computers. ASUS has won a PCMag.com Readers' Choice Award for its desktops four years running, leading the competition in both overall satisfaction and likelihood to be recommended. This proves that ASUS is better at delivering what customers want than rival Windows desktop PC companies. ASUS also had the lowest percentage of units needing repairs within the last 12 months, further proof of its trusted quality and reliability.<br>\n<br>\n<b>Trust worthy quality and reliability</b><br>\nASUS desktop PCs are subjected to a series of rigorous noise, vibration, drop, and thermal shock tests to ensure they meet our exacting standards and exceed those used by other manufacturers. So you can rest assured that your new computer can cope with extremes of dry, icy -40℃ to hot and humid 60℃ environments, as well as the bumps and knocks during shipping.","Intel Core i7-6700 (8M Cache, 3.4GHz), 16GB RAM, 1000GB HDD, Intel HD Graphics 530, Ethernet, Windows 10",0.0,,,0.0,https://www.asus.com/Tower-PCs/VivoPC-K31CD/,2017-06-20 09:29:04,,[4712900548402],35540060,0,K31CD-IT049T,1,,"ASUS K31CD-IT049T. Processor frequency: 3.4 GHz, Processor family: 6th gen Intel® Core™ i7, Processor model: i7-6700. Internal memory: 16 GB, Internal memory type: DDR4-SDRAM. Total storage capacity: 1000 GB, Storage media: HDD, Card reader integrated. Optical drive type: DVD-RW. On-board graphics adapter model: Intel® HD Graphics 530, Discrete graphics adapter model: NVIDIA® GeForce® GTX 950. Operating system installed: Windows 10 Home. Chassis type: Tower. Product type: PC. Product colour: Black","ASUS K31CD-IT049T, 3.4 GHz, 6th gen Intel® Core™ i7, 16 GB, 1000 GB, DVD-RW, Windows 10 Home",ASUS K31CD-IT049T PC 6th gen Intel® Core™ i7 i7-6700 16 GB DDR4-SDRAM 1000 GB HDD Black Tower,None,None,None,None,None,None,NaN,None,None,None,"[{'VirtualCategoryID': 195, 'UNCATID': '43171895', 'Value': 'PCs', 'Language': 'EN'}]",NaN,2833>150>153,Computers & Electronics>Computers>PCs/Workstations
906402,HP,,https://images.icecat.biz/img/brand/thumb/1_91e0e5b25690437cb026012c624a00ad.jpg,HP,https://images.icecat.biz/img/brand/thumb/1_91e0e5b25690437cb026012c624a00ad.jpg,686915-A41,[],2509,EN,Notebook Spare Parts,,40435749.0,,,Keyboard in midnight black finish with backlight for use on all computer models in Belgium (includes keyboard cable and keyboard backlight cable),0.0,,,0.0,https://www.hp.com/,2015-04-19 14:18:49,,[],20932444,1,686915-A41,0,,"HP 686915-A41. Type: Keyboard. Keyboard language: Belgian, Keyboard backlit. Brand compatibility: HP, Compatibility: Pavilion m6","HP 686915-A41, Keyboard, Belgian, Keyboard backlit, HP, Pavilion m6",HP 686915-A41 notebook spare part Keyboard,,None,None,None,None,None,NaN,None,None,None,None,NaN,2833>150>8355>2509,Computers & Electronics>Computers>Notebook Parts & Accessories>Notebook Spare Parts
411281,C2G,,https://images.icecat.biz/img/brand/thumb/2834_0fe501c2c3204f37b195bb21483fcd4a.jpg,C2G,https://images.icecat.biz/img/brand/thumb/2834_0fe501c2c3204f37b195bb21483fcd4a.jpg,37745,[],953,EN,Fibre Optic Cables,,23898946.0,,"Get the performance you demand at a price that makes sense with Plenum-Rated 9/125 Singlemode Fiber Patch Cords from Cables To Go. They provide high bandwidth and transmission rates and support longer distances, but are still cost effective. They also provide the fire protection required to run these cables within walls and air plenums without the need for conduit. Perfect for use with today’s high speed networks while providing headroom for tomorrow’s higher bandwidth requirements.<br>\r\n<br>\r\nThese multicolored fiber optic patch cables enable you to quickly identify various applications present in your fiber distribution system. The connectors on each end are color-coded for easy identification in a congested patch field.<br>\r\n<br>\r\n<b>Features:</b><br>\r\n<br>\r\n - A cost effective solution that provides higher bandwidth and support for longer distances<br>\r\n - Perfect for use in Gigabit Ethernet applications<br>\r\n - Headroom for tomorrow’s higher bandwidth needs<br>\r\n - CMP rated cable jacket provides the fire protection required to run these cables within walls and air plenums without the need for conduit<br>\r\n - Color-coded connector keys available in red, blue, green and black<br>\r\n - Connectors: (2) ST to (2) SC<br>\r\n - Buffer OD: 900 µm<br>\r\n - Jacket OD: 3.0 mm<br>\r\n - Jacket color: Blue<br>\r\n - Attenuation @1310 nm: 1.0 dB/km<br>\r\n - Attenuation @1550 nm: 0.75 dB/km<br>\r\n - Maximum tensile load: 100 N/cm<br>\r\n - Loaded min. bend radius: 5 cm<br>\r\n - Unloaded min. bend radius: 3 cm<br>\r\n - Crush resistance: 750 N/cm<br>\r\n - Impact resistance: 1000 cycles<br>\r\n - Flex resistance: 5000 cycles",1m ST/SC Plenum-Rated 9/125 Duplex Single-Mode Fiber Patch Cable - Blue,0.0,,,0.0,https://www.cablestogo.com/product.asp?cat_id=2333&sku=37745&st=37745,2009-06-26 14:00:19,,[],3090266,1,1m ST/SC Plenum-Rated 9/125 Duplex Single-Mode Fiber Patch Cable - Blue,1,,"C2G 1m ST/SC Plenum-Rated 9/125 Duplex Single-Mode Fiber Patch Cable - Blue. Cable length: 1 m, Connector 1: ST, Connector 2: SC, Connector gender: Male connector / Male connector, Cable colour: Blue","C2G 1m ST/SC Plenum-Rated 9/125 Duplex Single-Mode Fiber Patch Cable - Blue, 1 m, ST, SC, Male connector / Male connector, Blue","C2G 1m ST/SC Plenum-Rated 9/125 Duplex Single-Mode Fiber Patch Cable - Blue fiber optic cable 39.4"" (1 m)",Lifetime warranty against defects of materials and workmanship,None,None,None,None,None,NaN,None,None,None,None,NaN,2833>830>953,Computers & Electronics>Computer Cables>Fibre Optic Cables
425903,HP,,https://images.icecat.biz/img/brand/thumb/1_91e0e5b25690437cb026012c624a00ad.jpg,HP,https://images.icecat.biz/img/brand/thumb/1_91e0e5b25690437cb026012c624a00ad.jpg,FA889AA#AC3,[],8194,EN,Handheld Mobile Computer Spare Parts,,2230345.0,,Keeping an extra source of power nearby means your iPAQ Voice Messenger can run for longer periods away from your home or office.,"1100 mAh, Lithium Ion, Standard Battery",0.0,,,0.0,https://h18004.www1.hp.com/products/quickspecs/12657_div/12657_div.html,2013-03-11 10:31:57,,[],861193,1,FA889AA,1,,"HP FA889AA. Product type: Battery, Product colour: White, Battery technology: Lithium-Ion (Li-Ion). Width: 54 mm, Depth: 36 mm, Height: 6 mm. Number of batteries included: 1 pc(s)","HP FA889AA, Battery, White, Lithium-Ion (Li-Ion), 1100 mAh, 54 mm, 36 mm",HP FA889AA Battery,,None,None,None,None,None,NaN,None,None,None,None,NaN,2833>150>8194,Computers & Electronics>Computers>Handheld Mobile Computer Spare Parts
1047582,Lenovo,,https://images.icecat.biz/img/brand/thumb/728_2299a3e013664f2d827c919bc743fff0.jpg,Lenovo,https://images.icecat.biz/img/brand/thumb/728_2299a3e013664f2d827c919bc743fff0.jpg,109559U,[],153,EN,PCs/Workstations,,38547582.0,https://pdfs.icecat.biz/pdf/38547582-4292.pdf,"The C30 builds on its award-winning design as the world's smallest dual-CPU workstation, supporting two of the latest-generation Intel® Xeon® processors and faster memory performance, and comes with the Windows® 7 Professional OS. The ISV-certified ThinkStation C30 workstations are engineered from the ground up for the Financial Services sector, Computer-Aided Design (CAD) and Digital Content Creation (DCC) centers.<br>\n<br>\nThe C30 comes preloaded with Windows® 7 Professional and supports up to two Intel® Xeon® E5 2600 series processors, with Turbo Boost Technologyy, up to 128GB of Error Correcting Code (ECC) memory @ 1600MHz, and up to an 800W (90%efficient) power supply for high-performance in a compact form factor. Enhanced Experience 3.0<br>\n<br>\nWe've partnered with NVIDIA® to deliver professional-grade workstation graphic solutions, yielding superior application performance and stability.<br>\n<br>\nThe ThinkStation C30 workstation is certified by multiple leading ISVs, ensuring maximum performance and reliability. The certification also includes support from ISVs if software operational issues occur. Additionally, Error Correcting Code (ECC) memory provides greater data accuracy, improves system up-time, and protects against loss of data due to memory error. And the unique thermal design of the ThinkStation workstation is engineered for maximum cool air delivery to key components, reducing the risk of hardware failure.<br>\n<br>\n- Intel® vPro™ with Active Management Technology (AMT) allows IT personnel to access, diagnose, repair, manage, and secure workstations from remote locations, saving time and reducing maintenance costs.<br>\n- Tool-less interior enables quick and easy maintenance and upgrades of key components.<br>\n- User-friendly design features like a recessed power button prevents potential loss due to accidental shutdown.<br>\n- Front-access media ports with illuminated I/O icons allow you to easily connect devices to the right I/O ports, even in dark environments.<br>\n<br>\nBuilt with 50% post-consumer content, along with an 80 PLUS® Gold-certified 90% efficient power supply, the ThinkStation C30 workstation is friendly to the planet and your bottom line. Additionally, the C30 features several environmental certifications.","Intel Xeon E5-2620 (15M Cache, 2.00 GHz, 7.20 GT/s Intel QPI), 4GB ECC DDR3, 300GB SAS HDD, NVIDIA Quadro 2000D (1GB), DVD-RW, Gigabit Ethernet, Windows 7 Professional 64-bit",0.0,,,1261059.0,https://shop.lenovo.com/us/en/workstations/thinkstation/thinkstation-c-series.html,2013-06-24 11:41:08,,[],13902717,1400,C30,1,,"Lenovo ThinkStation C30. Processor frequency: 2 GHz, Processor family: Intel® Xeon® E5 Family, Processor model: E5-2620. Internal memory: 4 GB, Internal memory type: DDR3-SDRAM. Total storage capacity: 300 GB, Storage media: HDD. Optical drive type: DVD-RW. Discrete graphics adapter model: NVIDIA® Quadro® 2000. Operating system installed: Windows 7 Professional, Operating system architecture: 64-bit. Chassis type: Tower. Product type: Workstation. Weight: 18.5 kg. Product colour: Black","Lenovo ThinkStation C30, 2 GHz, Intel® Xeon® E5 Family, 4 GB, 300 GB, DVD-RW, Windows 7 Professional",Lenovo ThinkStation C30 Intel® Xeon® E5 Family E5-2620 4 GB DDR3-SDRAM 300 GB HDD Black Tower Workstation,3 Yr Onsite,None,EN,ThinkStation,None,None,NaN,None,None,None,"[{'VirtualCategoryID': 194, 'UNCATID': '43171896', 'Value': 'Workstations', 'Language': 'EN'}]",NaN,2833>150>153,Computers & Electronics>Computers>PCs/Workstations
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1093316,Fujitsu,,https://images.icecat.biz/img/brand/thumb/15_bcd6550338dd47a4bb4df7d2888c5fd0.jpg,Fujitsu,https://images.icecat.biz/img/brand/thumb/15_bcd6550338dd47a4bb4df7d2888c5fd0.jpg,VFY:P0758PP761CH,[],153,EN,PCs/Workstations,,66803262.0,,"The FUJITSU ESPRIMO P758 Desktop provides high expandability and solid performance for your challenging business applications. The 8th Gen Intel® Core™ processor combined with the DeskView manageability suite support advanced manageability capabilities. Its energy-efficient power supply and the innovative Low Power Active Mode feature help reduce your power bills while ensuring instant communication in your workplace. The optional Intel® Standard Manageability keeps administration costs low. Finally, EraseDisk ensures secure system retirement.","Intel Core i7-8700, 1 x 16 GB DDR4 2666 MHz, PCIe-SSD 512 GB M.2 NVMe, Intel UHD Graphics 630, Windows 10 Pro",0.0,,,0.0,https://www.fujitsu.com/fts/products/computing/pc/desktops/esprimo-p758/index.html,2019-02-20 16:35:23,,[],65447409,376,P758,511,,"Fujitsu ESPRIMO P758. Processor frequency: 3.2 GHz, Processor family: 8th gen Intel® Core™ i7, Processor model: i7-8700. Internal memory: 16 GB, Internal memory type: DDR4-SDRAM, Memory clock speed: 2666 MHz. Total storage capacity: 512 GB, Storage media: SSD. Optical drive type: DVD Super Multi. On-board graphics adapter model: Intel® UHD Graphics 630. Operating system installed: Windows 10 Pro, Operating system architecture: 64-bit. Power supply: 280 W. Chassis type: Midi Tower. Product type: PC","Fujitsu ESPRIMO P758, 3.2 GHz, 8th gen Intel® Core™ i7, 16 GB, 512 GB, DVD Super Multi, Windows 10 Pro","Fujitsu ESPRIMO P758 8th gen Intel® Core™ i7 i7-8700 16 GB DDR4-SDRAM 512 GB SSD Black,Red Midi Tower PC",1 year,None,EN,ESPRIMO,EN,P,NaN,None,None,None,"[{'VirtualCategoryID': 195, 'UNCATID': '43171895', 'Value': 'PCs', 'Language': 'EN'}]",NaN,2833>150>153,Computers & Electronics>Computers>PCs/Workstations
886679,Acer,,https://images.icecat.biz/img/brand/thumb/7_2e1091176d2d450eae2dce7506f1952f.jpg,Acer,https://images.icecat.biz/img/brand/thumb/7_2e1091176d2d450eae2dce7506f1952f.jpg,55.PDS07.001,[],2509,EN,Notebook Spare Parts,,34441876.0,,,Power board,0.0,,,0.0,https://www.acer.co.uk/ac/en/GB/content/home,2014-10-20 23:47:42,,[],13807663,1,55.PDS07.001,1,,"Acer 55.PDS07.001. Type: Power board, Brand compatibility: Acer","Acer 55.PDS07.001, Power board, Acer",Acer 55.PDS07.001 notebook spare part Power board,,None,None,None,None,None,NaN,None,None,None,None,NaN,2833>150>8355>2509,Computers & Electronics>Computers>Notebook Parts & Accessories>Notebook Spare Parts
35003,Gigabyte,,https://images.icecat.biz/img/brand/thumb/739_1e31c6b4fe83450ba7dc857f60d1a494.jpg,Gigabyte,https://images.icecat.biz/img/brand/thumb/739_1e31c6b4fe83450ba7dc857f60d1a494.jpg,28711-ARM01-0CBS,[],195,EN,Mice,,33939877.0,,<b>Mini Size</b><br>\nUltimate Choice for Notebook<br>\n<br>\n<b>Super Durable Cord</b><br>\nReliable retractable cord with 2-Year warranty<br>\n<br>\n<b>Reduce Cable Clutter</b><br>\nEliminate tangled cord mess<br>\n<br>\n<b>No Battery Needed!</b><br>\nGo green and no worries regarding low battery anymore<br>\n<br>\n<b>Compact Design</b><br>\nStylish shape & comfortable grip,"Optical, USB, 1000dpi, 61g, Black",0.0,,,0.0,https://www.gigabyte.com/products/product-page.aspx?pid=4029#kf,2012-03-11 00:59:03,,[],12795204,1,Aire M1,1,,"Gigabyte Aire M1. Movement detection technology: Optical, Device interface: USB, Movement resolution: 1000 DPI, Buttons quantity: 2, Scroll type: Wheel. Power source: Cable. Product colour: Black","Gigabyte Aire M1, Optical, USB, 1000 DPI, Black",Gigabyte Aire M1 mouse USB Optical 1000 DPI,2 year,None,None,None,None,None,NaN,None,None,None,None,NaN,2833>191>195,Computers & Electronics>Data Input Devices>Mice
779133,HP,,https://images.icecat.biz/img/brand/thumb/1_91e0e5b25690437cb026012c624a00ad.jpg,HP,https://images.icecat.biz/img/brand/thumb/1_91e0e5b25690437cb026012c624a00ad.jpg,7GN16EA,[],151,EN,Notebooks,None,NaN,None,None,None,NaN,None,None,NaN,None,None,,[0193905768042],71610404,64360,14-dh0062no,5739,17-07-2019,"HP Pavilion x360 14-dh0062no. Product type: Hybrid (2-in-1), Form factor: Convertible (Folder). Processor family: 8th gen Intel® Core™ i5, Processor model: i5-8265U, Processor frequency: 1.6 GHz. Display diagonal: 35.6 cm (14""), Display resolution: 1920 x 1080 pixels, Touchscreen. Internal memory: 8 GB, Internal memory type: DDR4-SDRAM. Total storage capacity: 256 GB, Storage media: SSD. On-board graphics adapter. Operating system installed: Windows 10 Home. Product colour: Gold","HP Pavilion x360 14-dh0062no, 8th gen Intel® Core™ i5, 1.6 GHz, 35.6 cm (14""), 1920 x 1080 pixels, 8 GB, 256 GB","HP Pavilion x360 14-dh0062no Gold Hybrid (2-in-1) 35.6 cm (14"") 1920 x 1080 pixels Touchscreen 8th gen Intel® Core™ i5 i5-8265U 8 GB DDR4-SDRAM 256 GB SSD",None,[],EN,Pavilion x360,EN,14,NaN,None,None,None,"[{'VirtualCategoryID': 329, 'UNCATID': '43211598', 'Value': 'Hybrids (2-in-1)', 'Language': 'EN'}]",NaN,2833>150>151,Computers & Electronics>Computers>Notebooks

In [24]:
pd.set_option("max_colwidth", None)

In [25]:
df_cleaned["metadata_text"].head(10)

1072689    ASUS K31CD-IT049T PC 6th gen Intel® Core™ i7 i7-6700 16 GB DDR4-SDRAM 1000 GB HDD Black Tower | ASUS | K31CD-IT049T | PCs/Workstations | ASUS K31CD-IT049T. Processor frequency: 3.4 GHz, Processor family: 6th gen Intel® Core™ i7, Processor model: i7-6700. Internal memory: 16 GB, Internal memory type: DDR4-SDRAM. Total storage capacity: 1000 GB, Storage media: HDD, Card reader integrated. Optical drive type: DVD-RW. On-board graphics adapter model: Intel® HD Graphics 530, Discrete graphics adapter model: NVIDIA® GeForce® GTX 950. Operating system installed: Windows 10 Home. Chassis type: Tower. Product type: PC. Product colour: Black | Intel Core i7-6700 (8M Cache, 3.4GHz), 16GB RAM, 1000GB HDD, Intel HD Graphics 530, Ethernet, Windows 10 | <b>Smart Multimedia Performance</b><br>\nVivoPC K31CD is powered by the 6th generation Intel® processors to give you significantly faster and more efficient multitasking performance over previous iterations. VivoPC K31CD enhances your daily computing experience, making online shopping, writing blogs, conducting presentations, or watching movies all the more enjoyable. <br>\n<br>\n<b>Ultra-Realistic 4K/UHD Visuals</b><br>\nVivoPC K31CD is with discrete NVIDIA or AMD graphics to bring home entertainment to the next level. It supports 4K/UHD (3840 x2160) displays so you can enjoy the latest movies, browse the web, or view photos in all their glory.<br>\n<br>\n<b>Expansive Audio, tuned by experts</b><br>\nA mixture of hardware, software, and tuning, ASUS SonicMaster was developed with the clear goal of giving you the best PC audio. A professional codec ensures precise sound performance; while an optimized amplifier, larger speakers and resonance chambers deliver powerful audio output and deeper bass. Additional signal processing helps fine tune the hardware, filtering noise and improving clarity so you can enjoy unrivalled audio on K31CD.<br>\n<br>\n<b>Windows 10 Home</b><br>\nWindows 10 Home brings the desktop back to the forefront, complete with the familiar convenience of the Start Menu. It also adds an Edge browser that lets you access the web with blistering speed and useful new functions. <br>\n<br>\n<b>SuperSpeed USB 3.1 transmission</b><br>\nVivoPC K31CD features SuperSpeed USB 3.1 transfering data up to 20 times faster than USB 2.0, and 2 times faster than USB 3.0. Besides, it also comes with all the connectivity options you need. HDMI output ports lets you hook your VivoPC K31CD up to an HDTV to supersize your entertainment. SATA 6Gbit/s ports offer blisteringly fast data transfer speeds, letting you save large files or quickly load games. <br>\n<br>\n<b>Ultra-fast connectivity</b><br>\nWith wireless transfer rates up to 433Mbit/s with compatible routers, 802.11ac Wi-Fi is around 8 times faster than 802.11g and around 3 times faster than 802.11n, making the VivoPC K31CD Series capable of streaming 4K/UHD video without the inconvenience of network cables.<br>\n<br>\n<b>ASUS desktops – Most recommended<br>\nWindows desktop brand</b><br>\nInnovation, design and reliability are at the heart of all ASUS computers. ASUS has won a PCMag.com Readers' Choice Award for its desktops four years running, leading the competition in both overall satisfaction and likelihood to be recommended. This proves that ASUS is better at delivering what customers want than rival Windows desktop PC companies. ASUS also had the lowest percentage of units needing repairs within the last 12 months, further proof of its trusted quality and reliability.<br>\n<br>\n<b>Trust worthy quality and reliability</b><br>\nASUS desktop PCs are subjected to a series of rigorous noise, vibration, drop, and thermal shock tests to ensure they meet our exacting standards and exceed those used by other manufacturers. So you can rest assured that your new computer can cope with extremes of dry, icy -40℃ to hot and humid 60℃ environments, as well as the bumps and knocks during shipping.
411281                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      C2G 1m ST/SC Plenum-Rated 9/125 Duplex Single-Mode Fiber Patch Cable - Blue fiber optic cable 39.4" (1 m) | C2G | 1m ST/SC Plenum-Rated 9/125 Duplex Single-Mode Fiber Patch Cable - Blue | Fibre Optic Cables | C2G 1m ST/SC Plenum-Rated 9/125 Duplex Single-Mode Fiber Patch Cable - Blue. Cable length: 1 m, Connector 1: ST, Connector 2: SC, Connector gender: Male connector / Male connector, Cable colour: Blue | 1m ST/SC Plenum-Rated 9/125 Duplex Single-Mode Fiber Patch Cable - Blue | Get the performance you demand at a price that makes sense with Plenum-Rated 9/125 Singlemode Fiber Patch Cords from Cables To Go. They provide high bandwidth and transmission rates and support longer distances, but are still cost effective. They also provide the fire protection required to run these cables within walls and air plenums without the need for conduit. Perfect for use with today’s high speed networks while providing headroom for tomorrow’s higher bandwidth requirements.<br>\r\n<br>\r\nThese multicolored fiber optic patch cables enable you to quickly identify various applications present in your fiber distribution system. The connectors on each end are color-coded for easy identification in a congested patch field.<br>\r\n<br>\r\n<b>Features:</b><br>\r\n<br>\r\n    - A cost effective solution that provides higher bandwidth and support for longer distances<br>\r\n    - Perfect for use in Gigabit Ethernet applications<br>\r\n    - Headroom for tomorrow’s higher bandwidth needs<br>\r\n    - CMP rated cable jacket provides the fire protection required to run these cables within walls and air plenums without the need for conduit<br>\r\n    - Color-coded connector keys available in red, blue, green and black<br>\r\n    - Connectors: (2) ST to (2) SC<br>\r\n    - Buffer OD: 900 µm<br>\r\n    - Jacket OD: 3.0 mm<br>\r\n    - Jacket color: Blue<br>\r\n    - Attenuation @1310 nm: 1.0 dB/km<br>\r\n    - Attenuation @1550 nm: 0.75 dB/km<br>\r\n    - Maximum tensile load: 100 N/cm<br>\r\n    - Loaded min. bend radius: 5 cm<br>\r\n    - Unloaded min. bend radius: 3 cm<br>\r\n    - Crush resistance: 750 N/cm<br>\r\n    - Impact resistance: 1000 cycles<br>\r\n    - Flex resistance: 5000 cycles
425903                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     HP FA889AA Battery | HP | FA889AA | Handheld Mobile Computer Spare Parts | HP FA889AA. Product type: Battery, Product colour: White, Battery technology: Lithium-Ion (Li-Ion). Width: 54 mm, Depth: 36 mm, Height: 6 mm. Number of batteries included: 1 pc(s) | 1100 mAh, Lithium Ion, Standard Battery | Keeping an extra source of power nearby means your iPAQ Voice Messenger can run for longer periods away from your home or office.
1047582                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Lenovo ThinkStation C30 Intel® Xeon® E5 Family E5-2620 4 GB DDR3-SDRAM 300 GB HDD Black Tower Workstation | Lenovo | C30 | PCs/Workstations | Lenovo ThinkStation C30. Processor frequency: 2 GHz, Processor family: Intel® Xeon® E5 Family, Processor model: E5-2620. Internal memory: 4 GB, Internal memory type: DDR3-SDRAM. Total storage capacity: 300 GB, Storage media: HDD. Optical drive type: DVD-RW. Discrete graphics adapter model: NVIDIA® Quadro® 2000. Operating system installed: Windows 7 Professional, Operating system architecture: 64-bit. Chassis type: Tower. Product type: Workstation. Weight: 18.5 kg. Product colour: Black | Intel Xeon E5-2620 (15M Cache, 2.00 GHz, 7.20 GT/s Intel QPI), 4GB ECC DDR3, 300GB SAS HDD, NVIDIA Quadro 2000D (1GB), DVD-RW, Gigabit Ethernet, Windows 7 Professional 64-bit | The C30 builds on its award-winning design as the world's smallest dual-CPU workstation, supporting two of the latest-generation Intel® Xeon® processors and faster memory performance, and comes with the Windows® 7 Professional OS. The ISV-certified ThinkStation C30 workstations are engineered from the ground up for the Financial Services sector, Computer-Aided Design (CAD) and Digital Content Creation (DCC) centers.<br>\n<br>\nThe C30 comes preloaded with Windows® 7 Professional and supports up to two Intel® Xeon® E5 2600 series processors, with Turbo Boost Technologyy, up to 128GB of Error Correcting Code (ECC) memory @ 1600MHz, and up to an 800W (90%efficient) power supply for high-performance in a compact form factor. Enhanced Experience 3.0<br>\n<br>\nWe've partnered with NVIDIA® to deliver professional-grade workstation graphic solutions, yielding superior application performance and stability.<br>\n<br>\nThe ThinkStation C30 workstation is certified by multiple leading ISVs, ensuring maximum performance and reliability. The certification also includes support from ISVs if software operational issues occur. Additionally, Error Correcting Code (ECC) memory provides greater data accuracy, improves system up-time, and protects against loss of data due to memory error. And the unique thermal design of the ThinkStation workstation is engineered for maximum cool air delivery to key components, reducing the risk of hardware failure.<br>\n<br>\n- Intel® vPro™ with Active Management Technology (AMT) allows IT personnel to access, diagnose, repair, manage, and secure workstations from remote locations, saving time and reducing maintenance costs.<br>\n- Tool-less interior enables quick and easy maintenance and upgrades of key components.<br>\n- User-friendly design features like a recessed power button prevents potential loss due to accidental shutdown.<br>\n- Front-access media ports with illuminated I/O icons allow you to easily connect devices to the right I/O ports, even in dark environments.<br>\n<br>\nBuilt with 50% post-consumer content, along with an 80 PLUS® Gold-certified 90% efficient power supply, the ThinkStation C30 workstation is friendly to the planet and your bottom line. Additionally, the C30 features several environmental certifications.
157385                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     Lenovo 00D8199 software license/upgrade | Lenovo | 00D8199 | Software Licenses/Upgrades | Lenovo 00D8199. License term in years: 3 year(s) | SLES for SAP Applications 2 Socket 24x7 SUSE Support 3 Years | SUSE Linux Enterprise Server (SLES)<br>\n<br>\nThis server OS supports thousands of applications in virtual and cloud environments as well as industry-standard hardware.<br>\n<br>\nDesigned to deliver essential data center services with commodity off-the-shelf IT resources, SUSE Linux Enterprise Server is a versatile Linux platform that pleases both business users and IT managers. This Linux server OS supports thousands of third-party ISV applications and enables them to run in physical, virtual, and cloud environments.<br>\n<br>\nSUSE Linux Enterprise Server also interoperates with two other operating systems often used in today's data centers: Windows and UNIX . Optional extensions deliver advanced functionality. As a result, you can integrate SUSE Linux Enterprise Server seamlessly into mixed IT infrastructures, continue to run your existing applications, and add new capabilities as your business needs change.<br>\n<br>\nMore than 13,000 businesses worldwide use SUSE Linux Enterprise Server because SLES supports more than 8,500 third-party ISVs. The list of supported software keeps growing. Certified and supported software for SUSE Linux Enterprise Server includes everything from mission-critical databases, e-commerce applications and ERP systems, to email, file, and print servers and web servers. Today, over 70% of all SAP applications for Linux run on SUSE Linux Enterprise Server.

In [27]:
df_cleaned["Description.LongDesc"]

1072689    <b>Smart Multimedia Performance</b><br>\nVivoPC K31CD is powered by the 6th generation Intel® processors to give you significantly faster and more efficient multitasking performance over previous iterations. VivoPC K31CD enhances your daily computing experience, making online shopping, writing blogs, conducting presentations, or watching movies all the more enjoyable. <br>\n<br>\n<b>Ultra-Realistic 4K/UHD Visuals</b><br>\nVivoPC K31CD is with discrete NVIDIA or AMD graphics to bring home entertainment to the next level. It supports 4K/UHD (3840 x2160) displays so you can enjoy the latest movies, browse the web, or view photos in all their glory.<br>\n<br>\n<b>Expansive Audio, tuned by experts</b><br>\nA mixture of hardware, software, and tuning, ASUS SonicMaster was developed with the clear goal of giving you the best PC audio. A professional codec ensures precise sound performance; while an optimized amplifier, larger speakers and resonance chambers deliver powerful audio output and deeper bass. Additional signal processing helps fine tune the hardware, filtering noise and improving clarity so you can enjoy unrivalled audio on K31CD.<br>\n<br>\n<b>Windows 10 Home</b><br>\nWindows 10 Home brings the desktop back to the forefront, complete with the familiar convenience of the Start Menu. It also adds an Edge browser that lets you access the web with blistering speed and useful new functions. <br>\n<br>\n<b>SuperSpeed USB 3.1 transmission</b><br>\nVivoPC K31CD features SuperSpeed USB 3.1 transfering data up to 20 times faster than USB 2.0, and 2 times faster than USB 3.0. Besides, it also comes with all the connectivity options you need. HDMI output ports lets you hook your VivoPC K31CD up to an HDTV to supersize your entertainment. SATA 6Gbit/s ports offer blisteringly fast data transfer speeds, letting you save large files or quickly load games. <br>\n<br>\n<b>Ultra-fast connectivity</b><br>\nWith wireless transfer rates up to 433Mbit/s with compatible routers, 802.11ac Wi-Fi is around 8 times faster than 802.11g and around 3 times faster than 802.11n, making the VivoPC K31CD Series capable of streaming 4K/UHD video without the inconvenience of network cables.<br>\n<br>\n<b>ASUS desktops – Most recommended<br>\nWindows desktop brand</b><br>\nInnovation, design and reliability are at the heart of all ASUS computers. ASUS has won a PCMag.com Readers' Choice Award for its desktops four years running, leading the competition in both overall satisfaction and likelihood to be recommended. This proves that ASUS is better at delivering what customers want than rival Windows desktop PC companies. ASUS also had the lowest percentage of units needing repairs within the last 12 months, further proof of its trusted quality and reliability.<br>\n<br>\n<b>Trust worthy quality and reliability</b><br>\nASUS desktop PCs are subjected to a series of rigorous noise, vibration, drop, and thermal shock tests to ensure they meet our exacting standards and exceed those used by other manufacturers. So you can rest assured that your new computer can cope with extremes of dry, icy -40℃ to hot and humid 60℃ environments, as well as the bumps and knocks during shipping.
411281                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              Get the performance you demand at a price that makes sense with Plenum-Rated 9/125 Singlemode Fiber Patch Cords from Cables To Go. They provide high bandwidth and transmission rates and support longer distances, but are still cost effective. They also provide the fire protection required to run these cables within walls and air plenums without the need for conduit. Perfect for use with today’s high speed networks while providing headroom for tomorrow’s higher bandwidth requirements.<br>\r\n<br>\r\nThese multicolored fiber optic patch cables enable you to quickly identify various applications present in your fiber distribution system. The connectors on each end are color-coded for easy identification in a congested patch field.<br>\r\n<br>\r\n<b>Features:</b><br>\r\n<br>\r\n    - A cost effective solution that provides higher bandwidth and support for longer distances<br>\r\n    - Perfect for use in Gigabit Ethernet applications<br>\r\n    - Headroom for tomorrow’s higher bandwidth needs<br>\r\n    - CMP rated cable jacket provides the fire protection required to run these cables within walls and air plenums without the need for conduit<br>\r\n    - Color-coded connector keys available in red, blue, green and black<br>\r\n    - Connectors: (2) ST to (2) SC<br>\r\n    - Buffer OD: 900 µm<br>\r\n    - Jacket OD: 3.0 mm<br>\r\n    - Jacket color: Blue<br>\r\n    - Attenuation @1310 nm: 1.0 dB/km<br>\r\n    - Attenuation @1550 nm: 0.75 dB/km<br>\r\n    - Maximum tensile load: 100 N/cm<br>\r\n    - Loaded min. bend radius: 5 cm<br>\r\n    - Unloaded min. bend radius: 3 cm<br>\r\n    - Crush resistance: 750 N/cm<br>\r\n    - Impact resistance: 1000 cycles<br>\r\n    - Flex resistance: 5000 cycles
425903                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   Keeping an extra source of power nearby means your iPAQ Voice Messenger can run for longer periods away from your home or office.
1047582                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 The C30 builds on its award-winning design as the world's smallest dual-CPU workstation, supporting two of the latest-generation Intel® Xeon® processors and faster memory performance, and comes with the Windows® 7 Professional OS. The ISV-certified ThinkStation C30 workstations are engineered from the ground up for the Financial Services sector, Computer-Aided Design (CAD) and Digital Content Creation (DCC) centers.<br>\n<br>\nThe C30 comes preloaded with Windows® 7 Professional and supports up to two Intel® Xeon® E5 2600 series processors, with Turbo Boost Technologyy, up to 128GB of Error Correcting Code (ECC) memory @ 1600MHz, and up to an 800W (90%efficient) power supply for high-performance in a compact form factor. Enhanced Experience 3.0<br>\n<br>\nWe've partnered with NVIDIA® to deliver professional-grade workstation graphic solutions, yielding superior application performance and stability.<br>\n<br>\nThe ThinkStation C30 workstation is certified by multiple leading ISVs, ensuring maximum performance and reliability. The certification also includes support from ISVs if software operational issues occur. Additionally, Error Correcting Code (ECC) memory provides greater data accuracy, improves system up-time, and protects against loss of data due to memory error. And the unique thermal design of the ThinkStation workstation is engineered for maximum cool air delivery to key components, reducing the risk of hardware failure.<br>\n<br>\n- Intel® vPro™ with Active Management Technology (AMT) allows IT personnel to access, diagnose, repair, manage, and secure workstations from remote locations, saving time and reducing maintenance costs.<br>\n- Tool-less interior enables quick and easy maintenance and upgrades of key components.<br>\n- User-friendly design features like a recessed power button prevents potential loss due to accidental shutdown.<br>\n- Front-access media ports with illuminated I/O icons allow you to easily connect devices to the right I/O ports, even in dark environments.<br>\n<br>\nBuilt with 50% post-consumer content, along with an 80 PLUS® Gold-certified 90% efficient power supply, the ThinkStation C30 workstation is friendly to the planet and your bottom line. Additionally, the C30 features several environmental certifications.
157385                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    SUSE Linux Enterprise Server (SLES)<br>\n<br>\nThis server OS supports thousands of applications in virtual and cloud environments as well as industry-standard hardware.<br>\n<br>\nDesigned to deliver essential data center services with commodity off-the-shelf IT resources, SUSE Linux Enterprise Server is a versatile Linux platform that pleases both business users and IT managers. This Linux server OS supports thousands of third-party ISV applications and enables them to run in physical, virtual, and cloud environments.<br>\n<br>\nSUSE Linux Enterprise Server also interoperates with two other operating systems often used in today's data centers: Windows and UNIX . Optional extensions deliver advanced functionality. As a result, you can integrate SUSE Linux Enterprise Server seamlessly into mixed IT infrastructures, continue to run your existing applications, and add new capabilities as your business needs change.<br>\n<br>\nMore than 13,000 businesses worldwide use SUSE Linux Enterprise Server because SLES supports more than 8,500 third-party ISVs. The list of supported software keeps growing. Certified and supported software for SUSE Linux Enterprise Server includes everything from mission-critical databases, e-commerce applications and ERP systems, to email, file, and print servers and web servers. Today, over 70% of all SAP applications for Linux run on SUSE Linux Enterprise Server.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ...
421630

In [28]:
# df_cleaned["BulletPoints"].head(59000)

In [29]:
import re

def clean_text(text):
    # Lowercase
    text = text.lower()
    # Remove HTML tags if any
    text = re.sub(r'<[^>]+>', ' ', text)
    # Remove special characters except common ones
    text = re.sub(r'[^a-zA-Z0-9\s\-/.,]', ' ', text)
    # Remove extra whitespace
    text = re.sub(r'\s+', ' ', text).strip()
    return text

df_cleaned['metadata_clean'] = df_cleaned['metadata_text'].apply(clean_text)

In [30]:
df_cleaned.head(3)

        Brand BrandInfo.BrandLocalName  \
1072689  ASUS
411281    C2G
425903     HP

                                                                         BrandInfo.BrandLogo  \
1072689   https://images.icecat.biz/img/brand/thumb/161_352df2a0298f4fc6b9b82e2d4f8aa4fa.jpg
411281   https://images.icecat.biz/img/brand/thumb/2834_0fe501c2c3204f37b195bb21483fcd4a.jpg
425903      https://images.icecat.biz/img/brand/thumb/1_91e0e5b25690437cb026012c624a00ad.jpg

        BrandInfo.BrandName  \
1072689                ASUS
411281                  C2G
425903                   HP

                                                                                   BrandLogo  \
1072689   https://images.icecat.biz/img/brand/thumb/161_352df2a0298f4fc6b9b82e2d4f8aa4fa.jpg
411281   https://images.icecat.biz/img/brand/thumb/2834_0fe501c2c3204f37b195bb21483fcd4a.jpg
425903      https://images.icecat.biz/img/brand/thumb/1_91e0e5b25690437cb026012c624a00ad.jpg

        BrandPartCode  Category.CategoryID Category.Name.Language  \
1072689  K31CD-IT049T                  153                     EN
411281          37745                  953                     EN
425903    FA889AA#AC3                 8194                     EN

                          Category.Name.Value Description.Disclaimer  \
1072689                      PCs/Workstations
411281                     Fibre Optic Cables
425903   Handheld Mobile Computer Spare Parts

         Description.ID Description.LeafletPDFURL  \
1072689      57169981.0
411281       23898946.0
425903        2230345.0

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Description.LongDesc  \
1072689  <b>Smart Multimedia Performance</b><br>\nVivoPC K31CD is powered by the 6th generation Intel® processors to give you significantly faster and more efficient multitasking performance over previous iterations. VivoPC K31CD enhances your daily computing experience, making online shopping, writing blogs, conducting presentations, or watching movies all the more enjoyable. <br>\n<br>\n<b>Ultra-Realistic 4K/UHD Visuals</b><br>\nVivoPC K31CD is with discrete NVIDIA or AMD graphics to bring home entertainment to the next level. It supports 4K/UHD (3840 x2160) displays so you can enjoy the latest movies, browse the web, or view photos in all their glory.<br>\n<br>\n<b>Expansive Audio, tuned by experts</b><br>\nA mixture of hardware, software, and tuning, ASUS SonicMaster was developed with the clear goal of giving you the best PC audio. A professional codec ensures precise sound performance; while an optimized amplifier, larger speakers and resonance chambers deliver powerful audio output and deeper bass. Additional signal processing helps fine tune the hardware, filtering noise and improving clarity so you can enjoy unrivalled audio on K31CD.<br>\n<br>\n<b>Windows 10 Home</b><br>\nWindows 10 Home brings the desktop back to the forefront, complete with the familiar convenience of the Start Menu. It also adds an Edge browser that lets you access the web with blistering speed and useful new functions. <br>\n<br>\n<b>SuperSpeed USB 3.1 transmission</b><br>\nVivoPC K31CD features SuperSpeed USB 3.1 transfering data up to 20 times faster than USB 2.0, and 2 times faster than USB 3.0. Besides, it also comes with all the connectivity options you need. HDMI output ports lets you hook your VivoPC K31CD up to an HDTV to supersize your entertainment. SATA 6Gbit/s ports offer blisteringly fast data transfer speeds, letting you save large files or quickly load games. <br>\n<br>\n<b>Ultra-fast connectivity</b><br>\nWith wireless transfer rates up to 433Mbit/s with compatible routers, 802.11ac Wi-Fi is around 8 times faster than 802.11g and around 3 times faster than 802.11n, making the VivoPC K31CD Series capable of streaming 4K/UHD video without the inconvenience of network cables.<br>\n<br>\n<b>ASUS desktops – Most recommended<br>\nWindows desktop brand</b><br>\nInnovation, design and reliability are at the heart of all ASUS computers. ASUS has won a PCMag.com Readers' Choice Award for its desktops four years running, leading the competition in both overall satisfaction and likelihood to be recommended. This proves that ASUS is better at delivering what customers want than rival Windows desktop PC companies. ASUS also had the lowest percentage of units needing repairs within the last 12 months, further proof of its trusted quality and reliability.<br>\n<br>\n<b>Trust worthy quality and reliability</b><br>\nASUS desktop PCs are subjected to a series of rigorous noise, vibration, drop, and thermal shock tests to ensure they meet our exacting standards and exceed those used by other manufacturers. So you can rest assured that your new computer can cope with extremes of dry, icy -40℃ to hot and humid 60℃ environments, as well as the bumps and knocks during shipping.
411281                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Get the performance you demand at a price that makes sense with Plenum-Rated 9/125 Singlemode Fiber Patch Cords from Cables To Go. They provide high bandwidth and transmission rates and support longer distances, but are still cost effective. They also provide the fire protection required to run these cables within walls and air plenums without the need for conduit. Perfect for use with today’s high speed networks while providing headroom for tomorrow’s higher bandwidth requirements.<br>\r\n<br>\r\nThese multicolored fiber optic patch cables enable you to quickly identify various applications present in your fiber distribution system. The connectors on each end are color-coded for easy identification in a congested patch field.<br>\r\n<br>\r\n<b>Features:</b><br>\r\n<br>\r\n    - A cost effective solution that provides higher bandwidth and support for longer distances<br>\r\n    - Perfect for use in Gigabit Ethernet applications<br>\r\n    - Headroom for tomorrow’s higher bandwidth needs<br>\r\n    - CMP rated cable jacket provides the fire protection required to run these cables within walls and air plenums without the need for conduit<br>\r\n    - Color-coded connector keys available in red, blue, green and black<br>\r\n    - Connectors: (2) ST to (2) SC<br>\r\n    - Buffer OD: 900 µm<br>\r\n    - Jacket OD: 3.0 mm<br>\r\n    - Jacket color: Blue<br>\r\n    - Attenuation @1310 nm: 1.0 dB/km<br>\r\n    - Attenuation @1550 nm: 0.75 dB/km<br>\r\n    - Maximum tensile load: 100 N/cm<br>\r\n    - Loaded min. bend radius: 5 cm<br>\r\n    - Unloaded min. bend radius: 3 cm<br>\r\n    - Crush resistance: 750 N/cm<br>\r\n    - Impact resistance: 1000 cycles<br>\r\n    - Flex resistance: 5000 cycles
425903                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 Keeping an extra source of power nearby means your iPAQ Voice Messenger can run for longer periods away from your home or office.

                                                                                      Description.LongProductName  \
1072689  Intel Core i7-6700 (8M Cache, 3.4GHz), 16GB RAM, 1000GB HDD, Intel HD Graphics 530, Ethernet, Windows 10
411281                                    1m ST/SC Plenum-Rated 9/125 Duplex Single-Mode Fiber Patch Cable - Blue
425903                                                                    1100 mAh, Lithium Ion, Standard Battery

         Description.ManualPDFSize Description.ManualPDFURL  \
1072689                        0.0
411281                         0.0
425903                         0.0

        Description.MiddleDesc  Description.PDFSize  \
1072689                                         0.0
411281                                          0.0
425903                                          0.0

                                                                 Description.URL  \
1072689                             https://www.asus.com/Tower-PCs/VivoPC-K31CD/
411281     https://www.cablestogo.com/product.asp?cat_id=2333&sku=37745&st=37745
425903   https://h18004.www1.hp.com/products/quickspecs/12657_div/12657_div.html

         Description.Updated EndOfLifeDate             GTIN  IcecatId  \
1072689  2017-06-20 09:29:04                [4712900548402]  35540060
411281   2009-06-26 14:00:19                             []   3090266
425903   2013-03-11 10:31:57                             []    861193

         ProductFamily.ProductFamilyID  \
1072689                              0
411281                               1
425903                               1

                                                                     ProductName  \
1072689                                                             K31CD-IT049T
411281   1m ST/SC Plenum-Rated 9/125 Duplex Single-Mode Fiber Patch Cable - Blue
425903                                                                   FA889AA

         ProductSeries.SeriesID ReleaseDate  \
1072689                       1
411281                        1
425903                        1

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      SummaryDescription.LongSummaryDescription  \
1072689  ASUS K31CD-IT049T. Processor frequency: 3.4 GHz, Processor family: 6th gen Intel® Core™ i7, Processor model: i7-6700. Internal memory: 16 GB, Internal memory type: DDR4-SDRAM. Total storage capacity: 1000 GB, Storage media: HDD, Card reader integrated. Optical drive type: DVD-RW. On-board graphics adapter model: Intel® HD Graphics 530, Discrete graphics adapter model: NVIDIA® GeForce® GTX 950. Operating system installed: Windows 10 Home. Chassis type: Tower. Product type: PC. Product colour: Black
411281                                                                                                                                                                                                                                                                                                                  C2G 1m ST/SC Plenum-Rated 9/125 Duplex Single-Mode Fiber Patch Cable - Blue. Cable length: 1 m, Connector 1: ST, Connector 2: SC, Connector gender: Male connector / Male connector, Cable colour: Blue
425903                                                                                                                                                                                                                                                                                                                                      HP FA889AA. Product type: Battery, Product colour: White, Battery technology: Lithium-Ion (Li-Ion). Width: 54 mm, Depth: 36 mm, Height: 6 mm. Number of batteries included: 1 pc(s)

                                                                                              SummaryDescription.ShortSummaryDescription  \
1072689                                     ASUS K31CD-IT049T, 3.4 GHz, 6th gen Intel® Core™ i7, 16 GB, 1000 GB, DVD-RW, Windows 10 Home
411281   C2G 1m ST/SC Plenum-Rated 9/125 Duplex Single-Mode Fiber Patch Cable - Blue, 1 m, ST, SC, Male connector / Male connector, Blue
425903                                                          HP FA889AA, Battery, White, Lithium-Ion (Li-Ion), 1100 mAh, 54 mm, 36 mm

                                                                                                             Title  \
1072689              ASUS K31CD-IT049T PC 6th gen Intel® Core™ i7 i7-6700 16 GB DDR4-SDRAM 1000 GB HDD Black Tower
411281   C2G 1m ST/SC Plenum-Rated 9/125 Duplex Single-Mode Fiber Patch Cable - Blue fiber optic cable 39.4" (1 m)
425903                                                                                          HP FA889AA Battery

                                               Description.WarrantyInfo  \
1072689                                                            None
411281   Lifetime warranty against defects of materials and workmanship
425903

        ProductFamily.Language ProductFamily.Value ProductSeries.Language  \
1072689                   None                None                   None

In [31]:
df_cleaned.columns

Index(['Brand', 'BrandInfo.BrandLocalName', 'BrandInfo.BrandLogo',
       'BrandInfo.BrandName', 'BrandLogo', 'BrandPartCode',
       'Category.CategoryID', 'Category.Name.Language', 'Category.Name.Value',
       'Description.Disclaimer', 'Description.ID', 'Description.LeafletPDFURL',
       'Description.LongDesc', 'Description.LongProductName',
       'Description.ManualPDFSize', 'Description.ManualPDFURL',
       'Description.MiddleDesc', 'Description.PDFSize', 'Description.URL',
       'Description.Updated', 'EndOfLifeDate', 'GTIN', 'IcecatId',
       'ProductFamily.ProductFamilyID', 'ProductName',
       'ProductSeries.SeriesID', 'ReleaseDate',
       'SummaryDescription.LongSummaryDescription',
       'SummaryDescription.ShortSummaryDescription', 'Title',
       'Description.WarrantyInfo', 'ProductFamily.Language',
       'ProductFamily.Value', 'ProductSeries.Language', 'ProductSeries.Value',
       'BulletPoints.BulletPointsId', 'BulletPoints.Language',
       'BulletPoints.Updated', 'BulletPoints.Values', 'pathlist_names',
       'metadata_text', 'metadata_clean'],
      dtype='object')

In [33]:
# # Save to CSV file
df_cleaned.to_csv("Cleaned_Data_1.csv", index=False)

print("CSV file saved successfully as 'Cleaned_Data_1.csv'")

CSV file saved successfully as 'Cleaned_Data_1.csv'

In [34]:
data = pd.read_csv("/Users/suyashmali/Case_Study_Materials/LLM/Cleaned_Data_1.csv")

/var/folders/b_/cv34fjz13m34nzs9_x_gpp600000gn/T/ipykernel_74218/1773616221.py:1: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv("/Users/suyashmali/Case_Study_Materials/LLM/Cleaned_Data_1.csv")

In [35]:
data.head(5)

    Brand BrandInfo.BrandLocalName  \
0    ASUS                      NaN
1     C2G                      NaN
2      HP                      NaN
3  Lenovo                      NaN
4  Lenovo                      NaN

                                                                   BrandInfo.BrandLogo  \
0   https://images.icecat.biz/img/brand/thumb/161_352df2a0298f4fc6b9b82e2d4f8aa4fa.jpg
1  https://images.icecat.biz/img/brand/thumb/2834_0fe501c2c3204f37b195bb21483fcd4a.jpg
2     https://images.icecat.biz/img/brand/thumb/1_91e0e5b25690437cb026012c624a00ad.jpg
3   https://images.icecat.biz/img/brand/thumb/728_2299a3e013664f2d827c919bc743fff0.jpg
4   https://images.icecat.biz/img/brand/thumb/728_2299a3e013664f2d827c919bc743fff0.jpg

  BrandInfo.BrandName  \
0                ASUS
1                 C2G
2                  HP
3              Lenovo
4              Lenovo

                                                                             BrandLogo  \
0   https://images.icecat.biz/img/brand/thumb/161_352df2a0298f4fc6b9b82e2d4f8aa4fa.jpg
1  https://images.icecat.biz/img/brand/thumb/2834_0fe501c2c3204f37b195bb21483fcd4a.jpg
2     https://images.icecat.biz/img/brand/thumb/1_91e0e5b25690437cb026012c624a00ad.jpg
3   https://images.icecat.biz/img/brand/thumb/728_2299a3e013664f2d827c919bc743fff0.jpg
4   https://images.icecat.biz/img/brand/thumb/728_2299a3e013664f2d827c919bc743fff0.jpg

  BrandPartCode  Category.CategoryID Category.Name.Language  \
0  K31CD-IT049T                  153                     EN
1         37745                  953                     EN
2   FA889AA#AC3                 8194                     EN
3       109559U                  153                     EN
4       00D8199                  803                     EN

                    Category.Name.Value Description.Disclaimer  \
0                      PCs/Workstations                    NaN
1                    Fibre Optic Cables                    NaN
2  Handheld Mobile Computer Spare Parts                    NaN
3                      PCs/Workstations                    NaN
4            Software Licenses/Upgrades                    NaN

   Description.ID                      Description.LeafletPDFURL  \
0      57169981.0                                            NaN
1      23898946.0                                            NaN
2       2230345.0                                            NaN
3      38547582.0  https://pdfs.icecat.biz/pdf/38547582-4292.pdf
4      44877091.0                                            NaN

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              Description.LongDesc  \
0  <b>Smart Multimedia Performance</b><br>\nVivoPC K31CD is powered by the 6th generation Intel® processors to give you significantly faster and more efficient multitasking performance over previous iterations. VivoPC K31CD enhances your daily computing experience, making online shopping, writing blogs, conducting presentations, or watching movies all the more enjoyable. <br>\n<br>\n<b>Ultra-Realistic 4K/UHD Visuals</b><br>\nVivoPC K31CD is with discrete NVIDIA or AMD graphics to bring home entertainment to the next level. It supports 4K/UHD (3840 x2160) displays so you can enjoy the latest movies, browse the web, or view photos in all their glory.<br>\n<br>\n<b>Expansive Audio, tuned by experts</b><br>\nA mixture of hardware, software, and tuning, ASUS SonicMaster was developed with the clear goal of giving you the best PC audio. A professional codec ensures precise sound performance; while an optimized amplifier, larger speakers and resonance chambers deliver powerful audio output and deeper bass. Additional signal processing helps fine tune the hardware, filtering noise and improving clarity so you can enjoy unrivalled audio on K31CD.<br>\n<br>\n<b>Windows 10 Home</b><br>\nWindows 10 Home brings the desktop back to the forefront, complete with the familiar convenience of the Start Menu. It also adds an Edge browser that lets you access the web with blistering speed and useful new functions. <br>\n<br>\n<b>SuperSpeed USB 3.1 transmission</b><br>\nVivoPC K31CD features SuperSpeed USB 3.1 transfering data up to 20 times faster than USB 2.0, and 2 times faster than USB 3.0. Besides, it also comes with all the connectivity options you need. HDMI output ports lets you hook your VivoPC K31CD up to an HDTV to supersize your entertainment. SATA 6Gbit/s ports offer blisteringly fast data transfer speeds, letting you save large files or quickly load games. <br>\n<br>\n<b>Ultra-fast connectivity</b><br>\nWith wireless transfer rates up to 433Mbit/s with compatible routers, 802.11ac Wi-Fi is around 8 times faster than 802.11g and around 3 times faster than 802.11n, making the VivoPC K31CD Series capable of streaming 4K/UHD video without the inconvenience of network cables.<br>\n<br>\n<b>ASUS desktops – Most recommended<br>\nWindows desktop brand</b><br>\nInnovation, design and reliability are at the heart of all ASUS computers. ASUS has won a PCMag.com Readers' Choice Award for its desktops four years running, leading the competition in both overall satisfaction and likelihood to be recommended. This proves that ASUS is better at delivering what customers want than rival Windows desktop PC companies. ASUS also had the lowest percentage of units needing repairs within the last 12 months, further proof of its trusted quality and reliability.<br>\n<br>\n<b>Trust worthy quality and reliability</b><br>\nASUS desktop PCs are subjected to a series of rigorous noise, vibration, drop, and thermal shock tests to ensure they meet our exacting standards and exceed those used by other manufacturers. So you can rest assured that your new computer can cope with extremes of dry, icy -40℃ to hot and humid 60℃ environments, as well as the bumps and knocks during shipping.
1                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           Get the performance you demand at a price that makes sense with Plenum-Rated 9/125 Singlemode Fiber Patch Cords from Cables To Go. They provide high bandwidth and transmission rates and support longer distances, but are still cost effective. They also provide the fire protection required to run these cables within walls and air plenums without the need for conduit. Perfect for use with today’s high speed networks while providing headroom for tomorrow’s higher bandwidth requirements.<br>\r\n<br>\r\nThese multicolored fiber optic patch cables enable you to quickly identify various applications present in your fiber distribution system. The connectors on each end are color-coded for easy identification in a congested patch field.<br>\r\n<br>\r\n<b>Features:</b><br>\r\n<br>\r\n    - A cost effective solution that provides higher bandwidth and support for longer distances<br>\r\n    - Perfect for use in Gigabit Ethernet applications<br>\r\n    - Headroom for tomorrow’s higher bandwidth needs<br>\r\n    - CMP rated cable jacket provides the fire protection required to run these cables within walls and air plenums without the need for conduit<br>\r\n    - Color-coded connector keys available in red, blue, green and black<br>\r\n    - Connectors: (2) ST to (2) SC<br>\r\n    - Buffer OD: 900 µm<br>\r\n    - Jacket OD: 3.0 mm<br>\r\n    - Jacket color: Blue<br>\r\n    - Attenuation @1310 nm: 1.0 dB/km<br>\r\n    - Attenuation @1550 nm: 0.75 dB/km<br>\r\n    - Maximum tensile load: 100 N/cm<br>\r\n    - Loaded min. bend radius: 5 cm<br>\r\n    - Unloaded min. bend radius: 3 cm<br>\r\n    - Crush resistance: 750 N/cm<br>\r\n    - Impact resistance: 1000 cycles<br>\r\n    - Flex resistance: 5000 cycles
2                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Keeping an extra source of power nearby means your iPAQ Voice Messenger can run for longer periods away from your home or office.
3                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               The C30 builds on its award-winning design as the world's smallest dual-CPU workstation, supporting two of the latest-generation Intel® Xeon® processors and faster memory performance, and comes with the Windows® 7 Professional OS. The ISV-certified ThinkStation C30 workstations are engineered from the ground up for the Financial Services sector, Computer-Aided Design (CAD) and Digital Content Creation (DCC) centers.<br>\n<br>\nThe C30 comes preloaded with Windows® 7 Professional and supports up to two Intel® Xeon® E5 2600 series processors, with Turbo Boost Technologyy, up to 128GB of Error Correcting Code (ECC) memory @ 1600MHz, and up to an 800W (90%efficient) power supply for high-performance in a compact form factor. Enhanced Experience 3.0<br>\n<br>\nWe've partnered with NVIDIA® to deliver professional-grade workstation graphic solutions, yielding superior application performance and stability.<br>\n<br>\nThe ThinkStation C30 workstation is certified by multiple leading ISVs, ensuring maximum performance and reliability. The certification also includes support from ISVs if software operational issues occur. Additionally, Error Correcting Code (ECC) memory provides greater data accuracy, improves system up-time, and protects against loss of data due to memory error. And the unique thermal design of the ThinkStation workstation is engineered for maximum cool air delivery to key components, reducing the risk of hardware failure.<br>\n<br>\n- Intel® vPro™ with Active Management Technology (AMT) allows IT personnel to access, diagnose, repair, manage, and secure workstations from remote locations, saving time and reducing maintenance costs.<br>\n- Tool-less interior enables quick and easy maintenance and upgrades of key components.<br>\n- User-friendly design features like a recessed power button prevents potential loss due to accidental shutdown.<br>\n- Front-access media ports with illuminated I/O icons allow you to easily connect devices to the right I/O ports, even in dark environments.<br>\n<br>\nBuilt with 50% post-consumer content, along with an 80 PLUS® Gold-certified 90% efficient power supply, the ThinkStation C30 workstation is friendly to the planet and your bottom line. Additionally, the C30 features several environmental certifications.

## Checking:

In [40]:
data = pd.read_csv("/Users/suyashmali/Case_Study_Materials/LLM/Cleaned_Data_1.csv")

/var/folders/b_/cv34fjz13m34nzs9_x_gpp600000gn/T/ipykernel_21629/1773616221.py:1: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv("/Users/suyashmali/Case_Study_Materials/LLM/Cleaned_Data_1.csv")

In [41]:
data[data["ProductName"] == "K31CD-IT049T"][["Brand", "metadata_text", "metadata_clean", "Category.Name.Value"]]

  Brand  \
0  ASUS

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  metadata_text  \
0  ASUS K31CD-IT049T PC 6th gen Intel® Core™ i7 i7-6700 16 GB DDR4-SDRAM 1000 GB HDD Black Tower | ASUS | K31CD-IT049T | PCs/Workstations | ASUS K31CD-IT049T. Processor frequency: 3.4 GHz, Processor family: 6th gen Intel® Core™ i7, Processor model: i7-6700. Internal memory: 16 GB, Internal memory type: DDR4-SDRAM. Total storage capacity: 1000 GB, Storage media: HDD, Card reader integrated. Optical drive type: DVD-RW. On-board graphics adapter model: Intel® HD Graphics 530, Discrete graphics adapter model: NVIDIA® GeForce® GTX 950. Operating system installed: Windows 10 Home. Chassis type: Tower. Product type: PC. Product colour: Black | Intel Core i7-6700 (8M Cache, 3.4GHz), 16GB RAM, 1000GB HDD, Intel HD Graphics 530, Ethernet, Windows 10 | <b>Smart Multimedia Performance</b><br>\nVivoPC K31CD is powered by the 6th generation Intel® processors to give you significantly faster and more efficient multitasking performance over previous iterations. VivoPC K31CD enhances your daily computing experience, making online shopping, writing blogs, conducting presentations, or watching movies all the more enjoyable. <br>\n<br>\n<b>Ultra-Realistic 4K/UHD Visuals</b><br>\nVivoPC K31CD is with discrete NVIDIA or AMD graphics to bring home entertainment to the next level. It supports 4K/UHD (3840 x2160) displays so you can enjoy the latest movies, browse the web, or view photos in all their glory.<br>\n<br>\n<b>Expansive Audio, tuned by experts</b><br>\nA mixture of hardware, software, and tuning, ASUS SonicMaster was developed with the clear goal of giving you the best PC audio. A professional codec ensures precise sound performance; while an optimized amplifier, larger speakers and resonance chambers deliver powerful audio output and deeper bass. Additional signal processing helps fine tune the hardware, filtering noise and improving clarity so you can enjoy unrivalled audio on K31CD.<br>\n<br>\n<b>Windows 10 Home</b><br>\nWindows 10 Home brings the desktop back to the forefront, complete with the familiar convenience of the Start Menu. It also adds an Edge browser that lets you access the web with blistering speed and useful new functions. <br>\n<br>\n<b>SuperSpeed USB 3.1 transmission</b><br>\nVivoPC K31CD features SuperSpeed USB 3.1 transfering data up to 20 times faster than USB 2.0, and 2 times faster than USB 3.0. Besides, it also comes with all the connectivity options you need. HDMI output ports lets you hook your VivoPC K31CD up to an HDTV to supersize your entertainment. SATA 6Gbit/s ports offer blisteringly fast data transfer speeds, letting you save large files or quickly load games. <br>\n<br>\n<b>Ultra-fast connectivity</b><br>\nWith wireless transfer rates up to 433Mbit/s with compatible routers, 802.11ac Wi-Fi is around 8 times faster than 802.11g and around 3 times faster than 802.11n, making the VivoPC K31CD Series capable of streaming 4K/UHD video without the inconvenience of network cables.<br>\n<br>\n<b>ASUS desktops – Most recommended<br>\nWindows desktop brand</b><br>\nInnovation, design and reliability are at the heart of all ASUS computers. ASUS has won a PCMag.com Readers' Choice Award for its desktops four years running, leading the competition in both overall satisfaction and likelihood to be recommended. This proves that ASUS is better at delivering what customers want than rival Windows desktop PC companies. ASUS also had the lowest percentage of units needing repairs within the last 12 months, further proof of its trusted quality and reliability.<br>\n<br>\n<b>Trust worthy quality and reliability</b><br>\nASUS desktop PCs are subjected to a series of rigorous noise, vibration, drop, and thermal shock tests to ensure they meet our exacting standards and exceed those used by other manufacturers. So you can rest assured that your new computer can cope with extremes of dry, icy -40℃ to hot and humid 60℃ environments, as well as the bumps and knocks during shipping.

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 metadata_clean  \
0  asus k31cd-it049t pc 6th gen intel core i7 i7-6700 16 gb ddr4-sdram 1000 gb hdd black tower asus k31cd-it049t pcs/workstations asus k31cd-it049t. processor frequency 3.4 ghz, processor family 6th gen intel core i7, processor model i7-6700. internal memory 16 gb, internal memory type ddr4-sdram. total storage capacity 1000 gb, storage media hdd, card reader integrated. optical drive type dvd-rw. on-board graphics adapter model intel hd graphics 530, discrete graphics adapter model nvidia geforce gtx 950. operating system installed windows 10 home. chassis type tower. product type pc. product colour black intel core i7-6700 8m cache, 3.4ghz , 16gb ram, 1000gb hdd, intel hd graphics 530, ethernet, windows 10 smart multimedia performance vivopc k31cd is powered by the 6th generation intel processors to give you significantly faster and more efficient multitasking performance over previous iterations. vivopc k31cd enhances your daily computing experience, making online shopping, writing blogs, conducting presentations, or watching movies all the more enjoyable. ultra-realistic 4k/uhd visuals vivopc k31cd is with discrete nvidia or amd graphics to bring home entertainment to the next level. it supports 4k/uhd 3840 x2160 displays so you can enjoy the latest movies, browse the web, or view photos in all their glory. expansive audio, tuned by experts a mixture of hardware, software, and tuning, asus sonicmaster was developed with the clear goal of giving you the best pc audio. a professional codec ensures precise sound performance while an optimized amplifier, larger speakers and resonance chambers deliver powerful audio output and deeper bass. additional signal processing helps fine tune the hardware, filtering noise and improving clarity so you can enjoy unrivalled audio on k31cd. windows 10 home windows 10 home brings the desktop back to the forefront, complete with the familiar convenience of the start menu. it also adds an edge browser that lets you access the web with blistering speed and useful new functions. superspeed usb 3.1 transmission vivopc k31cd features superspeed usb 3.1 transfering data up to 20 times faster than usb 2.0, and 2 times faster than usb 3.0. besides, it also comes with all the connectivity options you need. hdmi output ports lets you hook your vivopc k31cd up to an hdtv to supersize your entertainment. sata 6gbit/s ports offer blisteringly fast data transfer speeds, letting you save large files or quickly load games. ultra-fast connectivity with wireless transfer rates up to 433mbit/s with compatible routers, 802.11ac wi-fi is around 8 times faster than 802.11g and around 3 times faster than 802.11n, making the vivopc k31cd series capable of streaming 4k/uhd video without the inconvenience of network cables. asus desktops most recommended windows desktop brand innovation, design and reliability are at the heart of all asus computers. asus has won a pcmag.com readers choice award for its desktops four years running, leading the competition in both overall satisfaction and likelihood to be recommended. this proves that asus is better at delivering what customers want than rival windows desktop pc companies. asus also had the lowest percentage of units needing repairs within the last 12 months, further proof of its trusted quality and reliability. trust worthy quality and reliability asus desktop pcs are subjected to a series of rigorous noise, vibration, drop, and thermal shock tests to ensure they meet our exacting standards and exceed those used by other manufacturers. so you can rest assured that your new computer can cope with extremes of dry, icy -40 to hot and humid 60 environments, as well as the bumps and knocks during shipping.

  Category.Name.Value
0    PCs/Workstations

In [42]:
data[data["ProductName"] == "K360"][["Brand", "metadata_text", "metadata_clean"]]

,Brand,metadata_text,metadata_clean
124,Logitech,"Logitech K360 keyboard RF Wireless QWERTY Pan Nordic | Logitech | K360 | Keyboards | Logitech K360. Keyboard form factor: Standard. Keyboard style: Straight. Connectivity technology: Wireless, Device interface: RF Wireless, Keyboard layout: QWERTY | Wireless Keyboard K360 | <b>The wireless keyboard that’s beautifully convenient and conveniently compact.</b><br>\n<br>\n<b>Compact comfort.</b><br>\nThe perfect laptop companion—this compact keyboard lets you type with more comfort while taking up less space.<br>\n<br>\n<b>Power-packed.</b><br>\nThe three-year battery life is so hassle-free you just might forget it uses batteries at all.<br>\n<br>\n<b>Just one touch.</b><br>\nYou can do more, faster with six hot keys and twelve programmable F-keys for instant access to music, e-mail and more.","logitech k360 keyboard rf wireless qwerty pan nordic logitech k360 keyboards logitech k360. keyboard form factor standard. keyboard style straight. connectivity technology wireless, device interface rf wireless, keyboard layout qwerty wireless keyboard k360 the wireless keyboard that s beautifully convenient and conveniently compact. compact comfort. the perfect laptop companion this compact keyboard lets you type with more comfort while taking up less space. power-packed. the three-year battery life is so hassle-free you just might forget it uses batteries at all. just one touch. you can do more, faster with six hot keys and twelve programmable f-keys for instant access to music, e-mail and more."
3784,Logitech,"Logitech K360 keyboard RF Wireless QWERTY Pan Nordic Grey | Logitech | K360 | Keyboards | Logitech K360. Keyboard form factor: Standard. Keyboard style: Straight. Connectivity technology: Wireless, Device interface: RF Wireless, Keyboard layout: QWERTY. Product colour: Grey | Wireless Keyboard K360 | <b>The wireless keyboard that’s beautifully convenient and conveniently compact.</b><br>\n<br>\n<b>Compact comfort.</b><br>\nThe perfect laptop companion—this compact keyboard lets you type with more comfort while taking up less space.<br>\n<br>\n<b>Power-packed.</b><br>\nThe three-year battery life is so hassle-free you just might forget it uses batteries at all.<br>\n<br>\n<b>Just one touch.</b><br>\nYou can do more, faster with six hot keys and twelve programmable F-keys for instant access to music, e-mail and more.","logitech k360 keyboard rf wireless qwerty pan nordic grey logitech k360 keyboards logitech k360. keyboard form factor standard. keyboard style straight. connectivity technology wireless, device interface rf wireless, keyboard layout qwerty. product colour grey wireless keyboard k360 the wireless keyboard that s beautifully convenient and conveniently compact. compact comfort. the perfect laptop companion this compact keyboard lets you type with more comfort while taking up less space. power-packed. the three-year battery life is so hassle-free you just might forget it uses batteries at all. just one touch. you can do more, faster with six hot keys and twelve programmable f-keys for instant access to music, e-mail and more."
70011,Logitech,"Logitech K360 keyboard RF Wireless Greek Black | Logitech | K360 | Keyboards | Logitech K360. Keyboard form factor: Standard. Keyboard style: Straight. Connectivity technology: Wireless, Device interface: RF Wireless, Recommended usage: Universal. Product colour: Black | 6 hot keys, 2.4 GHz wireless, Plug-and-play, Greek, Black | <b>Compact comfort for your laptop</b><br>\nYou can type in more comfort with a layout you’re used to. And it’s about 20% smaller than our standard keyboards, so it fits in your office, your living room or wherever you use your laptop.<br>\n<br>\n<b>Three-year battery life</b><br>\nThe extended battery life means you won’t spend your time tracking down new batteries.*<br>\n<br>\n<b>Six hot keys</b><br>\nSkip a song. Pause a video. Turn up the volume. You get six hot keys for instant access to play, pause, previous, next, volume and mute.<br>\n<br>\n<b>Twelve programmable F-keys</b><br>\nYou’re in charge with programmable F-keys** you can easily customize to open your favorite applications, folders or Web pages.<br>\n<br>\n<b>Advanced 2.4 GHz wireless</b><br>\nSo you can work or play in more places—like your comfy couch—the long-range wireless connection virtually eliminates delays, dropouts and interference.<br>\n<br>\n<b>Logitech Unifying receiver</b><br>\nThe tiny receiver stays in your laptop. Plus, you can easily add a compatible wireless mouse, keyboard or number pad—without the hassle of multiple USB receivers.<br>\n<br>\n<b>Plug-and-play simplicity</b><br>\nSetup takes seconds—you simply plug the wireless receiver into a USB port, pull the battery tab and start using your keyboard right away without software.<br>\n<br>\n<b>Whisper-quiet, framed keys</b><br>\nThe framed keys look modern and barely make a sound, while providing a more comfortable typing experience than laptop and netbook keyboards.<br>\n<br>\n<b>Sturdy, adjustable-tilt legs</b><br>\nYou can extend the sturdy folding legs to increase the keyboard tilt by eight degrees to address your personal comfort needs. Rubber feet prevent slipping.","logitech k360 keyboard rf wireless greek black logitech k360 keyboards logitech k360. keyboard form factor standard. keyboard style straight. connectivity technology wireless, device interface rf wireless, recommended usage universal. product colour black 6 hot keys, 2.4 ghz wireless, plug-and-play, greek, black compact comfort for your laptop you can type in more comfort with a layout you re used to. and it s about 20 smaller than our standard keyboards, so it fits in your office, your living room or wherever you use your laptop. three-year battery life the extended battery life means you won t spend your time tracking down new batteries. six hot keys skip a song. pause a video. turn up the volume. you get six hot keys for instant access to play, pause, previous, next, volume and mute. twelve programmable f-keys you re in charge with programmable f-keys you can easily customize to open your favorite applications, folders or web pages. advanced 2.4 ghz wireless so you can work or play in more places like your comfy couch the long-range wireless connection virtually eliminates delays, dropouts and interference. logitech unifying receiver the tiny receiver stays in your laptop. plus, you can easily add a compatible wireless mouse, keyboard or number pad without the hassle of multiple usb receivers. plug-and-play simplicity setup takes seconds you simply plug the wireless receiver into a usb port, pull the battery tab and start using your keyboard right away without software. whisper-quiet, framed keys the framed keys look modern and barely make a sound, while providing a more comfortable typing experience than laptop and netbook keyboards. sturdy, adjustable-tilt legs you can extend the sturdy folding legs to increase the keyboard tilt by eight degrees to address your personal comfort needs. rubber feet prevent slipping."
79199,Logitech,"Logitech K360 keyboard RF Wireless Black,Coral | Logitech | K360 | Keyboards | Logitech K360. Keyboard form factor: Standard. Keyboard style: Straight. Connectivity technology: Wireless, Device interface: RF Wireless, Recommended usage: Universal. Product colour: Black,Coral | Keyboard, 2.4GHz, Coral/Black | <b>Compact comfort</b><br>\n<br>\nThe perfect laptop companion—this compact keyboard lets you type with more comfort while taking up less space.<br>\n<br>\n<b>Power-packed</b><br>\n<br>\nThe three-year battery life is so hassle-free you just might forget it uses batteries at all.<br>\n<br>\n<b>Just one touch</b><br>\n<br>\nYou can do more, faster with six hot keys and twelve programmable F-keys for instant access to music, e-mail and more.<br>\n<br>\n<b>More power</b><br>\n<br>\nYou pop the tiny Logitech Unifying receiver in your notebook and leave it there. You can even add more devices. Plug it. Forget it. Add to it. Learn more about the Logitech Unifying receiver.<br>\n<br>\n<b>Compact comfort for your laptop</b><br>\nYou can type in more comfort with a layout you’re used to. And it’s about 20% smaller than our standard keyboards, so it fits in your office, your living room or wherever you use your laptop.<br>\n<br>\n<b>Three-year battery life</b><br>\nThe extended battery life means you won’t spend your time tracking down new batteries.<br>\n<br>\n<b>Six hot keys</b><br>\nSkip a song. Pause a video. Turn up the volume. You get six hot keys for instant access to play, pause, previous, next, volume and mute.<br>\n<br>\n<b>Twelve programmable F-keys</b><br>\nYou’re in charge with programmable F-keys you can easily customize to open your favorite applications, folders or Web pages.<br>\n<br>\n<b>Advanced 2.4 GHz wireless</b><br>\nSo you can work or play in more places—like your comfy couch—the long-range wireless connection virtually eliminates delays, dropouts and interference.<br>\n<br>\n<b>Logitech Unifying receiver</b><br>\nThe tiny receiver stays in your laptop. Plus, you can easily add a compatible wireless mouse, keyboard or number pad—without the hassle of multiple USB receivers.<br>\n<br>\n<b>Plug-and-play simplicity</b><br>\nSetup takes seconds—you simply plug the wireless receiver into a USB port, pull the battery tab and start using your keyboard right away without software.<br>\n<br>\n<b>Whisper-quiet, framed keys</b><br>\nThe framed keys look modern and barely make a sound, while providing a more comfortable typing experience than laptop and netbook keyboards.<br>\n<br>\n<b>Sturdy, adjustable-tilt legs</b><br>\nYou can extend the sturdy folding legs to increase the keyboard tilt by eight degrees to address your personal comfort needs. Rubber feet prevent slipping.","logitech k360 keyboard rf wireless black,coral logitech k360 keyboards logitech k360. keyboard form factor standard. keyboard style straight. connectivity technology wireless, device interface rf wireless, recommended usage universal. product colour black,coral keyboard, 2.4ghz, coral/black compact comfort the perfect laptop companion this compact keyboard lets you type with more comfort while taking up less space. power-packed the three-year battery life is so hassle-free you just might forget it uses batteries at all. just one touch you can do more, faster with six hot keys and twelve programmable f-keys for instant access to music, e-mail and more. more power you pop the tiny logitech unifying receiver in your notebook and leave it there. you can even add more devices. plug it. forget it. add to it. learn more about the logitech unifying receiver. compact comfort for your laptop you can type in more comfort with a layout you re used to. and it s about 20 smaller than our standard keyboards, so it fits in your office, your living room or wherever you use your laptop. three-year battery life the extended battery life means you won t spend your time tracking down new batteries. six hot keys skip a song. pause a video. turn up the volume. you get six hot keys for instant access to play, pause, previous, next, volume and mute. twelve programmable f-keys you re in charge with programmable f-keys you can easily customize to open your favorite applications, folders or web pages. advanced 2.4 ghz wireless so you can work or play in more places like your comfy couch the long-range wireless connection virtually eliminates delays, dropouts and interference. logitech unifying receiver the tiny receiver stays in your laptop. plus, you can easily add a compatible wireless mouse, keyboard or number pad without the hassle of multiple usb receivers. plug-and-play simplicity setup takes seconds you simply plug the wireless receiver into a usb port, pull the battery tab and start using your keyboard right away without software. whisper-quiet, framed keys the framed keys look modern and barely make a sound, while providing a more comfortable typing experience than laptop and netbook keyboards. sturdy, adjustable-tilt legs you can extend the sturdy folding legs to increase the keyboard tilt by eight degrees to address your personal comfort needs. rubber feet prevent slipping."
106543,Logitech,"Logitech K360 keyboard RF Wireless Hebrew Black | Logitech | K360 | Keyboards | Logitech K360. Keyboard form factor: Standard. Keyboard style: Straight. Connectivity technology: Wireless, Device interface: RF Wireless, Recommended usage: Universal. Product colour: Black | 6 hot keys, 2.4 GHz wireless, Plug-and-play, Hebrew, Black | <b>Compact comfort for your laptop</b><br>\nYou can type in more comfort with a layout you’re used to. And it’s about 20% smaller than our standard keyboards, so it fits in your office, your living room or wherever you use your laptop.<br>\n<br>\n<b>Three-year battery life</b><br>\nThe extended battery life means you won’t spend your time tracking down new batteries.*<br>\n<br>\n<b>Six hot keys</b><br>\nSkip a song. Pause a video. Turn up the volume. You get six hot keys for instant access to play, pause, previous, next, volume and mute.<br>\n<br>\n<b>Twelve programmable F-keys</b><br>\nYou’re in charge with programmable F-keys** you can easily customize to open your favorite applications, folders or Web pages.<br>\n<br>\n<b>Advanced 2.4 GHz wireless</b><br>\nSo you can work or play in more places—like your comfy couch—the long-range wireless connection virtually eliminates delays, dropouts and interference.<br>\n<br>\n<b>Logitech Unifying receiver</b><br>\nThe tiny receiver stays in your laptop. Plus, you can easily add a compatible wireless mouse, keyboard or number pad—without the hassle of multiple USB receivers.<br>\n<br>\n<b>Plug-and-play simplicity</b><br>\nSetup takes seconds—you simply plug the wireless receiver into a USB port, pull the battery tab and start using your keyboard right away without software.<br>\n<br>\n<b>Whisper-quiet, framed keys</b><br>\nThe framed keys look modern and barely make a sound, while providing a more comfortable typing experience than laptop and netbook keyboards.<br>\n<br>\n<b>Sturdy, adjustable-tilt legs</b><br>\nYou can extend the sturdy folding legs to increase the keyboard tilt by eight degrees to address your personal comfort needs. Rubber feet prevent slipping.","logitech k360 keyboard rf wireless hebrew black logitech k360 keyboards logitech k360. keyboard form factor standard. keyboard style straight. connectivity technology wireless, device interface rf wireless, recommended usage universal. product colour black 6 hot keys, 2.4 ghz wireless, plug-and-play, hebrew, black compact comfort for your laptop you can type in more comfort with a layout you re used to. and it s about 20 smaller than our standard keyboards, so it fits in your office, your living room or wherever you use your laptop. three-year battery life the extended battery life means you won t spend your time tracking down new batteries. six hot keys skip a song. pause a video. turn up the volume. you get six hot keys for instant access to play, pause, previous, next, volume and mute. twelve programmable f-keys you re in charge with programmable f-keys you can easily customize to open your favorite applications, folders or web pages. advanced 2.4 ghz wireless so you can work or play in more places like your comfy couch the long-range wireless connection virtually eliminates delays, dropouts and interference. logitech unifying receiver the tiny receiver stays in your laptop. plus, you can easily add a compatible wireless mouse, keyboard or number pad without the hassle of multiple usb receivers. plug-and-play simplicity setup takes seconds you simply plug the wireless receiver into a usb port, pull the battery tab and start using your keyboard right away without software. whisper-quiet, framed keys the framed keys look modern and barely make a sound, while providing a more comfortable typing experience than laptop and netbook keyboards. sturdy, adjustable-tilt legs you can extend the sturdy folding legs to increase the keyboard tilt by eight degrees to address your personal comfort needs. rubber feet prevent slipping."
122947,Logitech,"Logitech K360 keyboard RF Wireless Turkish White | Logitech | K360 | Keyboards | Logitech K360. Keyboard form factor: Standard. Keyboard style: Straight. Connectivity technology: Wireless, Device interface: RF Wireless. Product colour: White | None | None","logitech k360 keyboard rf wireless turkish white logitech k360 keyboards logitech k360. keyboard form factor standard. keyboard style straight. connectivity technology wireless, device interface rf wireless. product colour white none none"
133557,Logitech,"Logitech K360 keyboard RF Wireless QWERTY English | Logitech | K360 | Keyboards | Logitech K360. Keyboard form factor: Standard. Keyboard style: Straight. Connectivity technology: Wireless, Device interface: RF Wireless, Keyboard layout: QWERTY | Wireless Keyboard K360 | <b>The wireless keyboard that’s beautifully convenient and conveniently compact.</b><br>\n<br>\n<b>Compact comfort.</b><br>\nThe perfect laptop companion—this compact keyboard lets you type with more comfort while taking up less space.<br>\n<br>\n<b>Power-packed.</b><br>\nThe three-year battery life is so hassle-free you just might forget it uses batteries at all.<br>\n<br>\n<b>Just one touch.</b><br>\nYou can do more, faster with six hot keys and twelve programmable F-keys for instant access to music, e-mail and more.","logitech k360 keyboard rf wireless qwerty english logitech k360 keyboards logitech k360. keyboard form factor standard. keyboard style straight. connectivity technology wireless, device interface rf wireless, keyboard layout qwerty wireless keyboard k360 the wireless keyboard that s beautifully convenient and conveniently compact. compact comfort. the perfect laptop companion this compact keyboard lets you type with more comfort while taking up less space. power-packed. the three-year battery life is so hassle-free you just might forget it uses batteries at all. just one touch. you can do more, faster with six hot keys and twelve programmable f-keys for instant access to music, e-mail and more."

In [56]:
df_final = pd.read_csv("/Users/suyashmali/Case_Study_Materials/LLM/Final_Cleaned_Data.csv")

In [57]:
df_final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 289865 entries, 0 to 289864
Data columns (total 8 columns):
 #   Column                                     Non-Null Count   Dtype
---  ------                                     --------------   -----
 0   Brand                                      289865 non-null  object
 1   BrandPartCode                              289865 non-null  object
 2   ProductName                                289838 non-null  object
 3   Description.LongProductName                244464 non-null  object
 4   Description.LongDesc                       225417 non-null  object
 5   SummaryDescription.LongSummaryDescription  289865 non-null  object
 6   metadata_text                              289865 non-null  object
 7   metadata_text_clean                        289865 non-null  object
dtypes: object(8)
memory usage: 17.7+ MB

In [61]:
df_final[df_final["ProductName"] == "X205TA-FD0052BS"][["Brand", "metadata_text_clean"]]

,Brand,metadata_text_clean
55622,ASUS,"asus x205ta-fd0052bs intel atom z3735f (1.33ghz), 29.464 cm (11.6 ) hd (1366x768), 2gb ddr3l, 128gb ssd, card reader, camera, bluetooth 4.0, windows 8.1 64-bit asus eeebook x205ta-fd0052bs. product type: notebook, form factor: clamshell. processor family: intel atom , processor model: z3735f, processor frequency: 1.33 ghz. display diagonal: 29.5 cm (11.6 ), hd type: hd, display resolution: 1366 x 768 pixels. internal memory: 2 gb, internal memory type: ddr3l-sdram. total storage capacity: 128 gb, storage media: ssd. on-board graphics adapter. operating system installed: windows 8.1. product colour: blue eeebook"

In [94]:
# df_final[df_final["ProductName"] == "K360"][["BrandInfo.BrandName", "metadata_clean", "Category.Name.Value", "SummaryDescription.LongSummaryDescription", "SummaryDescription.ShortSummaryDescription"]]

In [97]:
df_cleaned[df_cleaned["ProductName"] == "GL10CS-BE027T-BE"][["BrandInfo.BrandName", "Category.Name.Value"]]

        BrandInfo.BrandName Category.Name.Value
1104829                ASUS    PCs/Workstations

In [101]:
df_cleaned[df_cleaned["ProductName"] == "GL10CS-BE027T-BE"][["BrandInfo.BrandName", "Category.Name.Value"]]

        BrandInfo.BrandName Category.Name.Value
1104829                ASUS    PCs/Workstations

In [109]:
df_3level[df_3level["ProductName"] == "R516UX-DM512T"][["BrandInfo.BrandName", "Category.Name.Value", "pathlist_names"]]

,BrandInfo.BrandName,Category.Name.Value,pathlist_names
676773,ASUS,Notebooks,Computers & Electronics>Computers>Notebooks

      BrandInfo.BrandName Category.Name.Value
49753           Advantech        Thin Clients

In [107]:
df_3level[df_3level["ProductName"] == "UTC-515A-PE"][["BrandInfo.BrandName", "Category.Name.Value", "pathlist_names"]]

,BrandInfo.BrandName,Category.Name.Value,pathlist_names
49753,Advantech,Thin Clients,Computers & Electronics>Computers>Thin Clients

In [117]:
df_3level[df_3level["ProductName"] == "Preferred Pro"][["BrandInfo.BrandName", "Category.Name.Value", "pathlist_names"]]

,BrandInfo.BrandName,Category.Name.Value,pathlist_names
574614,Lenovo,Keyboards,Computers & Electronics>Data Input Devices>Keyboards
573011,Lenovo,Keyboards,Computers & Electronics>Data Input Devices>Keyboards
574425,Lenovo,Keyboards,Computers & Electronics>Data Input Devices>Keyboards
574275,Lenovo,Keyboards,Computers & Electronics>Data Input Devices>Keyboards
575569,Lenovo,Keyboards,Computers & Electronics>Data Input Devices>Keyboards
571254,Lenovo,Keyboards,Computers & Electronics>Data Input Devices>Keyboards
573014,Lenovo,Keyboards,Computers & Electronics>Data Input Devices>Keyboards
573022,Lenovo,Keyboards,Computers & Electronics>Data Input Devices>Keyboards
575577,Lenovo,Keyboards,Computers & Electronics>Data Input Devices>Keyboards
575557,Lenovo,Keyboards,Computers & Electronics>Data Input Devices>Keyboards
568057,Lenovo,Keyboards,Computers & Electronics>Data Input Devices>Keyboards
569632,Lenovo,Keyboards,Computers & Electronics>Data Input Devices>Keyboards
568059,Lenovo,Keyboards,Computers & Electronics>Data Input Devices>Keyboards
573029,Lenovo,Keyboards,Computers & Electronics>Data Input Devices>Keyboards
569634,Lenovo,Keyboards,Computers & Electronics>Data Input Devices>Keyboards
568053,Lenovo,Keyboards,Computers & Electronics>Data Input Devices>Keyboards
569649,Lenovo,Keyboards,Computers & Electronics>Data Input Devices>Keyboards
573005,Lenovo,Keyboards,Computers & Electronics>Data Input Devices>Keyboards
573028,Lenovo,Keyboards,Computers & Electronics>Data Input Devices>Keyboards
569638,Lenovo,Keyboards,Computers & Electronics>Data Input Devices>Keyboards
568816,Lenovo,Keyboards,Computers & Electronics>Data Input Devices>Keyboards
575568,Lenovo,Keyboards,Computers & Electronics>Data Input Devices>Keyboards
569642,Lenovo,Keyboards,Computers & Electronics>Data Input Devices>Keyboards
573485,Lenovo,Keyboards,Computers & Electronics>Data Input Devices>Keyboards
569637,Lenovo,Keyboards,Computers & Electronics>Data Input Devices>Keyboards
569635,Lenovo,Keyboards,Computers & Electronics>Data Input Devices>Keyboards
569640,Lenovo,Keyboards,Computers & Electronics>Data Input Devices>Keyboards
573027,Lenovo,Keyboards,Computers & Electronics>Data Input Devices>Keyboards
573120,Lenovo,Keyboards,Computers & Electronics>Data Input Devices>Keyboards
572952,Lenovo,Keyboards,Computers & Electronics>Data Input Devices>Keyboards
568060,Lenovo,Keyboards,Computers & Electronics>Data Input Devices>Keyboards
569648,Lenovo,Keyboards,Computers & Electronics>Data Input Devices>Keyboards
569644,Lenovo,Keyboards,Computers & Electronics>Data Input Devices>Keyboards
573023,Lenovo,Keyboards,Computers & Electronics>Data Input Devices>Keyboards
569636,Lenovo,Keyboards,Computers & Electronics>Data Input Devices>Keyboards
569646,Lenovo,Keyboards,Computers & Electronics>Data Input Devices>Keyboards

In [118]:
df_3level[df_3level["ProductName"] == "Ultra-Compact Bluetooth Keyboard"][["BrandInfo.BrandName", "Category.Name.Value", "pathlist_names"]]

,BrandInfo.BrandName,Category.Name.Value,pathlist_names
573211,Anker,Keyboards,Computers & Electronics>Data Input Devices>Keyboards
573212,Anker,Keyboards,Computers & Electronics>Data Input Devices>Keyboards

### ["C_id"] == , C_name : Mobile Phone Cases

In [112]:
df_3level[df_3level["ProductName"] == "Oxford"][["BrandInfo.BrandName", "Category.Name.Value", "pathlist_names"]]

,BrandInfo.BrandName,Category.Name.Value,pathlist_names
359738,ZAGG,Mobile Phone Cases,Computers & Electronics>Telecom & Navigation>Mobile Phone Cases
360918,ZAGG,Mobile Phone Cases,Computers & Electronics>Telecom & Navigation>Mobile Phone Cases
361007,ZAGG,Mobile Phone Cases,Computers & Electronics>Telecom & Navigation>Mobile Phone Cases
360937,ZAGG,Mobile Phone Cases,Computers & Electronics>Telecom & Navigation>Mobile Phone Cases

In [113]:
df_3level[df_3level["ProductName"] == "Juice pack air"][["BrandInfo.BrandName", "Category.Name.Value", "pathlist_names"]]

,BrandInfo.BrandName,Category.Name.Value,pathlist_names
357302,Mophie,Mobile Phone Cases,Computers & Electronics>Telecom & Navigation>Mobile Phone Cases
357303,Mophie,Mobile Phone Cases,Computers & Electronics>Telecom & Navigation>Mobile Phone Cases
355481,Mophie,Mobile Phone Cases,Computers & Electronics>Telecom & Navigation>Mobile Phone Cases
357307,Mophie,Mobile Phone Cases,Computers & Electronics>Telecom & Navigation>Mobile Phone Cases
357308,Mophie,Mobile Phone Cases,Computers & Electronics>Telecom & Navigation>Mobile Phone Cases
357305,Mophie,Mobile Phone Cases,Computers & Electronics>Telecom & Navigation>Mobile Phone Cases
357311,Mophie,Mobile Phone Cases,Computers & Electronics>Telecom & Navigation>Mobile Phone Cases
357309,Mophie,Mobile Phone Cases,Computers & Electronics>Telecom & Navigation>Mobile Phone Cases

In [115]:
df_3level[df_3level["ProductName"] == "GP-G973HIFGKWG"][["BrandInfo.BrandName", "Category.Name.Value", "pathlist_names"]]

,BrandInfo.BrandName,Category.Name.Value,pathlist_names
359690,Samsung,Mobile Phone Cases,Computers & Electronics>Telecom & Navigation>Mobile Phone Cases

## ["C_id"] == 28, C_name : Home Entertainment Systems

In [121]:
df_3level[df_3level["ProductName"] == "KDL-46HX905"][["BrandInfo.BrandName", "Category.Name.Value", "pathlist_names"]]

,BrandInfo.BrandName,Category.Name.Value,pathlist_names
293348,Sony,TVs,Computers & Electronics>TVs & Monitors>TVs

In [122]:
df_3level[df_3level["ProductName"] == "LCD monitor, LED backlight 19B4LPCB/69"][["BrandInfo.BrandName", "Category.Name.Value", "pathlist_names"]]

,BrandInfo.BrandName,Category.Name.Value,pathlist_names
273351,Philips,Computer Monitors,Computers & Electronics>TVs & Monitors>Computer Monitors

In [123]:
df_3level[df_3level["ProductName"] == "P554U"][["BrandInfo.BrandName", "Category.Name.Value", "pathlist_names"]]

,BrandInfo.BrandName,Category.Name.Value,pathlist_names
606577,NEC,Data Projectors,Computers & Electronics>Projectors>Data Projectors

## C_id = 22	C_name: Enterprise Security Software

In [132]:
df_3level[df_3level["ProductName"] == "EIRN0029"][["BrandInfo.BrandName", "Category.Name.Value", "pathlist_names"]]

,BrandInfo.BrandName,Category.Name.Value,pathlist_names
215201,Trend Micro,Software Licenses/Upgrades,Computers & Electronics>Software>Software Licenses/Upgrades

In [130]:
df_3level[df_3level["ProductName"] == "Enterprise Security Suite, RNW, EDU, 7m, 501-750u, ML"][["BrandInfo.BrandName", "Category.Name.Value", "pathlist_names"]]

,BrandInfo.BrandName,Category.Name.Value,pathlist_names
163660,Trend Micro,Software Licenses/Upgrades,Computers & Electronics>Software>Software Licenses/Upgrades

In [134]:
df_3level[df_3level["ProductName"] == "Elastica"][["BrandInfo.BrandName", "Category.Name.Value", "pathlist_names"]]

,BrandInfo.BrandName,Category.Name.Value,pathlist_names
177549,Symantec,Software Licenses/Upgrades,Computers & Electronics>Software>Software Licenses/Upgrades

In [135]:
df_3level[df_3level["ProductName"] == "Prosecure UTM10 VPN Firewall"][["BrandInfo.BrandName", "Category.Name.Value", "pathlist_names"]]

,BrandInfo.BrandName,Category.Name.Value,pathlist_names
63647,Netgear,Hardware Firewalls,Computers & Electronics>Networking>Hardware Firewalls

## C_id: 17, C_name : IT Support Services

In [136]:
df_3level[df_3level["ProductName"] == "ServicePack 3 Years On-site 8h 7x24 Primergy TX300"][["BrandInfo.BrandName", "Category.Name.Value", "pathlist_names"]]

,BrandInfo.BrandName,Category.Name.Value,pathlist_names
461187,Fujitsu,Warranty & Support Extensions,Computers & Electronics>Warranty & Support>Warranty & Support Extensions

In [141]:
df_3level[df_3level["ProductName"] == "FSP:G-SW5GF63PRE0B"][["BrandInfo.BrandName", "Category.Name.Value", "pathlist_names"]]

,BrandInfo.BrandName,Category.Name.Value,pathlist_names
501110,Fujitsu,Warranty & Support Extensions,Computers & Electronics>Warranty & Support>Warranty & Support Extensions

In [143]:
df_3level[df_3level["ProductName"] == "01CG027"][["BrandInfo.BrandName", "Category.Name.Value", "pathlist_names"]]

,BrandInfo.BrandName,Category.Name.Value,pathlist_names
489881,Lenovo,Warranty & Support Extensions,Computers & Electronics>Warranty & Support>Warranty & Support Extensions

In [153]:
df_cleaned[df_cleaned["ProductName"] == "01CG027"][["BrandInfo.BrandName", "Category.Name.Value", "metadata_clean"]]

,BrandInfo.BrandName,Category.Name.Value,metadata_clean
489881,Lenovo,Warranty & Support Extensions,"lenovo 01cg027 warranty/support extension lenovo 01cg027 warranty support extensions lenovo 01cg027. number of years 3 year s , service time hours x days 9x5, response time 4 h, type on-site 3 years, 9x5, 4h response, on-site lenovo offers a comprehensive portfolio of value-added services that support the full lifecycle of your lenovo assets from procurement to disposition. our service experience can optimise productivity and user satisfaction by reducing downtime, and enabling you or your it staff to focus on your business-critical issues."

## C_id : 31, C_name :Battery Chargers and Packs

In [154]:
df_cleaned[df_cleaned["ProductName"] == "MOBILE PHONE BATTERY"][["BrandInfo.BrandName", "Category.Name.Value", "metadata_clean"]]

,BrandInfo.BrandName,Category.Name.Value,metadata_clean
397384,2-Power,Mobile Phone Spare Parts,"2-power mobile phone battery black 2-power mobile phone battery mobile phone spare parts 2-power mobile phone battery. product type battery, brand compatibility samsung, product colour black. width 68 mm, height 52 mm, depth 6 mm. compatible products samsung galaxy note 2500 mah, 3.7 v for samsung galaxy note"

In [155]:
df_cleaned[df_cleaned["ProductName"] == "SYPOWERBANK4400K"][["BrandInfo.BrandName", "Category.Name.Value", "metadata_clean"]]

,BrandInfo.BrandName,Category.Name.Value,metadata_clean
331487,Cellularline,Power Banks,"cellularline sypowerbank4400k power bank black 4400 mah cellularline sypowerbank4400k power banks cellularline sypowerbank4400k. product colour black, charger compatibility universal. battery capacity 4400 mah, charging source usb. usb input port type micro-usb. cables included usb none none"

In [156]:
df_cleaned[df_cleaned["ProductName"] == "EB-K1G6UWU"][["BrandInfo.BrandName", "Category.Name.Value", "metadata_clean"]]

,BrandInfo.BrandName,Category.Name.Value,metadata_clean
397892,Samsung,Mobile Phone Spare Parts,"samsung eb-k1g6uwu white samsung eb-k1g6uwu mobile phone spare parts samsung eb-k1g6uwu. product colour white. width 68 mm, height 135 mm, depth 6 mm high capacity li-ion battery 3000mah, incl. battery cover, for samsung galaxy s iii this battery is a 3,000 mah extended battery. if you need some extra juice for your battery, the extended battery will certainly see a longer run time with the device. nfc enabled. available in 3 colours."

In [157]:
df_cleaned[df_cleaned["ProductName"] == "UX305FA-FC066P"][["BrandInfo.BrandName", "Category.Name.Value", "metadata_clean"]]

,BrandInfo.BrandName,Category.Name.Value,metadata_clean
653122,ASUS,Notebooks,"asus zenbook ux305fa-fc066p black notebook 33.8 cm 13.3 1920 x 1080 pixels intel core m m-5y10 8 gb lpddr3-sdram 128 gb ssd asus ux305fa-fc066p notebooks asus zenbook ux305fa-fc066p. product type notebook, form factor clamshell. processor family intel core m, processor model m-5y10, processor frequency 0.8 ghz. display diagonal 33.8 cm 13.3 , hd type full hd, display resolution 1920 x 1080 pixels. internal memory 8 gb, internal memory type lpddr3-sdram. total storage capacity 128 gb, storage media ssd. on-board graphics adapter. operating system installed windows 8.1 pro. product colour black intel core m-5y10c 0.8ghz , 8gb lpddr3 ram, 128gb ssd, 33.782 cm 13.3 1920 x 1200 ips, intel hd graphics 5300, hd webcam, wi-fi 802.11ac, bluetooth 4.0, windows 8.1 pro 64-bit thinner, lighter, faster your slim, featherweight powerhouse zenbook ux305 weighs a mere 1.2kg, and is just 1.2cm thin. it is quite simply the thinnest and lightest laptop with a 13.3-inch qhd display. sheer elegance, cool colors agile beauty for all to behold the light, agile zenbook ux305 epitomizes elegance with its two chic finishes refined white ceramic alloy or obsidian stone with spun-metal hairline details, and subtle diamond-cut edges that further highlight its understated beauty. bright in every sense a display that always easy to see the perfect view demands perfect balance of ambient light and screen brightness so zenbook ux305 manages your display dynamically. smart light sensors know whether you re on a sunny beach or in a dark meeting room, adjusting display brightness accordingly. both the batteries and your eyes will be much happier sound you won t believe an incredible laptop like zenbook ux305 deserves incredible sound, and so the asus golden ear audio engineering team developed sonicmaster, incorporating icepower , bang olufsen technology. sonicmaster produces sound like you ve never heard from a laptop, with deep rich bass and crystal-clear vocals. your zenbook, your cloud asus cloud services provide a complete platform for online living, accessible anywhere from a host of devices. with asus webstorage, convenience is the main priority, offering you easy storage, sharing, and syncing of everything from business presentations to photo albums and your favorite multimedia content. each zenbook ux305 comes with 16gb of webstorage space free for three years."

In [158]:
df_cleaned[df_cleaned["ProductName"] == "NT910S3L"][["BrandInfo.BrandName", "Category.Name.Value", "metadata_clean"]]

,BrandInfo.BrandName,Category.Name.Value,metadata_clean
696633,Samsung,Notebooks,"samsung 9 nt910s3l white notebook 33.8 cm 13.3 1920 x 1080 pixels 6th gen intel core i3 i3-6100u 8 gb ddr4-sdram 128 gb ssd samsung nt910s3l notebooks samsung 9 nt910s3l. product type notebook, form factor clamshell. processor family 6th gen intel core i3, processor model i3-6100u, processor frequency 2.3 ghz. display diagonal 33.8 cm 13.3 , hd type full hd, display resolution 1920 x 1080 pixels. internal memory 8 gb, internal memory type ddr4-sdram. total storage capacity 128 gb, storage media ssd. on-board graphics adapter. operating system installed windows 10 home. product colour white none none"
696606,Samsung,Notebooks,"samsung 9 nt910s3l white notebook 33.8 cm 13.3 1920 x 1080 pixels 6th gen intel core i5 i5-6200u 8 gb ddr4-sdram 256 gb ssd samsung nt910s3l notebooks samsung 9 nt910s3l. product type notebook, form factor clamshell. processor family 6th gen intel core i5, processor model i5-6200u, processor frequency 2.3 ghz. display diagonal 33.8 cm 13.3 , hd type full hd, display resolution 1920 x 1080 pixels. internal memory 8 gb, internal memory type ddr4-sdram. total storage capacity 256 gb, storage media ssd. on-board graphics adapter. operating system installed windows 10 home. product colour white none none"
696826,Samsung,Notebooks,"samsung 9 nt910s3l white notebook 33.8 cm 13.3 1920 x 1080 pixels intel celeron 3855u 4 gb lpddr3-sdram 128 gb ssd samsung nt910s3l notebooks samsung 9 nt910s3l. product type notebook, form factor clamshell. processor family intel celeron , processor model 3855u, processor frequency 1.6 ghz. display diagonal 33.8 cm 13.3 , hd type full hd, display resolution 1920 x 1080 pixels. internal memory 4 gb, internal memory type lpddr3-sdram. total storage capacity 128 gb, storage media ssd. on-board graphics adapter. operating system installed windows 10 home. product colour white none none"
696617,Samsung,Notebooks,"samsung 9 nt910s3l white notebook 33.8 cm 13.3 1920 x 1080 pixels intel pentium 4405u 4 gb lpddr3-sdram 128 gb ssd samsung nt910s3l notebooks samsung 9 nt910s3l. product type notebook, form factor clamshell. processor family intel pentium , processor model 4405u, processor frequency 2.1 ghz. display diagonal 33.8 cm 13.3 , hd type full hd, display resolution 1920 x 1080 pixels. internal memory 4 gb, internal memory type lpddr3-sdram. total storage capacity 128 gb, storage media ssd. on-board graphics adapter. operating system installed windows 10 home. product colour white none none"
696823,Samsung,Notebooks,"samsung 9 nt910s3l white notebook 33.8 cm 13.3 1920 x 1080 pixels intel pentium 4405u 4 gb ddr4-sdram 128 gb ssd samsung nt910s3l notebooks samsung 9 nt910s3l. product type notebook, form factor clamshell. processor family intel pentium , processor model 4405u, processor frequency 2.1 ghz. display diagonal 33.8 cm 13.3 , hd type full hd, display resolution 1920 x 1080 pixels. internal memory 4 gb, internal memory type ddr4-sdram. total storage capacity 128 gb, storage media ssd. on-board graphics adapter. operating system installed windows 10 home. product colour white none none"
671843,Samsung,Notebooks,"samsung 9 nt910s3l white notebook 33.8 cm 13.3 1920 x 1080 pixels 6th gen intel core i5 i5-6200u 8 gb lpddr3-sdram 500 gb hdd samsung nt910s3l notebooks samsung 9 nt910s3l. product type notebook, form factor clamshell. processor family 6th gen intel core i5, processor model i5-6200u, processor frequency 2.3 ghz. display diagonal 33.8 cm 13.3 , hd type full hd, display resolution 1920 x 1080 pixels. internal memory 8 gb, internal memory type lpddr3-sdram. total storage capacity 500 gb, storage media hdd. on-board graphics adapter. product colour white. weight 1.34 kg none none"
699512,Samsung,Notebooks,"samsung 9 nt910s3l blue notebook 33.8 cm 13.3 1920 x 1080 pixels intel celeron 3855u 4 gb ddr4-sdram 128 gb ssd samsung nt910s3l notebooks samsung 9 nt910s3l. product type notebook, form factor clamshell. processor family intel celeron , processor model 3855u, processor frequency 1.6 ghz. display diagonal 33.8 cm 13.3 , hd type full hd, display resolution 1920 x 1080 pixels. internal memory 4 gb, internal memory type ddr4-sdram. total storage capacity 128 gb, storage media ssd. on-board graphics adapter. operating system installed windows 10 home. product colour blue none none"

In [161]:
df_cleaned[df_cleaned["ProductName"] == "SM-G973F"][["BrandInfo.BrandName", "Category.Name.Value", "metadata_clean"]]

,BrandInfo.BrandName,Category.Name.Value,metadata_clean
75446,Samsung,Smartphones,"samsung galaxy s10 sm-g973f 15.5 cm 6.1 8 gb 128 gb dual sim white 3400 mah samsung sm-g973f smartphones samsung galaxy s10 sm-g973f. display diagonal 15.5 cm 6.1 , display resolution 1440 x 3040 pixels, display type dynamic amoled. processor frequency 2.7 ghz. ram capacity 8 gb, internal storage capacity 128 gb. rear camera resolution numeric 12 mp, rear camera type triple camera. sim card capability dual sim, 3g, 4g. operating system installed android 9.0. battery capacity 3400 mah. product colour white. weight 157 g 15.494 cm 6.1 , quad hd curved dynamic amoled, 19 9 550ppi , 8nm 64-bit octa-core max. 2.7 ghz 2.3 ghz 1.9 ghz , 3400mah, lte cat.20, android simply touch the glass to unlock. we ve moved security from the back of the phone to the front, fusing the ultrasonic fingerprint scanner directly into the screen. camera the next generation camera that captures life as you see it capture the wider world. use the ultra wide camera to take stunning, cinematic photos with a 123 degree field of vision. a smarter camera for better photos. the intelligent camera helps you shoot stunning photos by suggesting image compositions and automatically optimising your camera settings to the scene. performance next generation performance for a generation that can t wait power is yours to share. wireless powershare gives you the ability to share your power with other devices.1 and fast wireless charging 2.0 gets your phone back to 100 , faster stream and share, wherever life takes you. intelligent wi-fi reaches faster speeds with wi-fi 6, connecting reliably and securely even on public networks. and it seamlessly switches to lte to hit incredible speeds. a total game changer. we ve engineered both hardware and software to give you performance-enhanced gaming without lags. intelligence the phone that adapts to you so you don t have to adapt to it continuously working to keep you one step ahead. intelligence and advanced hardware learn how you use your phone, adapting to last longer and run more efficiently, giving you peak performance throughout your day. intuitive ai makes your daily life run smoother. bixby routines suggests frequently used apps and tasks based on time or location to develop a naturally smart experience just for you."
74941,Samsung,Smartphones,"samsung galaxy sm-g973f 15.5 cm 6.1 8 gb 128 gb white 3400 mah samsung sm-g973f smartphones samsung galaxy sm-g973f. display diagonal 15.5 cm 6.1 , display resolution 1440 x 3040 pixels. processor frequency 2.7 ghz. ram capacity 8 gb, ram type lpddr4x, internal storage capacity 128 gb. rear camera resolution numeric 12 mp, rear camera type triple camera. 3g, 4g. operating system installed android 9.0. battery capacity 3400 mah. product colour white. weight 157 g 15.494 cm 6.1 , quad hd curved dynamic amoled, 19 9 550ppi , 8nm 64-bit octa-core max. 2.7 ghz 2.3 ghz 1.9 ghz , 8gb ram lpddr4x , 3400mah, lte cat.20, android simply touch the glass to unlock. we ve moved security from the back of the phone to the front, fusing the ultrasonic fingerprint scanner directly into the screen. camera the next generation camera that captures life as you see it capture the wider world. use the ultra wide camera to take stunning, cinematic photos with a 123 degree field of vision. a smarter camera for better photos. the intelligent camera helps you shoot stunning photos by suggesting image compositions and automatically optimising your camera settings to the scene. performance next generation performance for a generation that can t wait power is yours to share. wireless powershare gives you the ability to share your power with other devices.1 and fast wireless charging 2.0 gets your phone back to 100 , faster stream and share, wherever life takes you. intelligent wi-fi reaches faster speeds with wi-fi 6, connecting reliably and securely even on public networks. and it seamlessly switches to lte to hit incredible speeds. a total game changer. we ve engineered both hardware and software to give you performance-enhanced gaming without lags. intelligence the phone that adapts to you so you don t have to adapt to it continuously working to keep you one step ahead. intelligence and advanced hardware learn how you use your phone, adapting to last longer and run more efficiently, giving you peak performance throughout your day. intuitive ai makes your daily life run smoother. bixby routines suggests frequently used apps and tasks based on time or location to develop a naturally smart experience just for you."
74660,Samsung,Smartphones,"samsung galaxy s10 sm-g973f 15.5 cm 6.1 8 gb 512 gb green 3400 mah samsung sm-g973f smartphones samsung galaxy s10 sm-g973f. display diagonal 15.5 cm 6.1 , display resolution 1440 x 3040 pixels, display type dynamic amoled. processor frequency 2.7 ghz, processor family samsung exynos. ram capacity 8 gb, internal storage capacity 512 gb. rear camera resolution numeric 12 mp, rear camera type triple camera. 3g, 4g. operating system installed android 9.0. battery capacity 3400 mah. product colour green. weight 157 g 15.494 cm 6.1 , quad hd curved dynamic amoled, 19 9 550ppi , 8nm 64-bit octa-core max. 2.7 ghz 2.3 ghz 1.9 ghz , 8gb ram lpddr4x , 3400mah, lte cat.20, android simply touch the glass to unlock. we ve moved security from the back of the phone to the front, fusing the ultrasonic fingerprint scanner directly into the screen. camera the next generation camera that captures life as you see it capture the wider world. use the ultra wide camera to take stunning, cinematic photos with a 123 degree field of vision. a smarter camera for better photos. the intelligent camera helps you shoot stunning photos by suggesting image compositions and automatically optimising your camera settings to the scene. performance next generation performance for a generation that can t wait power is yours to share. wireless powershare gives you the ability to share your power with other devices.1 and fast wireless charging 2.0 gets your phone back to 100 , faster stream and share, wherever life takes you. intelligent wi-fi reaches faster speeds with wi-fi 6, connecting reliably and securely even on public networks. and it seamlessly switches to lte to hit incredible speeds. a total game changer. we ve engineered both hardware and software to give you performance-enhanced gaming without lags. intelligence the phone that adapts to you so you don t have to adapt to it continuously working to keep you one step ahead. intelligence and advanced hardware learn how you use your phone, adapting to last longer and run more efficiently, giving you peak performance throughout your day. intuitive ai makes your daily life run smoother. bixby routines suggests frequently used apps and tasks based on time or location to develop a naturally smart experience just for you."
75448,Samsung,Smartphones,"samsung galaxy s10 sm-g973f 15.5 cm 6.1 8 gb 128 gb dual sim black 3400 mah samsung sm-g973f smartphones samsung galaxy s10 sm-g973f. display diagonal 15.5 cm 6.1 , display resolution 1440 x 3040 pixels, display type dynamic amoled. processor frequency 2.7 ghz. ram capacity 8 gb, internal storage capacity 128 gb. rear camera resolution numeric 12 mp, rear camera type triple camera. sim card capability dual sim, 3g, 4g. operating system installed android 9.0. battery capacity 3400 mah. product colour black. weight 157 g 15.494 cm 6.1 , quad hd curved dynamic amoled, 19 9 550ppi , 8nm 64-bit octa-core max. 2.7 ghz 2.3 ghz 1.9 ghz , 3400mah, lte cat.20, android simply touch the glass to unlock. we ve moved security from the back of the phone to the front, fusing the ultrasonic fingerprint scanner directly into the screen. camera the next generation camera that captures life as you see it capture the wider world. use the ultra wide camera to take stunning, cinematic photos with a 123 degree field of vision. a smarter camera for better photos. the intelligent camera helps you shoot stunning photos by suggesting image compositions and automatically optimising your camera settings to the scene. performance next generation performance for a generation that can t wait power is yours to share. wireless powershare gives you the ability to share your power with other devices.1 and fast wireless charging 2.0 gets your phone back to 100 , faster stream and share, wherever life takes you. intelligent wi-fi reaches faster speeds with wi-fi 6, connecting reliably and securely even on public networks. and it seamlessly switches to lte to hit incredible speeds. a total game changer. we ve engineered both hardware and software to give you performance-enhanced gaming without lags. intelligence the phone that adapts to you so you don t have to adapt to it continuously working to keep you one step ahead. intelligence and advanced hardware learn how you use your phone, adapting to last longer and run more efficiently, giving you peak performance throughout your day. intuitive ai makes your daily life run smoother. bixby routines suggests frequently used apps and tasks based on time or location to develop a naturally smart experience just for you."
75432,Samsung,Smartphones,"samsung galaxy s10 sm-g973f 15.5 cm 6.1 8 gb 128 gb hybrid dual sim 3400 mah samsung sm-g973f smartphones samsung galaxy s10 sm-g973f. display diagonal 15.5 cm 6.1 , display resolution 1440 x 3040 pixels, display type dynamic amoled. processor frequency 2.7 ghz. ram capacity 8 gb, ram type lppddr4x, internal storage capacity 128 gb. rear camera resolution numeric 12 mp, rear camera type triple camera. sim card capability hybrid dual sim, 3g, 4g. operating system installed android 9.0. battery capacity 3400 mah. weight 157 g none none"
74699,Samsung,Smartphones,"samsung galaxy s10 sm-g973f 15.5 cm 6.1 8 gb 512 gb blue 3400 mah samsung sm-g973f smartphones samsung galaxy s10 sm-g973f. display diagonal 15.5 cm 6.1 , display resolution 1440 x 3040 pixels, display type dynamic amoled. processor frequency 2.7 ghz. ram capacity 8 gb, ram type lpddr4, internal storage capacity 512 gb. rear camera resolution numeric 12 mp, rear camera type triple camera. 3g, 4g. operating system installed android 9.0. battery capacity 3400 mah. product colour blue. weight 157 g 15.494 cm 6.1 , quad hd curved dynamic amoled, 19 9 550ppi , 8nm 64-bit octa-core max. 2.7 ghz 2.3 ghz 1.9 ghz , 8gb ram lpddr4x , 3400mah, lte cat.20, android simply touch the glass to unlock. we ve moved security from the back of the phone to the front, fusing the ultrasonic fingerprint scanner directly into the screen. camera the next generation camera that captures life as you see it capture the wider world. use the ultra wide camera to take stunning, cinematic photos with a 123 degree field of vision. a smarter camera for better photos. the intelligent camera helps you shoot stunning photos by suggesting image compositions and automatically optimising your camera settings to the scene. performance next generation performance for a generation that can t wait power is yours to share. wireless powershare gives you the ability to share your power with other devices.1 and fast wireless charging 2.0 gets your phone back to 100 , faster stream and share, wherever life takes you. intelligent wi-fi reaches faster speeds with wi-fi 6, connecting reliably and securely even on public networks. and it seamlessly switches to lte to hit incredible speeds. a total game changer. we ve engineered both hardware and software to give you performance-enhanced gaming without lags. intelligence the phone that adapts to you so you don t have to adapt to it continuously working to keep you one step ahead. intelligence and advanced hardware learn how you use your phone, adapting to last longer and run more efficiently, giving you peak performance throughout your day. intuitive ai makes your daily life run smoother. bixby routines suggests frequently used apps and tasks based on time or location to develop a naturally smart experience just for you."
74658,Samsung,Smartphones,"samsung galaxy s10 sm-g973f 15.5 cm 6.1 8 gb 128 gb black 3400 mah samsung sm-g973f smartphones samsung galaxy s10 sm-g973f. display diagonal 15.5 cm 6.1 , display resolution 1440 x 3040 pixels, display type dynamic amoled. processor frequency 2.7 ghz, processor family samsung exynos. ram capacity 8 gb, internal storage capacity 128 gb. rear camera resolution numeric 12 mp, rear camera type triple camera. 3g, 4g. operating system installed android 9.0. battery capacity 3400 mah. product colour black. weight 157 g 15.494 cm 6.1 , quad hd curved dynamic amoled, 19 9 550ppi , 8nm 64-bit octa-core max. 2.7 ghz 2.3 ghz 1.9 ghz , 8gb ram lpddr4x , 3400mah, lte cat.20, android simply touch the glass to unlock. we ve moved security from the back of the phone to the front, fusing the ultrasonic fingerprint scanner directly into the screen. camera the next generation camera that captures life as you see it capture the wider world. use the ultra wide camera to take stunning, cinematic photos with a 123 degree field of vision. a smarter camera for better photos. the intelligent camera helps you shoot stunning photos by suggesting image compositions and automatically optimising your camera settings to the scene. performance next generation performance for a generation that can t wait power is yours to share. wireless powershare gives you the ability to share your power with other devices.1 and fast wireless charging 2.0 gets your phone back to 100 , faster stream and share, wherever life takes you. intelligent wi-fi reaches faster speeds with wi-fi 6, connecting reliably and securely even on public networks. and it seamlessly switches to lte to hit incredible speeds. a total game changer. we ve engineered both hardware and software to give you performance-enhanced gaming without lags. intelligence the phone that adapts to you so you don t have to adapt to it continuously working to keep you one step ahead. intelligence and advanced hardware learn how you use your phone, adapting to last longer and run more efficiently, giving you peak performance throughout your day. intuitive ai makes your daily life run smoother. bixby routines suggests frequently used apps and tasks based on time or location to develop a naturally smart experience just for you."
74671,Samsung,Smartphones,"samsung galaxy s10 sm-g973f 15.5 cm 6.1 8 gb 512 gb white 3400 mah samsung sm-g973f smartphones samsung galaxy s10 sm-g973f. display diagonal 15.5 cm 6.1 , display resolution 1440 x 3040 pixels, display type dynamic amoled. processor frequency 2.7 ghz, processor family samsung exynos. ram capacity 8 gb, internal storage capacity 512 gb. rear camera resolution numeric 12 mp, rear camera type triple camera. 3g, 4g. operating system installed android 9.0. battery capacity 3400 mah. product colour white. weight 157 g 15.494 cm 6.1 , quad hd curved dynamic amoled, 19 9 550ppi , 8nm 64-bit octa-core max. 2.7 ghz 2.3 ghz 1.9 ghz , 8gb ram lpddr4x , 3400mah, lte cat.20, android simply touch the glass to unlock. we ve moved security from the back of the phone to the front, fusing the ultrasonic fingerprint scanner directly into the screen. camera the next generation camera that captures life as you see it capture the wider world. use the ultra wide camera to take stunning, cinematic photos with a 123 degree field of vision. a smarter camera for better photos. the intelligent camera helps you shoot stunning photos by suggesting image compositions and automatically optimising your camera settings to the scene. performance next generation performance for a generation that can t wait power is yours to share. wireless powershare gives you the ability to share your power with other devices.1 and fast wireless charging 2.0 gets your phone back to 100 , faster stream and share, wherever life takes you. intelligent wi-fi reaches faster speeds with wi-fi 6, connecting reliably and securely even on public networks. and it seamlessly switches to lte to hit incredible speeds. a total game changer. we ve engineered both hardware and software to give you performance-enhanced gaming without lags. intelligence the phone that adapts to you so you don t have to adapt to it continuously working to keep you one step ahead. intelligence and advanced hardware learn how you use your phone, adapting to last longer and run more efficiently, giving you peak performance throughout your day. intuitive ai makes your daily life run smoother. bixby routines suggests frequently used apps and tasks based on time or location to develop a naturally smart experience just for you."
75620,Samsung,Smartphones,"samsung galaxy s10 sm-g973f 15.5 cm 6.1 8 gb 128 gb dual sim silver 3400 mah samsung sm-g973f smartphones samsung galaxy s10 sm-g973f. display diagonal 15.5 cm 6.1 , display resolution 1440 x 3040 pixels, display type dynamic amoled. processor frequency 2.7 ghz. ram capacity 8 gb, internal storage capacity 128 gb. rear camera resolution numeric 12 mp, rear camera type triple camera. sim card capability dual sim, 3g, 4g. operating system installed android 9.0. battery capacity 3400 mah. product colour silver. weight 157 g 15.494 cm 6.1 , quad hd curved dynamic amoled, 19 9 550ppi , 8nm 64-bit octa-core max. 2.7 ghz 2.3 ghz 1.9 ghz , 8gb ram lpddr4x , 3400mah, lte cat.20, android simply touch the glass to unlock. we ve moved security from the back of the phone to the front, fusing the ultrasonic fingerprint scanner directly into the screen. camera the next generation camera that captures life as you see it capture the wider world. use the ultra wide camera to take stunning, cinematic photos with a 123 degree field of vision. a smarter camera for better photos. the intelligent camera helps you shoot stunning photos by suggesting image compositions and automatically optimising your camera settings to the scene. performance next generation performance for a generation that can t wait power is yours to share. wireless powershare gives you the ability to share your power with other devices.1 and fast wireless charging 2.0 gets your phone back to 100 , faster stream and share, wherever life takes you. intelligent wi-fi reaches faster speeds with wi-fi 6, connecting reliably and securely even on public networks. and it seamlessly switches to lte to hit incredible speeds. a total game changer. we ve engineered both hardware and software to give you performance-enhanced gaming without lags. intelligence the phone that adapts to you so you don t have to adapt to it continuously working to keep you one step ahead. intelligence and advanced hardware learn how you use your phone, adapting to last longer and run more efficiently, giving you peak performance throughout your day. intuitive ai makes your daily life run smoother. bixby routines suggests frequently used apps and tasks based on time or location to develop a naturally smart experience just for you."

## C_id: 18, C_name: Product Warranty Services

In [162]:
df_cleaned[df_cleaned["ProductName"] == "60 M. NBD Scan Station 710"][["BrandInfo.BrandName", "Category.Name.Value", "metadata_clean"]]

,BrandInfo.BrandName,Category.Name.Value,metadata_clean
492895,Kodak Alaris,Warranty & Support Extensions,"kodak alaris 60 m. nbd scan station 710 kodak alaris 60 m. nbd scan station 710 warranty support extensions kodak alaris 60 m. nbd scan station 710. number of years 5 year s , next business day nbd none none"

In [163]:
df_cleaned[df_cleaned["ProductName"] == "Unified Switch/12 AP Upgrade for DWS-3160"][["BrandInfo.BrandName", "Category.Name.Value", "metadata_clean"]]

,BrandInfo.BrandName,Category.Name.Value,metadata_clean
149672,D-Link,Software Licenses/Upgrades,"d-link unified switch/12 ap upgrade for dws-3160 d-link unified switch/12 ap upgrade for dws-3160 software licenses/upgrades d-link unified switch/12 ap upgrade for dws-3160. license term in years 1 year s , software type upgrade unified switch/12 ap upgrade for dws-3160 warranty information the warranty period stated in this table supersedes and replaces the warranty period as stated in the user s manual for the relevant products. once the warranty terms have expired, d-link will no longer offer help desk support on the product. product warranty period two 2 years. for products bought before 1 january 2009, the warranty period is 11 years. limited lifetime warranty. this means the warranty will only end five years after d-link or its successor discontinues sales of the product in europe. you must register your product to get the limited lifetime warranty see below . limited lifetime warranty. this means the warranty will only end five years after d-link or its successor discontinues sales of the product in europe. you must register your product to get the limited lifetime warranty see below . in addition, d-link offers a free three months ips pattern / signature update after registration. to extend the ips pattern / signature update, customers can purchase 12 months subscription packages from their local d-link reseller.to register your firewall for your free three month update or to activate your authentication code that you receive when purchasing the 12 month update subscription, please visit our netdefend security portal."

In [164]:
df_cleaned[df_cleaned["ProductName"] == "AcerAdvantage extended warranty 3 years On-site for all Acer Projector families"][["BrandInfo.BrandName", "Category.Name.Value", "metadata_clean"]]

,BrandInfo.BrandName,Category.Name.Value,metadata_clean
458237,Acer,Warranty & Support Extensions,"acer aceradvantage extended warranty 3 years on-site for all projector families acer aceradvantage extended warranty 3 years on-site for all acer projector families warranty support extensions acer aceradvantage extended warranty 3 years on-site for all acer projector families. number of years 3 year s , service time hours x days 9x5, type on-site aceradvantage extended warranty 3 years on-site for all acer projector families aceradvantage is a warranty extension program for acer products that has been extremely successful in the countries where it has been implemented and is now broadened and extended to all eec countries. advantages - delivery fees are at acer s expense for repairs at our service centers and you will be reserved priority within our laboratories as an aceradvantage customer. - on-site service will be provided with the temporary replacement of the defective device with another projector replacement with the exactly same model is not guaranteed that will be left with the customer until the defective device is not repaired and delivered. aceradvantage covers all projector part defects that prevent product use. damages due to negligence or careless use, incorrect maintenance, maintenance by unauthorised personnel, transport in unsuitable packaging, any cause not attributable to manufacturer s defects, small damages such as scratches, scores, etc. derived from routine product use are excluded from service coverage. the lamp is not included in the extension service and will maintain the original warranty coverage of 90 days."

In [165]:
df_cleaned[df_cleaned["ProductName"] == "5Y On-site NBD 5x8"][["BrandInfo.BrandName", "Category.Name.Value", "metadata_clean"]]

,BrandInfo.BrandName,Category.Name.Value,metadata_clean
481270,Toshiba,Warranty & Support Extensions,"toshiba 5y on-site nbd 5x8 toshiba 5y on-site nbd 5x8 warranty support extensions toshiba 5y on-site nbd 5x8. number of years 5 year s , service time hours x days 8x5, type on-site, next business day nbd toshiba gons105eu-v 5 years gold on-site repair next business day response with warranty extension for satellite pro/tecra/portege/wt310 tablets europe"